// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct _HeapManager {
    // non-virtual members
    void * getMemory(int);  // 00FF7CAF
};
