// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct _LocaleUpdate {
    // non-virtual members
    _LocaleUpdate();  // 00FDCD51
};
