// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ArmoredCarObj : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB94A0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0BD0 slot 0x4  overrides cObj
    virtual void vf30();  // 00414B30 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00414DD0 slot 0x40  overrides Behavior
    virtual void vf44();  // 004151B0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00415800 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00414B60 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00414F40 slot 0x50  overrides Behavior
    virtual void vf54();  // 00414FC0 slot 0x54  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00415260 slot 0x19C  overrides Behavior
    // non-virtual members
    ArmoredCarObj();  // 00AB0BB0
};
