// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Ba0041 : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9530 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0CD0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00B789A0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B78780 slot 0x44  overrides Behavior
    virtual void vf48();  // 00B78D40 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00B78B60 slot 0x4C  overrides Behavior
};
