// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBa.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Ba0017 : public BehaviorBa {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8E00 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0080 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00404740 slot 0x40  overrides Behavior
    virtual void vf44();  // 00404610 slot 0x44  overrides Behavior
    virtual void vf48();  // 00404A80 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00404AA0 slot 0x4C  overrides Behavior
    // non-virtual members
    Ba0017();  // 00AB0040
};
