// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBa.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Ba0160 : public BehaviorBa {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9170 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0570 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 004058A0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00405890 slot 0x44  overrides Behavior
    virtual void vf48();  // 00405980 slot 0x48  overrides Behavior
    // non-virtual members
    Ba0160();  // 00AB0550
};
