// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBa.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Ba041a : public BehaviorBa {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9330 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0960 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00405A00 slot 0x40  overrides Behavior
    virtual void vf44();  // 00405A20 slot 0x44  overrides Behavior
    virtual void vf48();  // 00405A30 slot 0x48  overrides Behavior
    // non-virtual members
    Ba041a();  // 00AB0940
};
