// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBa.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Ba5000 : public BehaviorBa {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB95A0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0D80 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 004067D0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00406270 slot 0x44  overrides Behavior
    virtual void vf48();  // 004072F0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00406260 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00406890 slot 0x50  overrides Behavior
    // non-virtual members
    Ba5000();  // 00AB0D40
};
