// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BattleCollisionManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BattleCollisionManagerImplement : public BattleCollisionManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00();  // 00D7DC80 slot 0x0  overrides BattleCollisionManager
    virtual void vf04();  // 00D7BD20 slot 0x4  overrides BattleCollisionManager
    virtual void addOffense(int param_2);  // 00D781B0 slot 0x8  overrides BattleCollisionManager
    virtual undefined4 addDefense(int * param_2);  // 00D78210 slot 0xC  overrides BattleCollisionManager
    virtual void vf10(int param_2);  // 00D7B410 slot 0x10  overrides BattleCollisionManager
    virtual void vf14(int param_2);  // 00D7B470 slot 0x14  overrides BattleCollisionManager
    virtual int vf18(int param_2);  // 00D782A0 slot 0x18  overrides BattleCollisionManager
    virtual int vf1C(int param_2);  // 00D782E0 slot 0x1C  overrides BattleCollisionManager
    virtual int * vf20(int * param_2);  // 00D7A400 slot 0x20  overrides BattleCollisionManager
    virtual undefined4 * vf24(byte param_2);  // 00D7BD00 slot 0x24  overrides BattleCollisionManager
    virtual void vf28();  // 00D77330 slot 0x28  overrides BattleCollisionManager
    virtual void vf2C();  // 00D77340 slot 0x2C  overrides BattleCollisionManager
    virtual void vf30();  // 00D77350 slot 0x30  overrides BattleCollisionManager
    virtual undefined4 vf34();  // 00D78320 slot 0x34  overrides BattleCollisionManager
    virtual undefined4 vf38();  // 00D78330 slot 0x38  overrides BattleCollisionManager
    virtual undefined4 vf3C(int param_2);  // 00D78340 slot 0x3C  overrides BattleCollisionManager
    virtual undefined4 vf40(int param_2);  // 00D78360 slot 0x40  overrides BattleCollisionManager
};
