// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BattleParameterManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00() = 0;  // 00FDB68B slot 0x0
    virtual undefined addReference() = 0;  // 00FDB68B slot 0x4
    virtual void vf08(int param_2) = 0;  // 00FDB68B slot 0x8
    virtual undefined4 * vf0C(byte param_2);  // 00D72800 slot 0xC
    // non-virtual members
    BattleParameterManager();  // 00D76170
};
