// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BattleSituationManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00() = 0;  // 00FDB68B slot 0x0
    virtual void vf04() = 0;  // 00FDB68B slot 0x4
    virtual void vf08() = 0;  // 00FDB68B slot 0x8
    virtual undefined4 * vf0C(byte param_2);  // 00D72AD0 slot 0xC
    // non-virtual members
    BattleSituationManager();  // 00D76C30
};
