// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BattleRegionManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BattleRegionManagerImplement : public BattleRegionManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00(float param_2);  // 00401980 slot 0x0  overrides BattleRegionManager
    virtual void vf04(int param_2);  // 00401DE0 slot 0x4  overrides BattleRegionManager
    virtual void vf08(int param_2);  // 00401EB0 slot 0x8  overrides BattleRegionManager
    virtual bool vf0C(undefined4 param_1);  // 00401470 slot 0xC  overrides BattleRegionManager
    virtual void vf10();  // 00401100 slot 0x10  overrides BattleRegionManager
    virtual undefined4 * vf14(byte param_2);  // 004024C0 slot 0x14  overrides BattleRegionManager
    // non-virtual members
    ~BattleRegionManagerImplement();  // 004024A0
};
