// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorDebrisBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BehaviorDebrisExplode : public BehaviorDebrisBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 005DBF90 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 005DBF70 slot 0x4  overrides cObj
    virtual void vf30();  // 005DBF10 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 005E17A0 slot 0x40  overrides Behavior
    virtual void vf44();  // 005D8F00 slot 0x44  overrides Behavior
    virtual void vf48();  // 005DBF00 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005DE330 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005D8F10 slot 0x50  overrides Behavior
    virtual void vf54();  // 005E2C30 slot 0x54  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 005D8F20 slot 0x1B8  overrides Behavior
    // non-virtual members
    BehaviorDebrisExplode();  // 005DBF20
};
