// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBgBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BehaviorBg : public BehaviorBgBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AA7900 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6FE0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00AC3DD0 slot 0x40  overrides Behavior
    virtual void vf4C();  // 00AC3DE0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00AC3DF0 slot 0x50  overrides Behavior
    virtual undefined4 vfA8();  // 00AC3E00 slot 0xA8  overrides Behavior
    virtual undefined4 vfAC();  // 00AC3E10 slot 0xAC  overrides Behavior
    virtual undefined4 vfB0();  // 00AC3E20 slot 0xB0  overrides Behavior
    // non-virtual members
    BehaviorBg();  // 00AA6FC0
};
