// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BehaviorDebrisActor : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 005DA750 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 005DA730 slot 0x4  overrides cObj
    virtual void vf1C();  // 005D88E0 slot 0x1C  overrides cObj
    virtual void vf20();  // 005D88C0 slot 0x20  overrides cObj
    virtual void vf30();  // 005DA3F0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 005DFC00 slot 0x40  overrides Behavior
    virtual void vf44();  // 005D87F0 slot 0x44  overrides Behavior
    virtual void vf4C();  // 005DE4E0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005DC4A0 slot 0x50  overrides Behavior
    virtual void vf54();  // 005E1C90 slot 0x54  overrides Behavior
    virtual void vfC8(undefined4 param_2);  // 005D88A0 slot 0xC8  overrides Behavior
    virtual void vf114();  // 005D8730 slot 0x114  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 005D8760 slot 0x1D0  overrides Behavior
    // non-virtual members
    BehaviorDebrisActor();  // 005DA670
    static void vf48();  // 00A9D2F0
};
