// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BehaviorEmBody : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6840 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA61A0 slot 0x4  overrides cObj
    virtual void vf30();  // 00AD2CB0 slot 0x30  overrides cObj
    virtual void vf34();  // 00AD2E80 slot 0x34  overrides cObj
    virtual undefined4 startup();  // 00ACDD60 slot 0x40  overrides Behavior
    virtual void vf44();  // 00AC6380 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00AC6390 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00AC63A0 slot 0x50  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 00AD2CF0 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 00AD2D50 slot 0x1BC  overrides Behavior
    virtual void vf1C8();  // 00AD2E60 slot 0x1C8  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 00AA61B0 slot 0x1D0  overrides Behavior
    virtual void vf258();  // 00AD2DF0 slot 0x258  overrides Behavior
    virtual void vf260();  // 00AD2E40 slot 0x260  overrides Behavior
    // non-virtual members
    BehaviorEmBody();  // 00AA6180
    void ctor_00AB20E0();  // 00AB20E0
};
