// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBgBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BehaviorBh : public BehaviorBgBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AC7B20 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AC7B10 slot 0x4  overrides cObj
    virtual void vf34();  // 00AD33B0 slot 0x34  overrides cObj
    virtual undefined4 startup();  // 00AC79B0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00AC3FB0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00ACE590 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00AC78F0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00AE27F0 slot 0x50  overrides Behavior
    virtual void vf54();  // 00AC7940 slot 0x54  overrides Behavior
    virtual void vf254();  // 00AD3380 slot 0x254  overrides Behavior
    // non-virtual members
    BehaviorBh();  // 00AC7AB0
};
