// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BehaviorDebrisEmActor : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8450 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6B90 slot 0x4  overrides cObj
    virtual void vf1C();  // 005D8D70 slot 0x1C  overrides cObj
    virtual void vf20();  // 005D8D50 slot 0x20  overrides cObj
    virtual void vf30();  // 005DB7F0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 005E0E60 slot 0x40  overrides Behavior
    virtual void vf44();  // 005D8C80 slot 0x44  overrides Behavior
    virtual void vf4C();  // 005DDFB0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005DD0F0 slot 0x50  overrides Behavior
    virtual void vf54();  // 005DB4D0 slot 0x54  overrides Behavior
    virtual void vfC8(undefined4 param_2);  // 005D8D30 slot 0xC8  overrides Behavior
    virtual void vf114();  // 005D8C00 slot 0x114  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 005D8C30 slot 0x1D0  overrides Behavior
    // non-virtual members
    BehaviorDebrisEmActor();  // 00AA6B60
};
