// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct BehaviorImpactWave : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7AC0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA67F0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00602C20 slot 0x40  overrides Behavior
    virtual void vf44();  // 00602C50 slot 0x44  overrides Behavior
    virtual void vf50();  // 00602D50 slot 0x50  overrides Behavior
    // non-virtual members
    BehaviorImpactWave();  // 00AA67D0
};
