// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBh.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bh0140 : public BehaviorBh {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7680 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAE9F0 slot 0x4  overrides cObj
    virtual void vf2EC();  // 005B0B70 slot 0x2EC  overrides Behavior
    // non-virtual members
    Bh0140();  // 00AAE9D0
    static void vf54();  // 00AC7940
};
