// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBh.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bh0303 : public BehaviorBh {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9A20 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1700 slot 0x4  overrides cObj
    virtual void vf30();  // 00603E30 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00603DF0 slot 0x40  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 00603E10 slot 0x1D0  overrides Behavior
    // non-virtual members
    Bh0303();  // 00AB16E0
};
