// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm020e : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB93B0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0A40 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00411680 slot 0x40  overrides Behavior
    virtual void vf44();  // 004116F0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00411700 slot 0x48  overrides Behavior
    // non-virtual members
    Bm020e();  // 00AB0A20
};
