// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm0292 : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB94D0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0C20 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00412060 slot 0x40  overrides Behavior
    virtual void vf44();  // 00411FA0 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00411FB0 slot 0x4C  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 004120C0 slot 0x1D0  overrides Behavior
    // non-virtual members
    Bm0292();  // 00AB0C00
};
