// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm0238 : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8FC0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB02E0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 004119E0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00411A10 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00411A30 slot 0x4C  overrides Behavior
    // non-virtual members
    Bm0238();  // 00AB02C0
};
