// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm0304 : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9080 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB03E0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00412490 slot 0x40  overrides Behavior
    virtual void vf44();  // 00412530 slot 0x44  overrides Behavior
    virtual void vf50();  // 00412510 slot 0x50  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 00412540 slot 0x1D0  overrides Behavior
    // non-virtual members
    Bm0304();  // 00AB03C0
};
