// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm0403 : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9140 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0520 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00413990 slot 0x40  overrides Behavior
    virtual void vf50();  // 00413030 slot 0x50  overrides Behavior
    // non-virtual members
    Bm0403();  // 00AB0500
};
