// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm0429 : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB92A0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0890 slot 0x4  overrides cObj
    virtual void vf30();  // 00413E10 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00413DB0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00413D80 slot 0x44  overrides Behavior
    virtual void vf48();  // 00413D70 slot 0x48  overrides Behavior
    virtual void vf2F4();  // 00413E60 slot 0x2F4  overrides Behavior
    // non-virtual members
    Bm0429();  // 00AB0870
};
