// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "P458AtqScr.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm5400 : public P458AtqScr {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AC1170 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AC1140 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00414930 slot 0x40  overrides Behavior
    virtual void vf44();  // 00414970 slot 0x44  overrides Behavior
    virtual void vf48();  // 00414980 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00414960 slot 0x4C  overrides Behavior
    // non-virtual members
    Bm5400();  // 00AC1120
};
