// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Bm6000 : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB98A0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1510 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00603E80 slot 0x40  overrides Behavior
    virtual void vf48();  // 00603EA0 slot 0x48  overrides Behavior
    // non-virtual members
    Bm6000();  // 00AB14F0
};
