// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "CAkFileLocationBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CAkDefaultIOHookBlocking : public CAkFileLocationBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static int vf14(int param_1, undefined4 param_2, LPVOID param_3, DWORD * param_4);  // 00DEF3D0
    static int vf18(int param_1, undefined4 param_2, undefined4 param_3, DWORD * param_4);  // 00DEF430
    static int vf04(int param_1);  // 00DEF490
    static undefined4 vf08();  // 00DEF4B0
    static void vf0C();  // 00DEF4C0
    static bool vf10();  // 00DEF4D0
    static void vf00();  // 00DF5A00
    static void vf00_00DF5AB0();  // 00DF5AB0
};
