// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CAkDefaultLowLevelIODispatcher {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00();  // 00DF5A50 slot 0x0  overrides AK::StreamMgr::IAkFileLocationResolver
    virtual undefined vf04();  // 00DEEA10 slot 0x4  overrides AK::StreamMgr::IAkFileLocationResolver
    virtual undefined vf08();  // 00DEE9B0 slot 0x8  overrides AK::StreamMgr::IAkFileLocationResolver
    virtual undefined4 vf0C(int param_2);  // 00DEEA70 slot 0xC
    virtual void vf10();  // 00DEEAA0 slot 0x10
};
