// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "CAkFileLocationBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CAkDefaultIOHookDeferred : public CAkFileLocationBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static undefined4 vf14(int param_1, undefined4 param_2, DWORD * param_3);  // 00DEF800
    static undefined4 vf18(int param_1, undefined4 param_2, DWORD * param_3);  // 00DEF870
    static void vf1C(int param_1, undefined4 param_2, char * param_3);  // 00DEF8E0
    static int vf04(int param_1);  // 00DEF900
    static int vf08(int param_1);  // 00DEF920
    static void vf0C();  // 00DEF940
    static bool vf10();  // 00DEF950
    static void vf00();  // 00DF59F0
    static void vf00_00DF5B00();  // 00DF5B00
};
