// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CAkRegistryMgr {
    // non-virtual members
    CAkRegisteredObj * GetObjAndAddref(uint param_1);  // 013D43C0
};
