// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCamera.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cCameraApp : public cCamera {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf08();  // 00DC09A0 slot 0x8
    virtual void vf0C();  // 00DC0C90 slot 0xC
    virtual void vf10() = 0;  // 00FDB68B slot 0x10
    // non-virtual members
    static void vf00();  // 00C407C0
};
