// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cChapterBg : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009AADD0 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00989230 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 009AADF0 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cChapterBg();  // 00989130
    static void vf0C();  // 00989190
    static void vf10();  // 009891A0
    static void vf18();  // 009891B0
    ~cChapterBg();  // 0099A600
    static void vf04();  // 00CE4C50
};
