// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManagerEx.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cCodecWindowParts : public cCustomObjCtrlManagerEx {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CE32E0 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf04();  // 00CD1490 slot 0x4  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00D214A0 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 00D220A0 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cCodecWindowParts();  // 00CD13B0
};
