// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cCodecMenuParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009AD830 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 0099B1C0 slot 0x8  overrides cCustomObjCtrlManager
    virtual void vf0C();  // 0098A510 slot 0xC  overrides cCustomObjCtrlManager
    virtual void create();  // 009AD850 slot 0x14  overrides cCustomObjCtrlManager
};
