// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cCodecMenu {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0099C620 slot 0x0
    // non-virtual members
    cCodecMenu();  // 0098A850
    void ctor_0098A880();  // 0098A880
};
