// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cCollectionLockedItemParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0099D510 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 0098BC60 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 0098BC70 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cCollectionLockedItemParts();  // 0098BBA0
    void ctor_0098BBF0();  // 0098BBF0
};
