// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cComboListMenu : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0099DFB0 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 009B0DA0 slot 0x8  overrides cCustomObjCtrlManager
    virtual void vf0C();  // 0098D1F0 slot 0xC  overrides cCustomObjCtrlManager
    virtual void create();  // 009BA4A0 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cComboListMenu();  // 0098CFF0
    ~cComboListMenu();  // 0098D100
};
