// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cCountDispParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CE3350 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00CB7020 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 00CEB370 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cCountDispParts();  // 00D2C4B0
};
