// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cCustomizeMenuParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0098F7C0 slot 0x0  overrides cCustomObjCtrlManager
    // non-virtual members
    cCustomizeMenuParts();  // 0098F770
};
