// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cDrawStencilWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00A341D0 slot 0x0  overrides Hw::cOtWork
    virtual void draw();  // 00A29350 slot 0x4  overrides Hw::cOtWork
    // non-virtual members
    cDrawStencilWork();  // 00A2A050
    void ctor_00A3D4D0();  // 00A3D4D0
};
