// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEffectSouDispBase : public cCustomObjWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D0B980 slot 0x0  overrides cUIWork
    virtual undefined4 vf14(undefined4 param_2);  // 00D235C0 slot 0x14  overrides cCustomObjWorkBase
    // non-virtual members
    cEffectSouDispBase();  // 00D0B930
};
