// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "GimmickBehaviorBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cElectromagneticBarrierNode : public GimmickBehaviorBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA9B0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB61F0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005E3630 slot 0x40  overrides Behavior
    virtual void vf44();  // 005E2EF0 slot 0x44  overrides Behavior
    virtual void vf50();  // 005E2F10 slot 0x50  overrides Behavior
    virtual void vf320();  // 00AB6200 slot 0x320  overrides GimmickBehaviorBase
    virtual void vf324();  // 00AB6210 slot 0x324  overrides GimmickBehaviorBase
    virtual void vf328();  // 005E35D0 slot 0x328  overrides GimmickBehaviorBase
    // non-virtual members
    cElectromagneticBarrierNode();  // 00AB61D0
};
