// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorPartsModel.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEm0010Magazine : public BehaviorPartsModel {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7C10 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAF150 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00B2B6A0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B2B770 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00B31530 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00B2B780 slot 0x50  overrides Behavior
    virtual void vf54();  // 00B2B790 slot 0x54  overrides Behavior
};
