// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEnemyLeftHandInfo {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int * vf00(byte param_2);  // 00CD3770 slot 0x0
    // non-virtual members
    cEnemyLeftHandInfo();  // 00CB8450
};
