// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEnemyTargetParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CDE8D0 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00CB7F00 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 00CFF320 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cEnemyTargetParts();  // 00CD2E40
    void ctor_00D2E280();  // 00D2E280
};
