// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEnergyGaugeWhiteRaidenBase : public cCustomObjWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D0BB60 slot 0x0  overrides cUIWork
    virtual undefined4 vf14(undefined4 param_2);  // 00D23FA0 slot 0x14  overrides cCustomObjWorkBase
    // non-virtual members
    cEnergyGaugeWhiteRaidenBase();  // 00D0BB10
};
