// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEnemyEnergyGauge {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CD2C50 slot 0x0
    // non-virtual members
    cEnemyEnergyGauge();  // 00CB7DB0
    void ctor_00CB7DE0();  // 00CB7DE0
};
