// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderToneCurveBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderToneCurveRGB_MB_G : public cEspShaderToneCurveBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8D930 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F66EA0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderToneCurveRGB_MB_G();  // 00F8D910
};
