// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F40630 slot 0x0
    virtual undefined preTrans() = 0;  // 00FDB68B slot 0x4
    virtual void vf08() = 0;  // 00FDB68B slot 0x8
    virtual void vf0C();  // 009CD650 slot 0xC
    virtual void addOtTransList();  // 00ED4C70 slot 0x10
    virtual void vf14();  // 00ED4C80 slot 0x14
    virtual bool vf18(int param_2);  // 00ED4C90 slot 0x18
    // non-virtual members
    cEspBase();  // 00EDB150
    static void addOtTransList_00F099B0();  // 00F099B0
    void ctor_00F128E0();  // 00F128E0
    void ctor_00F12970();  // 00F12970
    void ctor_00F12A00();  // 00F12A00
    void ctor_00F17660();  // 00F17660
    void ctor_00F1E960();  // 00F1E960
    void ctor_00F200E0();  // 00F200E0
    void ctor_00F20170();  // 00F20170
    static void addOtTransList_2();  // 00F2C540
    void ctor_00F403F0();  // 00F403F0
    void ctor_00F40470();  // 00F40470
    void ctor_00F404B0();  // 00F404B0
    void ctor_00F404F0();  // 00F404F0
    void ctor_00F40530();  // 00F40530
    void ctor_00F40950();  // 00F40950
};
