// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspList {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F45620 slot 0x0
    virtual undefined4 startup(uint param_2, undefined4 param_3);  // 00F435A0 slot 0x4
    virtual void vf08();  // 00F435C0 slot 0x8
    virtual void vf0C();  // 00F40B30 slot 0xC
    virtual void vf10();  // 00F43640 slot 0x10
    virtual void preTrans();  // 00F40B50 slot 0x14
    virtual void vf18();  // 00F436C0 slot 0x18
    virtual undefined4 vf1C(undefined4 param_2);  // 00F440B0 slot 0x1C
    virtual void vf20(int * param_2, int * param_3) = 0;  // 00FDB68B slot 0x20
    // non-virtual members
    cEspList();  // 00F441C0
    void ctor_00F455D0();  // 00F455D0
};
