// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderSoftPT3D.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderSoftPT3DMask : public cEspShaderSoftPT3D {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8B080 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F5FC40 slot 0x8  overrides cEspShaderBase
    virtual void vf0C();  // 00F5C5D0 slot 0xC  overrides cEspShaderBase
    virtual undefined4 vf10(uint param_2);  // 00F5FDA0 slot 0x10  overrides cEspShaderSoftPT
    // non-virtual members
    cEspShaderSoftPT3DMask();  // 00F8AF90
};
