// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderToneCurveMask.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderToneCurveAlMask : public cEspShaderToneCurveMask {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8BDF0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F623D0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderToneCurveAlMask();  // 00F8BDD0
};
