// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspDrawWork.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspDrawWork44_PT : public cEspDrawWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00F3FA70 slot 0x0  overrides Hw::cOtWork
    virtual void draw();  // 00EDA140 slot 0x4  overrides Hw::cOtWork
    // non-virtual members
    cEspDrawWork44_PT();  // 00F3B570
};
