// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspControler.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspControlerEvent : public cEspControler {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00EAAD30 slot 0x0  overrides cEspControler
    // non-virtual members
    cEspControlerEvent();  // 00EAAA30
    void ctor_00EAAAA0();  // 00EAAAA0
};
