// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderPsMask_Edge_Mul.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderPsMask_EdgeMulOnly : public cEspShaderPsMask_Edge_Mul {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8E500 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F6A4B0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderPsMask_EdgeMulOnly();  // 00F83980
};
