// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspStrip.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEsp103Strip : public cEspStrip {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009D44E0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 009D7BC0 slot 0x4  overrides cEspBase
    virtual void vf08();  // 009D7C40 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 009D7D10 slot 0x10  overrides cEspBase
    virtual void vf14();  // 009CFD20 slot 0x14  overrides cEspBase
    virtual void vf1C();  // 009CF990 slot 0x1C  overrides cEspStrip
    virtual void vf20();  // 009D6E40 slot 0x20  overrides cEspStrip
    // non-virtual members
    cEsp103Strip();  // 009D4490
};
