// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspDrawWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009D5510 slot 0x0  overrides Hw::cOtWork
    virtual void draw();  // 00F46BA0 slot 0x4  overrides Hw::cOtWork
    // non-virtual members
    cEspDrawWork(int param_2, int param_3);  // 009E2A40
    cEspDrawWork();  // 009E2BF0
    void ctor_00F26D30();  // 00F26D30
    void ctor_00F29530(int param_2, int param_3);  // 00F29530
    cEspDrawWork(int param_2);  // 00F297E0
    cEspDrawWork(undefined4 param_2);  // 00F2B2C0
};
