// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderPointLight3D.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderPointLight3D_Fog : public cEspShaderPointLight3D {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8E620 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F6AB30 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderPointLight3D_Fog();  // 00F8E5F0
};
