// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderSoftPTSubFade.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderSoftPT3DSubFade : public cEspShaderSoftPTSubFade {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8BD10 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F61EF0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderSoftPT3DSubFade();  // 00F82100
};
