// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspDrawWork.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspDrawWork44_P : public cEspDrawWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00F3FA40 slot 0x0  overrides Hw::cOtWork
    virtual void draw();  // 00EDA100 slot 0x4  overrides Hw::cOtWork
    // non-virtual members
    cEspDrawWork44_P(undefined4 param_2);  // 00F09030
    cEspDrawWork44_P();  // 00F3B550
};
