// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderProjection_Fog.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderProjection_Fog_Mul : public cEspShaderProjection_Fog {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8E930 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F6BCE0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderProjection_Fog_Mul();  // 00F8E8F0
};
