// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderProjection.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderProjection_Fog : public cEspShaderProjection {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8E8C0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F6BB80 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderProjection_Fog();  // 00F850A0
};
