// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderMultiParticleBillbord.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderMultiParticleBillbordAtl : public cEspShaderMultiParticleBillbord {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8C7D0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F63C90 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderMultiParticleBillbordAtl();  // 00F8C7B0
};
