// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderSoftPT.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspShaderSoftPTMono : public cEspShaderSoftPT {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8B590 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F60BC0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cEspShaderSoftPTMono();  // 00F8B570
};
