// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspDrawWork.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspDrawWork_Emt10 : public cEspDrawWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00F3F010 slot 0x0  overrides Hw::cOtWork
};
