// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEspChain : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ECD6E0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F2E180 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F13470 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 00F278F0 slot 0x10  overrides cEspBase
    virtual void vf14();  // 00EE2200 slot 0x14  overrides cEspBase
    virtual void vf1C(int param_2);  // 00EE2250 slot 0x1C
    virtual void vf20(int param_2);  // 00F0DC20 slot 0x20
    virtual void vf24(int param_2);  // 00F00280 slot 0x24
    virtual void vf28(int param_1);  // 00EE24D0 slot 0x28
    // non-virtual members
    cEspChain();  // 00ECD5E0
};
