// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEventCutData {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00();  // 00D7EAA0 slot 0x0
    virtual undefined4 * vf04(byte param_2);  // 00D7E0E0 slot 0x4
    // non-virtual members
    cEventCutData(int * param_2, int param_3);  // 00D7FC40
    cEventCutData(int param_2);  // 00D7FE70
    cEventCutData();  // 015F0700
};
