// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cEventCutWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(undefined4 param_2);  // 00D7EBB0 slot 0x0
    virtual void vf04();  // 00D7F610 slot 0x4
    virtual void vf08();  // 00D7FBD0 slot 0x8
    virtual undefined4 * vf0C(byte param_2);  // 00D7FA50 slot 0xC
    // non-virtual members
    cEventCutWork();  // 00D7FA10
    void ctor_015F0760();  // 015F0760
};
