// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShader01 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC3CD0 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EBF700 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShader01();  // 00EBF5A0
    ~cFilterShader01();  // 015F1710
};
