// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cFilterShader2xAAResolve.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShader2xAAResolveRot90 : public cFilterShader2xAAResolve {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC4170 slot 0x0  overrides Hw::cShader
    // non-virtual members
    cFilterShader2xAAResolveRot90();  // 00EC4120
};
