// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShaderCopyTex {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC4250 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EC0BC0 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShaderCopyTex();  // 00EC0AB0
    void ctor_00EC1C70();  // 00EC1C70
    ~cFilterShaderCopyTex();  // 015F1B80
};
