// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShader00 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC3C60 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EBF550 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShader00();  // 00EBF300
    void ctor_00EBF8D0();  // 00EBF8D0
    void ctor_015F1680();  // 015F1680
};
