// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShader05 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC3E10 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EBFDA0 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShader05();  // 00EBFC30
    void ctor_015F1860();  // 015F1860
};
