// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShader09 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC3FA0 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EC0580 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShader09();  // 00EC0380
    ~cFilterShader09();  // 015F1A30
};
