// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShaderGather {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC42C0 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EC1030 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShaderGather();  // 00EC0D20
    void ctor_00EC22A0();  // 00EC22A0
    ~cFilterShaderGather();  // 015F1BF0
};
