// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShaderZConversion {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC4380 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EC1310 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShaderZConversion();  // 00EC1200
    void ctor_015F1CB0();  // 015F1CB0
};
