// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShader09_Sub2 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC4020 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EC0820 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShader09_Sub2();  // 00EC06F0
    void ctor_015F1AA0();  // 015F1AA0
};
