// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cFilterShaderOculus {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00EC4090 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00EBDB30 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cFilterShaderOculus();  // 00EC0BF0
    ~cFilterShaderOculus();  // 015F1AF0
};
