// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cGameResultDLC3Base : public cCustomObjWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D0FEA0 slot 0x0  overrides cUIWork
    virtual undefined4 vf14(undefined4 param_2);  // 00D28CA0 slot 0x14  overrides cCustomObjWorkBase
    // non-virtual members
    cGameResultDLC3Base();  // 00D0FE50
};
