// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cGeckoBattery : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7890 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAEF30 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00B76E90 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B76FF0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00B77AD0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00B77D30 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00B769E0 slot 0x50  overrides Behavior
    virtual void vf25C(undefined4 param_2, int param_3, int param_4);  // 00B76D50 slot 0x25C  overrides Behavior
};
