// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cGrenadeGuideLine {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CD4470 slot 0x0
    // non-virtual members
    cGrenadeGuideLine();  // 00CB92A0
    void ctor_00CB92E0();  // 00CB92E0
};
