// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCharacterProxy.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CharacterProxy : public hkpCharacterProxy {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf00();  // 008E1130
    static void vf00_008E1140();  // 008E1140
    static void vf04();  // 008E1590
    static void vf0C(int param_2);  // 008E15A0
    static void vf10();  // 008E15D0
    static void vf14();  // 008E15E0
    static void vf04_008E1680();  // 008E1680
    static void vf0C_008E1690(int param_2);  // 008E1690
    static void vf10_008E16C0();  // 008E16C0
    CharacterProxy();  // 008E8420
    static void vf10_01269940(float * param_2, float * param_3, float param_4);  // 01269940
    static void vf08(int param_2);  // 01269B00
    static void vf08_01269C50(int param_2);  // 01269C50
    static undefined vf0C_0126CB20();  // 0126CB20
};
