// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cHeadMarkStunParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CE3840 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00CBA440 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 00D00C30 slot 0x14  overrides cCustomObjCtrlManager
};
