// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemFixBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemFixVRPda : public cItemFixBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AC1200 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AC11E0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005EB060 slot 0x40  overrides Behavior
    virtual void vf44();  // 005EB180 slot 0x44  overrides Behavior
    virtual void vf48();  // 005ED6F0 slot 0x48  overrides Behavior
    virtual void vf54();  // 005EB190 slot 0x54  overrides Behavior
};
