// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemFixBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemFixVRPdaDlc : public cItemFixBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9C50 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1AA0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0085B0C0 slot 0x40  overrides Behavior
    virtual void vf44();  // 0085BDA0 slot 0x44  overrides Behavior
    virtual void vf48();  // 0085B290 slot 0x48  overrides Behavior
    virtual void vf54();  // 0085AE30 slot 0x54  overrides Behavior
    // non-virtual members
    cItemFixVRPdaDlc();  // 00AB1A60
};
