// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemStageDropInstant.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemStageDropViscera : public cItemStageDropInstant {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual char * vf00();  // 0094D420 slot 0x0  overrides cItemBase
    virtual undefined4 * vf04(byte param_2);  // 009503E0 slot 0x4  overrides cItemBase
    virtual void vf0C();  // 0094D480 slot 0xC  overrides cItemBase
    virtual char * vf10();  // 0094D430 slot 0x10  overrides cItemStageDrop
    virtual void vf1C();  // 00950420 slot 0x1C  overrides cItemStageDrop
    virtual void vf24();  // 0094D510 slot 0x24  overrides cItemStageDrop
    virtual void vf28();  // 0094D560 slot 0x28  overrides cItemStageDrop
    virtual void vf2C();  // 0094D440 slot 0x2C  overrides cItemStageDrop
};
