// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemObjectBase : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AA8C00 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA7340 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005E9630 slot 0x40  overrides Behavior
    virtual void vf44();  // 005E9BB0 slot 0x44  overrides Behavior
    virtual void vf48();  // 005E9C40 slot 0x48  overrides Behavior
    virtual void vf54();  // 005E9CC0 slot 0x54  overrides Behavior
    virtual undefined4 vf300();  // 005E86F0 slot 0x300
    virtual undefined4 vf304(int param_1);  // 005EBA20 slot 0x304
    virtual undefined4 vf308();  // 00AA7350 slot 0x308
    // non-virtual members
    cItemObjectBase();  // 00AA7300
    void ctor_00AB1360();  // 00AB1360
    void ctor_00AB13C0();  // 00AB13C0
    void ctor_00AB1420();  // 00AB1420
    void ctor_00AB1490();  // 00AB1490
    void ctor_00AB1A60();  // 00AB1A60
    void ctor_00AB6700();  // 00AB6700
    void ctor_00AC0D90();  // 00AC0D90
    void ctor_00AC0E10();  // 00AC0E10
    void ctor_00AC11A0();  // 00AC11A0
};
