// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemObjectBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemViscelaBase : public cItemObjectBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABABA0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB6750 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005EB6A0 slot 0x40  overrides Behavior
    virtual void vf44();  // 005EB780 slot 0x44  overrides Behavior
    virtual void vf48();  // 005ED850 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005EC410 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005EB7E0 slot 0x50  overrides Behavior
    virtual void vf54();  // 005EB7B0 slot 0x54  overrides Behavior
    virtual void vf30C();  // 005EC210 slot 0x30C
    virtual void vf310();  // 005E9390 slot 0x310
    virtual void vf314();  // 00AB6760 slot 0x314
};
