// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemStageDrop.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemStageDropCollectable : public cItemStageDrop {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual char * vf00();  // 0094D280 slot 0x0  overrides cItemBase
    virtual undefined4 * vf04(byte param_2);  // 00950280 slot 0x4  overrides cItemBase
    virtual char * vf10();  // 0094D290 slot 0x10  overrides cItemStageDrop
    virtual void vf1C();  // 00953180 slot 0x1C  overrides cItemStageDrop
    virtual void vf2C();  // 0094D320 slot 0x2C  overrides cItemStageDrop
};
