// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemInfoDisp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CD4EF0 slot 0x0
    // non-virtual members
    cItemInfoDisp();  // 00CBB0C0
};
