// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemStageDrop.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemStageDropCollectableDlc : public cItemStageDrop {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual char * vf00();  // 0094F200 slot 0x0  overrides cItemBase
    virtual undefined4 * vf04(byte param_2);  // 009520F0 slot 0x4  overrides cItemBase
    virtual char * vf10();  // 0094F210 slot 0x10  overrides cItemStageDrop
    virtual void vf1C();  // 00952130 slot 0x1C  overrides cItemStageDrop
    virtual void vf2C();  // 0094F2A0 slot 0x2C  overrides cItemStageDrop
    // non-virtual members
    cItemStageDropCollectableDlc();  // 0094F1B0
};
