// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemPossessionBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemPossessionCure : public cItemPossessionBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual char * vf00();  // 0094DAE0 slot 0x0  overrides cItemBase
    virtual undefined4 * vf04(byte param_2);  // 0094DB00 slot 0x4  overrides cItemBase
    virtual void vf08();  // 00949C60 slot 0x8  overrides cItemBase
    virtual char * vf10();  // 0094DAF0 slot 0x10  overrides cItemPossessionBase
    virtual undefined4 vf14();  // 00949C40 slot 0x14  overrides cItemPossessionBase
    virtual bool vf30();  // 0094DB50 slot 0x30  overrides cItemPossessionBase
    virtual bool vf34();  // 0094DCB0 slot 0x34  overrides cItemPossessionBase
    virtual bool vf38();  // 0094DE20 slot 0x38  overrides cItemPossessionBase
};
