// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemPossessionBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemPossessionWeaponGun : public cItemPossessionBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual char * vf00();  // 00949910 slot 0x0  overrides cItemBase
    virtual undefined4 * vf04(byte param_2);  // 0094D950 slot 0x4  overrides cItemBase
    virtual void vf08();  // 00949970 slot 0x8  overrides cItemBase
    virtual char * vf10();  // 00949920 slot 0x10  overrides cItemPossessionBase
    virtual void vf18(int param_2);  // 0094DA00 slot 0x18  overrides cItemPossessionBase
    virtual void vf1C();  // 0094D9B0 slot 0x1C  overrides cItemPossessionBase
    virtual void vf20(int param_2);  // 00949A60 slot 0x20  overrides cItemPossessionBase
    virtual void vf28(int param_2);  // 00949A80 slot 0x28  overrides cItemPossessionBase
    virtual bool vf2C();  // 00949B00 slot 0x2C  overrides cItemPossessionBase
    virtual bool vf30();  // 009499A0 slot 0x30  overrides cItemPossessionBase
    virtual undefined4 vf3C();  // 00949AB0 slot 0x3C  overrides cItemPossessionBase
    virtual undefined4 vf40();  // 009499E0 slot 0x40  overrides cItemPossessionBase
    virtual bool vf44();  // 0094D9A0 slot 0x44  overrides cItemPossessionBase
    virtual undefined4 vf48();  // 00949A20 slot 0x48  overrides cItemPossessionBase
    virtual undefined4 vf4C();  // 00949A30 slot 0x4C  overrides cItemPossessionBase
    virtual undefined4 vf50();  // 00949A40 slot 0x50  overrides cItemPossessionBase
    virtual void vf54(int param_2);  // 00949AC0 slot 0x54  overrides cItemPossessionBase
};
