// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cItemPossessionBase : public cItemBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual char * vf00();  // 009496E0 slot 0x0  overrides cItemBase
    virtual undefined4 * vf04(byte param_2);  // 0094D7D0 slot 0x4  overrides cItemBase
    virtual void vf08();  // 00949780 slot 0x8  overrides cItemBase
    virtual char * vf10();  // 009496F0 slot 0x10
    virtual undefined4 vf14();  // 00949790 slot 0x14
    virtual void vf18(int param_2);  // 0094D870 slot 0x18
    virtual void vf1C();  // 0094D820 slot 0x1C
    virtual void vf20(int param_2);  // 0094D8F0 slot 0x20
    virtual void vf24();  // 0094D8D0 slot 0x24
    virtual void vf28(int param_2);  // 0094D910 slot 0x28
    virtual bool vf2C();  // 00949850 slot 0x2C
    virtual bool vf30();  // 009497A0 slot 0x30
    virtual bool vf34();  // 009497D0 slot 0x34
    virtual bool vf38();  // 00949800 slot 0x38
    virtual undefined4 vf3C();  // 00949830 slot 0x3C
    virtual undefined4 vf40();  // 00949840 slot 0x40
    virtual bool vf44();  // 00949870 slot 0x44
    virtual undefined4 vf48();  // 00949700 slot 0x48
    virtual undefined4 vf4C();  // 00949710 slot 0x4C
    virtual undefined4 vf50();  // 00949720 slot 0x50
    virtual void vf54(int param_2);  // 009498B0 slot 0x54
    // non-virtual members
    cItemPossessionBase(int * param_1);  // 00951C80
    cItemPossessionBase(undefined4 param_1, undefined4 * param_2);  // 009530A0
};
