// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cJammingDie {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CD51E0 slot 0x0
    // non-virtual members
    cJammingDie();  // 00CBB4A0
    void ctor_00CBB4D0();  // 00CBB4D0
};
