// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cLightVolumeObj : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABAA90 slot 0x0  overrides cParts
    virtual undefined4 vf08();  // 00A002E0 slot 0x8  overrides cObj
    // non-virtual members
    cLightVolumeObj();  // 00AA6FA0
};
