// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cLightDataMinimum.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cLightDataMinimumEv : public cLightDataMinimum {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined ** vf00();  // 00A40C30 slot 0x0  overrides cObject
    virtual undefined4 * vf04(byte param_2);  // 00A40C40 slot 0x4  overrides cObject
    // non-virtual members
    cLightDataMinimumEv();  // 00A40C10
};
