// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "GimmickBehaviorBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cManupilateNodeSingleDlc : public GimmickBehaviorBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9C70 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1AE0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0085ACF0 slot 0x40  overrides Behavior
    virtual void vf44();  // 0085A0A0 slot 0x44  overrides Behavior
    virtual void vf4C();  // 0085A380 slot 0x4C  overrides Behavior
    virtual void vf318();  // 0085A130 slot 0x318  overrides GimmickBehaviorBase
    virtual void vf31C();  // 0085A5F0 slot 0x31C  overrides GimmickBehaviorBase
    virtual void vf320();  // 0085A0C0 slot 0x320  overrides GimmickBehaviorBase
    virtual void vf324();  // 0085A440 slot 0x324  overrides GimmickBehaviorBase
    virtual void vf328();  // 0085A100 slot 0x328  overrides GimmickBehaviorBase
    virtual void vf32C();  // 0085A4B0 slot 0x32C  overrides GimmickBehaviorBase
    virtual void vf330();  // 0085A170 slot 0x330  overrides GimmickBehaviorBase
    // non-virtual members
    cManupilateNodeSingleDlc();  // 00AB1AC0
};
