// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "GimmickBehaviorBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cManupilatePanel : public GimmickBehaviorBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABAA10 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB62D0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005E2F70 slot 0x40  overrides Behavior
    virtual void vf44();  // 005E2FA0 slot 0x44  overrides Behavior
    virtual void vf4C();  // 005E2FC0 slot 0x4C  overrides Behavior
    virtual void vf318();  // 005E30B0 slot 0x318  overrides GimmickBehaviorBase
    virtual void vf31C();  // 005E30D0 slot 0x31C  overrides GimmickBehaviorBase
    virtual void vf320();  // 005E2FE0 slot 0x320  overrides GimmickBehaviorBase
    virtual void vf324();  // 005E3060 slot 0x324  overrides GimmickBehaviorBase
    virtual void vf328();  // 005E3080 slot 0x328  overrides GimmickBehaviorBase
    // non-virtual members
    cManupilatePanel();  // 00AB62B0
};
