// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cModelVertexFormatNV2I {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00();  // 00F907D0 slot 0x0  overrides Hw::cVertexFormat
    virtual undefined4 * vf04(byte param_2);  // 00F942E0 slot 0x4  overrides Hw::cVertexFormat
    // non-virtual members
    cModelVertexFormatNV2I();  // 00F8F940
};
