// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cModelShaderEventFixed {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8FDF0 slot 0x0  overrides Hw::cShader
    virtual void vf04();  // 00F90120 slot 0x4  overrides Hw::cShader
    // non-virtual members
    cModelShaderEventFixed();  // 00F8FDB0
    ~cModelShaderEventFixed();  // 00F8FDD0
};
