// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cMsgPrimWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CCCC60 slot 0x0  overrides Hw::cOtWork
    virtual void draw();  // 00CCCCD0 slot 0x4  overrides Hw::cOtWork
    virtual undefined4 vf08() = 0;  // 00FDB68B slot 0x8
    virtual int vf0C() = 0;  // 00FDB68B slot 0xC
    // non-virtual members
    cMsgPrimWorkBase();  // 00CCCB80
};
