// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined ** vf00();  // 00A1F620 slot 0x0
    virtual undefined4 * vf04(byte param_2);  // 00A1F630 slot 0x4
    // non-virtual members
    cObject();  // 00A36200
    void ctor_00A36330();  // 00A36330
    void ctor_00A44940();  // 00A44940
    cObject(byte param_2);  // 00FBA010
    void ctor_015EDA90();  // 015EDA90
    void ctor_015EDB30();  // 015EDB30
    void ctor_015F15D0();  // 015F15D0
    void ctor_015F5EC0();  // 015F5EC0
};
