// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Collision.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CollisionMesh : public Collision {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00D7D600 slot 0x0  overrides Collision
    virtual undefined4 * vf04(undefined4 * param_1);  // 00D7D610 slot 0x4  overrides Collision
    virtual undefined4 vf08(byte param_2);  // 00D7D670 slot 0x8  overrides Collision
    virtual void detectionForPenetration();  // 00D78DA0 slot 0x10  overrides Collision
    virtual void vf14();  // 00D776E0 slot 0x14  overrides Collision
    virtual float10 vf1C();  // 00D776B0 slot 0x1C  overrides Collision
    virtual void vf24();  // 00D776C0 slot 0x24  overrides Collision
    // non-virtual members
    CollisionMesh();  // 00D7D650
    CollisionMesh(undefined4 param_1, undefined4 param_2, undefined4 param_3);  // 00D7E080
};
