// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Collision.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CollisionImpactVolume : public Collision {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00D7D510 slot 0x0  overrides Collision
    virtual undefined4 * vf04(undefined4 * param_1);  // 00D7D520 slot 0x4  overrides Collision
    virtual undefined4 vf08(byte param_2);  // 00D7D580 slot 0x8  overrides Collision
    virtual void detectionForPenetration();  // 00D78D50 slot 0x10  overrides Collision
    virtual void vf14();  // 00D77670 slot 0x14  overrides Collision
    virtual float10 vf1C();  // 00D775F0 slot 0x1C  overrides Collision
    virtual void vf24();  // 00D7A680 slot 0x24  overrides Collision
    // non-virtual members
    CollisionImpactVolume();  // 00D7D560
    void ctor_00D7E030();  // 00D7E030
};
