// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "ContentsManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ContentsManagerImplement : public ContentsManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 008DF800 slot 0x0  overrides ContentsManager
    virtual void vf04();  // 008DF700 slot 0x4  overrides ContentsManager
    virtual void vf08(int * param_2);  // 008DF740 slot 0x8  overrides ContentsManager
    virtual void vf0C(int param_2);  // 008DF870 slot 0xC  overrides ContentsManager
    virtual undefined4 vf10();  // 008DF6D0 slot 0x10  overrides ContentsManager
};
