// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cOptionMenuGraphicParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00996A70 slot 0x0  overrides cCustomObjCtrlManager
    // non-virtual members
    cOptionMenuGraphicParts();  // 00996A20
    void ctor_009A8AA0();  // 009A8AA0
};
