// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cOptionMenuSystemParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009969D0 slot 0x0  overrides cCustomObjCtrlManager
    // non-virtual members
    cOptionMenuSystemParts();  // 00996940
    void ctor_009A8AA0();  // 009A8AA0
    void ctor_009A8B90();  // 009A8B90
};
