// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cP470 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D6D910 slot 0x0  overrides cPhaseAbstract
    virtual void vf08();  // 00D4A7C0 slot 0x8  overrides cPhaseAbstract
    virtual void vf0C();  // 00D5B340 slot 0xC  overrides cPhaseAbstract
    virtual void vf10();  // 00D5B3A0 slot 0x10  overrides cPhaseAbstract
    virtual void vf14(undefined4 param_2, byte * param_3);  // 00D6D960 slot 0x14  overrides cPhaseAbstract
    virtual void vf18();  // 00D713F0 slot 0x18  overrides cPhaseAbstract
    virtual void vf1C(undefined4 param_1, byte * param_2);  // 00D4A830 slot 0x1C  overrides cPhaseAbstract
    virtual void vf28(undefined4 param_1);  // 00D63CE0 slot 0x28  overrides cPhaseAbstract
    // non-virtual members
    cP470();  // 00D6D860
};
