// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cPa15 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D70020 slot 0x0  overrides cPhaseAbstract
    virtual void vf08();  // 00D514F0 slot 0x8  overrides cPhaseAbstract
    virtual void vf0C();  // 00D47830 slot 0xC  overrides cPhaseAbstract
    virtual void vf10();  // 00D51620 slot 0x10  overrides cPhaseAbstract
    virtual void vf14(undefined4 param_2, byte * param_3);  // 00D66830 slot 0x14  overrides cPhaseAbstract
    virtual void vf18();  // 00D47860 slot 0x18  overrides cPhaseAbstract
    virtual void vf1C(undefined4 param_1, byte * param_2);  // 00D47870 slot 0x1C  overrides cPhaseAbstract
};
