// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cPc20 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D708A0 slot 0x0  overrides cPhaseAbstract
    virtual void vf08();  // 00D4B2D0 slot 0x8  overrides cPhaseAbstract
    virtual void vf0C();  // 00D64B60 slot 0xC  overrides cPhaseAbstract
    virtual void vf10();  // 00D4B410 slot 0x10  overrides cPhaseAbstract
    virtual void vf14(undefined4 param_2, byte * param_3);  // 00D55C90 slot 0x14  overrides cPhaseAbstract
    virtual void vf18();  // 00D5D240 slot 0x18  overrides cPhaseAbstract
    virtual void vf2C();  // 00D5D2C0 slot 0x2C  overrides cPhaseAbstract
    virtual undefined1 * vf30(byte * param_1);  // 00D56380 slot 0x30  overrides cPhaseAbstract
};
