// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cPd30 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D70A20 slot 0x0  overrides cPhaseAbstract
    virtual void vf08();  // 00D4B9B0 slot 0x8  overrides cPhaseAbstract
    virtual void vf0C();  // 00D4BA20 slot 0xC  overrides cPhaseAbstract
    virtual void vf10();  // 00D56920 slot 0x10  overrides cPhaseAbstract
    virtual void vf14(undefined4 param_2, byte * param_3);  // 00D651D0 slot 0x14  overrides cPhaseAbstract
    virtual void vf18();  // 00D56980 slot 0x18  overrides cPhaseAbstract
    virtual void vf2C();  // 00D5D8D0 slot 0x2C  overrides cPhaseAbstract
    virtual undefined1 * vf30(byte * param_1);  // 00D5D880 slot 0x30  overrides cPhaseAbstract
    // non-virtual members
    cPd30();  // 00D6F9F0
};
