// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cPrologTrainEvent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D70BD0 slot 0x0  overrides cPhaseAbstract
    virtual undefined1 * vf30(byte * param_1);  // 00D557C0 slot 0x30  overrides cPhaseAbstract
    virtual undefined4 vf34(byte * param_1);  // 00D64A10 slot 0x34  overrides cPhaseAbstract
};
