// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cRayBatteryDLC : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA010 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB3BD0 slot 0x4  overrides cObj
    virtual void vf30();  // 008D4BE0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 008D56A0 slot 0x40  overrides Behavior
    virtual void vf44();  // 008D4C80 slot 0x44  overrides Behavior
    virtual void vf4C();  // 008D6CE0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 008D4C90 slot 0x50  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 008D4C60 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 008D4C40 slot 0x1BC  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 008D4C50 slot 0x1D0  overrides Behavior
    virtual undefined4 vf238();  // 00AB3BE0 slot 0x238  overrides Behavior
};
