// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cRayBattery : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7870 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAEE10 slot 0x4  overrides cObj
    virtual void vf30();  // 00B74980 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00B74ED0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B74450 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00B76490 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00B74460 slot 0x50  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 00B74430 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 00B74410 slot 0x1BC  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 00B74420 slot 0x1D0  overrides Behavior
};
