// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CRect {
    // non-virtual members
    undefined4 SetRect(int, int, int);  // 00FA4DE0
};
