// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManagerEx.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cResultDispParts : public cCustomObjCtrlManagerEx {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CF11A0 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00CF11C0 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 00D32E60 slot 0x14  overrides cCustomObjCtrlManager
};
