// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cRoomAbstract {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00() = 0;  // 00FDB68B slot 0x0
    virtual void vf04() = 0;  // 00FDB68B slot 0x4
    virtual void vf08() = 0;  // 00FDB68B slot 0x8
    virtual void vf0C() = 0;  // 00FDB68B slot 0xC
    virtual void vf10() = 0;  // 00FDB68B slot 0x10
    virtual undefined4 * vf14(byte param_2);  // 00A75FE0 slot 0x14
    virtual void vf18();  // 00A71750 slot 0x18
    virtual void vf1C();  // 00A6D630 slot 0x1C
};
