// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cScrObj : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7DC0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6920 slot 0x4  overrides cObj
    virtual undefined4 vf08();  // 00A00510 slot 0x8  overrides cObj
    virtual void vf50();  // 009F8720 slot 0x50  overrides Behavior
    virtual void vf60();  // 009FD120 slot 0x60  overrides Behavior
    // non-virtual members
    cScrObj();  // 00AA6900
};
