// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cSlashPointDispParts : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CF0B00 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00D32130 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 00CF0B20 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cSlashPointDispParts();  // 00D320B0
};
