// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cStingerMissileSite {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CD87C0 slot 0x0
    // non-virtual members
    cStingerMissileSite();  // 00CBF740
    void ctor_00CBF7B0();  // 00CBF7B0
};
