// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cTexRenderAddBlend : public cEspShaderBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8E830 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F6B850 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    cTexRenderAddBlend();  // 00F84E50
};
