// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cTutorialDisp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CD9010 slot 0x0
    // non-virtual members
    cTutorialDisp();  // 00CC0970
    void ctor_00CC09E0();  // 00CC09E0
};
