// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUICtrl {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CF6AF0 slot 0x0
    virtual undefined vf04();  // 00CF6B20 slot 0x4
    // non-virtual members
    cUICtrl();  // 00CC75D0
    static int HIT(undefined4 param_2, undefined4 param_3, undefined4 param_4);  // 00D120F0
    static undefined HIT_2();  // 00D20260
};
