// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUIDrawBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CA8890 slot 0x0
    virtual void vf04();  // 00CA8880 slot 0x4
    virtual undefined4 vf08() = 0;  // 00FDB68B slot 0x8
    virtual void vf0C();  // 00CB3920 slot 0xC
    virtual undefined vf10();  // 00CB3910 slot 0x10
    virtual void vf14(int * param_2, int param_3) = 0;  // 00FDB68B slot 0x14
    virtual void vf18(int param_2, undefined4 param_3, int param_4);  // 00CCEA20 slot 0x18
    // non-virtual members
    cUIDrawBase();  // 00CCEE50
    void ctor_00CCF710();  // 00CCF710
    void ctor_00CE5320();  // 00CE5320
};
