// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cUIDrawBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUIDrawHit : public cUIDrawBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CE78A0 slot 0x0  overrides cUIDrawBase
    virtual void vf04();  // 00CB3EE0 slot 0x4  overrides cUIDrawBase
    virtual undefined4 vf08();  // 00CB3ED0 slot 0x8  overrides cUIDrawBase
    virtual void vf14(int * param_2, int param_3);  // 00CB3F40 slot 0x14  overrides cUIDrawBase
    // non-virtual members
    cUIDrawHit(undefined4 param_2, int param_3);  // 00D0CAB0
};
