// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cUIDrawBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUIDrawString : public cUIDrawBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CCF1F0 slot 0x0  overrides cUIDrawBase
    virtual undefined4 vf08();  // 00CCF1E0 slot 0x8  overrides cUIDrawBase
    virtual void vf0C();  // 00CCF600 slot 0xC  overrides cUIDrawBase
    virtual undefined vf10();  // 00CCF520 slot 0x10  overrides cUIDrawBase
    virtual void vf14(int * param_2, int param_3);  // 00CE6B40 slot 0x14  overrides cUIDrawBase
    virtual void vf18(int param_2, undefined4 param_3, int param_4);  // 00CB3D30 slot 0x18  overrides cUIDrawBase
    // non-virtual members
    cUIDrawString();  // 00CCF0D0
};
