// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cUIPrimWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUIPrimWorkStrip : public cUIPrimWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CCC490 slot 0x0  overrides Hw::cOtWork
    virtual undefined4 vf08();  // 00CCC440 slot 0x8  overrides cUIPrimWorkBase
    virtual int vf0C();  // 00CCC450 slot 0xC  overrides cUIPrimWorkBase
    // non-virtual members
    cUIPrimWorkStrip();  // 00CCC420
    cUIPrimWorkStrip(int * param_2, int param_3);  // 00CE8060
    void ctor_00CE87E0();  // 00CE87E0
    void ctor_00CE8F90();  // 00CE8F90
    cUIPrimWorkStrip(int * param_2, int param_3, int param_4);  // 00CE97D0
};
