// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cUIPrimWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUIPrimWorkFan : public cUIPrimWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CCC120 slot 0x0  overrides Hw::cOtWork
    virtual undefined4 vf08();  // 00CCC0D0 slot 0x8  overrides cUIPrimWorkBase
    virtual int vf0C();  // 00CCC0E0 slot 0xC  overrides cUIPrimWorkBase
    // non-virtual members
    cUIPrimWorkFan();  // 00CCC0B0
};
