// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUIWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00CCA770 slot 0x0
    virtual void vf04() = 0;  // 00FDB68B slot 0x4
    virtual void vf08(undefined4 param_2) = 0;  // 00FDB68B slot 0x8
    virtual void vf0C(undefined4 param_2) = 0;  // 00FDB68B slot 0xC
    virtual void vf10();  // 00CAE150 slot 0x10
    // non-virtual members
    cUIWork();  // 00CE3150
    void ctor_00CEAB60();  // 00CEAB60
    void ctor_00CEABF0();  // 00CEABF0
    void ctor_00CEB560();  // 00CEB560
    void ctor_00CEB790();  // 00CEB790
    void ctor_00CEDE40();  // 00CEDE40
    void ctor_00CF34E0();  // 00CF34E0
    void ctor_00CF3750();  // 00CF3750
    void ctor_00CF6560();  // 00CF6560
    void ctor_00CF8070();  // 00CF8070
    void ctor_00CF9A50();  // 00CF9A50
    void ctor_00D0B620();  // 00D0B620
    void ctor_00D0B810();  // 00D0B810
    void ctor_00D0B8B0();  // 00D0B8B0
    void ctor_00D0B950();  // 00D0B950
    void ctor_00D0B9F0();  // 00D0B9F0
    void ctor_00D0BA90();  // 00D0BA90
    void ctor_00D0BB30();  // 00D0BB30
    void ctor_00D0BBD0();  // 00D0BBD0
    void ctor_00D0BC70();  // 00D0BC70
    void ctor_00D0BD10();  // 00D0BD10
    void ctor_00D0BDB0();  // 00D0BDB0
    void ctor_00D0BE50();  // 00D0BE50
    void ctor_00D0BEF0();  // 00D0BEF0
    void ctor_00D0BF90();  // 00D0BF90
    void ctor_00D0C030();  // 00D0C030
    void ctor_00D0C0D0();  // 00D0C0D0
    void ctor_00D0C170();  // 00D0C170
    void ctor_00D0C210();  // 00D0C210
    void ctor_00D0C2B0();  // 00D0C2B0
    void ctor_00D0C350();  // 00D0C350
    void ctor_00D0C3F0();  // 00D0C3F0
    void ctor_00D0C490();  // 00D0C490
    void ctor_00D0C530();  // 00D0C530
    void ctor_00D0C5D0();  // 00D0C5D0
    void ctor_00D0C670();  // 00D0C670
    void ctor_00D0C710();  // 00D0C710
    void ctor_00D0C7B0();  // 00D0C7B0
    void ctor_00D0C850();  // 00D0C850
    void ctor_00D0C8F0();  // 00D0C8F0
    void ctor_00D0C990();  // 00D0C990
    void ctor_00D0CA30();  // 00D0CA30
    void ctor_00D0DDF0();  // 00D0DDF0
    void ctor_00D0DE90();  // 00D0DE90
    void ctor_00D0DF30();  // 00D0DF30
    void ctor_00D0DFD0();  // 00D0DFD0
    void ctor_00D0E070();  // 00D0E070
    void ctor_00D0E110();  // 00D0E110
    void ctor_00D0E1B0();  // 00D0E1B0
    void ctor_00D0E250();  // 00D0E250
    void ctor_00D0E2F0();  // 00D0E2F0
    void ctor_00D0E390();  // 00D0E390
    void ctor_00D0E430();  // 00D0E430
    void ctor_00D0E4D0();  // 00D0E4D0
    void ctor_00D0E570();  // 00D0E570
    void ctor_00D0E610();  // 00D0E610
    void ctor_00D0E6B0();  // 00D0E6B0
    void ctor_00D0E750();  // 00D0E750
    void ctor_00D0E7F0();  // 00D0E7F0
    void ctor_00D0E890();  // 00D0E890
    void ctor_00D0E930();  // 00D0E930
    void ctor_00D0E9D0();  // 00D0E9D0
    void ctor_00D0EA70();  // 00D0EA70
    void ctor_00D0EB10();  // 00D0EB10
    void ctor_00D0EBB0();  // 00D0EBB0
    void ctor_00D0EC50();  // 00D0EC50
    void ctor_00D0ECF0();  // 00D0ECF0
    void ctor_00D0ED90();  // 00D0ED90
    void ctor_00D0EE30();  // 00D0EE30
    void ctor_00D0EED0();  // 00D0EED0
    void ctor_00D0EF70();  // 00D0EF70
    void ctor_00D0F010();  // 00D0F010
    void ctor_00D0F0B0();  // 00D0F0B0
    void ctor_00D0F150();  // 00D0F150
    void ctor_00D0F1F0();  // 00D0F1F0
    void ctor_00D0F290();  // 00D0F290
    void ctor_00D0F330();  // 00D0F330
    void ctor_00D0F3D0();  // 00D0F3D0
    void ctor_00D0F470();  // 00D0F470
    void ctor_00D0F510();  // 00D0F510
    void ctor_00D0F5B0();  // 00D0F5B0
    void ctor_00D0F650();  // 00D0F650
    void ctor_00D0F6F0();  // 00D0F6F0
    void ctor_00D0F790();  // 00D0F790
    void ctor_00D0F830();  // 00D0F830
    void ctor_00D0F8D0();  // 00D0F8D0
    void ctor_00D0F970();  // 00D0F970
    void ctor_00D0FA10();  // 00D0FA10
    void ctor_00D0FAB0();  // 00D0FAB0
    void ctor_00D0FB50();  // 00D0FB50
    void ctor_00D0FBF0();  // 00D0FBF0
    void ctor_00D0FC90();  // 00D0FC90
    void ctor_00D0FD30();  // 00D0FD30
    void ctor_00D0FDD0();  // 00D0FDD0
    void ctor_00D0FE70();  // 00D0FE70
    void ctor_00D0FF10();  // 00D0FF10
    void ctor_00D0FFB0();  // 00D0FFB0
    void ctor_00D10050();  // 00D10050
    void ctor_00D100F0();  // 00D100F0
    void ctor_00D10190();  // 00D10190
    void ctor_00D10230();  // 00D10230
    void ctor_00D102D0();  // 00D102D0
    void ctor_00D10370();  // 00D10370
    void ctor_00D10410();  // 00D10410
    void ctor_00D104B0();  // 00D104B0
    void ctor_00D10550();  // 00D10550
    void ctor_00D105F0();  // 00D105F0
    void ctor_00D10690();  // 00D10690
    void ctor_00D10730();  // 00D10730
    void ctor_00D107D0();  // 00D107D0
    void ctor_00D10870();  // 00D10870
    void ctor_00D10910();  // 00D10910
    void ctor_00D109B0();  // 00D109B0
    void ctor_00D10A50();  // 00D10A50
    void ctor_00D10AF0();  // 00D10AF0
    void ctor_00D10B90();  // 00D10B90
    void ctor_00D10C30();  // 00D10C30
    void ctor_00D10CD0();  // 00D10CD0
    void ctor_00D10D70();  // 00D10D70
    void ctor_00D10E10();  // 00D10E10
    void ctor_00D10EB0();  // 00D10EB0
    void ctor_00D10F50();  // 00D10F50
    void ctor_00D11000();  // 00D11000
    void ctor_00D110A0();  // 00D110A0
    void ctor_00D11140();  // 00D11140
    void ctor_00D111E0();  // 00D111E0
    void ctor_00D11280();  // 00D11280
    void ctor_00D11320();  // 00D11320
    void ctor_00D113C0();  // 00D113C0
    void ctor_00D11460();  // 00D11460
    void ctor_00D11500();  // 00D11500
    void ctor_00D115A0();  // 00D115A0
    void ctor_00D11640();  // 00D11640
    void ctor_00D116E0();  // 00D116E0
    void ctor_00D11780();  // 00D11780
    void ctor_00D11820();  // 00D11820
    void ctor_00D118C0();  // 00D118C0
    void ctor_00D11960();  // 00D11960
};
