// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cUpdatePop : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009A1FD0 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf08();  // 009A2000 slot 0x8  overrides cCustomObjCtrlManager
    virtual void vf0C();  // 009907F0 slot 0xC  overrides cCustomObjCtrlManager
    virtual void create();  // 009A2050 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    cUpdatePop();  // 00990760
    void ctor_00990780();  // 00990780
};
