// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct cVertexFormatF16_4_4_R4 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00();  // 00EC4930 slot 0x0  overrides Hw::cVertexFormat
    virtual undefined4 * vf04(byte param_2);  // 00ECC440 slot 0x4  overrides Hw::cVertexFormat
    // non-virtual members
    cVertexFormatF16_4_4_R4();  // 00ECC410
};
