// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct CWiauPropertyList {
    // non-virtual members
    undefined4 LookupPropId();  // 010F3A50
    undefined4 LookupPropId_011773D0();  // 011773D0
};
