// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "DatsuSetTable.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct DatsuSetTableImplement : public DatsuSetTable {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int vf00(int param_2);  // 0093D500 slot 0x0  overrides DatsuSetTable
    virtual int vf04(int param_2);  // 0093D550 slot 0x4  overrides DatsuSetTable
    virtual int vf08(int param_2);  // 0093D5A0 slot 0x8  overrides DatsuSetTable
    virtual int vf0C(int param_2);  // 0093D5F0 slot 0xC  overrides DatsuSetTable
    virtual int vf10(int param_2);  // 0093D640 slot 0x10  overrides DatsuSetTable
    virtual int vf14(int param_2);  // 0093D690 slot 0x14  overrides DatsuSetTable
    virtual int vf18(int param_2);  // 0093D6E0 slot 0x18  overrides DatsuSetTable
    virtual void vf1C();  // 0093BED0 slot 0x1C  overrides DatsuSetTable
    virtual undefined4 * vf20(byte param_2);  // 0093D480 slot 0x20  overrides DatsuSetTable
    // non-virtual members
    DatsuSetTableImplement();  // 0093D3E0
};
