// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct DatsuSetTable {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int vf00(int param_2) = 0;  // 00FDB68B slot 0x0
    virtual int vf04(int param_2) = 0;  // 00FDB68B slot 0x4
    virtual int vf08(int param_2) = 0;  // 00FDB68B slot 0x8
    virtual int vf0C(int param_2) = 0;  // 00FDB68B slot 0xC
    virtual int vf10(int param_2) = 0;  // 00FDB68B slot 0x10
    virtual int vf14(int param_2) = 0;  // 00FDB68B slot 0x14
    virtual int vf18(int param_2) = 0;  // 00FDB68B slot 0x18
    virtual void vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual undefined4 * vf20(byte param_2);  // 0093BCB0 slot 0x20
};
