// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct DatsuSetTableManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00() = 0;  // 00FDB68B slot 0x0
    virtual int vf04(int param_2, undefined4 param_3) = 0;  // 00FDB68B slot 0x4
    virtual void vf08(int param_2) = 0;  // 00FDB68B slot 0x8
    virtual void vf0C();  // 0093C000 slot 0xC
    virtual void vf10();  // 0093C010 slot 0x10
    virtual undefined4 * vf14(byte param_2);  // 0093BD60 slot 0x14
    // non-virtual members
    DatsuSetTableManager();  // 0093D0B0
};
