// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "DebrisManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct DebrisManagerImplement : public DebrisManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00C62B90 slot 0x0  overrides DebrisManager
    virtual void vf04();  // 00C1C600 slot 0x4  overrides DebrisManager
    virtual void vf08(int param_2);  // 00C50F40 slot 0x8  overrides DebrisManager
    virtual int vf0C();  // 00C62AD0 slot 0xC  overrides DebrisManager
    virtual undefined4 vf10();  // 00C62AF0 slot 0x10  overrides DebrisManager
    virtual void vf14();  // 00C2DC20 slot 0x14  overrides DebrisManager
    virtual void vf18();  // 00C448C0 slot 0x18  overrides DebrisManager
    virtual void vf1C();  // 00C448F0 slot 0x1C  overrides DebrisManager
    virtual undefined4 vf20();  // 00C2DC60 slot 0x20  overrides DebrisManager
    virtual void vf24();  // 00C50FB0 slot 0x24  overrides DebrisManager
    virtual void vf28();  // 00C510B0 slot 0x28  overrides DebrisManager
    // non-virtual members
    DebrisManagerImplement(undefined4 param_1);  // 00C64820
    void ctor_00C64880(undefined4 param_1);  // 00C64880
};
