// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct DlcCatBehavior : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9BE0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB19F0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00603780 slot 0x40  overrides Behavior
    virtual void vf44();  // 00603AD0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00603BA0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00603980 slot 0x4C  overrides Behavior
    virtual undefined4 vf94();  // 00603750 slot 0x94  overrides Behavior
};
