// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBa.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct DlcMoveBlock : public BehaviorBa {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9BB0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1990 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00603BE0 slot 0x40  overrides Behavior
    virtual void vf48();  // 00603CB0 slot 0x48  overrides Behavior
    // non-virtual members
    DlcMoveBlock();  // 00AB1970
};
