// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBm.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct E3_EnemyBoardBase : public BehaviorBm {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9470 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0B80 slot 0x4  overrides cObj
    virtual void vf2C();  // 0040BA90 slot 0x2C  overrides cObj
    virtual void vf30();  // 0040B890 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 0040B6F0 slot 0x40  overrides Behavior
    virtual void vf44();  // 0040AE60 slot 0x44  overrides Behavior
    virtual void vf4C();  // 0040AE80 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0040AEA0 slot 0x50  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 0040AF60 slot 0x1B8  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 0040AEE0 slot 0x1D0  overrides Behavior
    virtual void vf2F4();  // 0040BF80 slot 0x2F4  overrides Behavior
    virtual void vf318();  // 0040BCD0 slot 0x318
    // non-virtual members
    E3_EnemyBoardBase();  // 00AB0B60
};
