// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBa.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct E3_EnemyBoardGroundCircle : public BehaviorBa {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB93E0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB0A90 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0040B020 slot 0x40  overrides Behavior
    virtual void vf4C();  // 0040C110 slot 0x4C  overrides Behavior
    // non-virtual members
    E3_EnemyBoardGroundCircle();  // 00AB0A70
};
