// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EffectShaderWaterDraw : public cEspShaderBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8E7A0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F6B590 slot 0x8  overrides cEspShaderBase
    virtual void vf0C();  // 00F5D8E0 slot 0xC  overrides cEspShaderBase
    // non-virtual members
    EffectShaderWaterDraw();  // 00F84AD0
};
