// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0030Wire : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7970 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAEFD0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00B62BA0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B62C40 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00B70D90 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00B62C50 slot 0x50  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00B682C0 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00B62C70 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00B62CB0 slot 0x150  overrides Behavior
    virtual undefined4 vf1A0();  // 00B683D0 slot 0x1A0  overrides Behavior
    // non-virtual members
    Em0030Wire();  // 00AAEFA0
};
