// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0030 : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6CC0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAC690 slot 0x4  overrides cObj
    virtual void vf1C();  // 00B628B0 slot 0x1C  overrides cObj
    virtual void vf20();  // 00B62870 slot 0x20  overrides cObj
    virtual undefined4 startup();  // 00B722B0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B69DF0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00B6FC90 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00B741F0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00B70DD0 slot 0x50  overrides Behavior
    virtual void vf54();  // 00B60B70 slot 0x54  overrides Behavior
    virtual void vf6C();  // 00B61760 slot 0x6C  overrides Behavior
    virtual void vf70();  // 00B617C0 slot 0x70  overrides Behavior
    virtual void vfC8(undefined4 param_2);  // 00B60B80 slot 0xC8  overrides Behavior
    virtual void vfFC();  // 00B60AB0 slot 0xFC  overrides Behavior
    virtual void vf100();  // 00B60B10 slot 0x100  overrides Behavior
    virtual void vf104();  // 00B69B40 slot 0x104  overrides Behavior
    virtual void vf108();  // 00B69DC0 slot 0x108  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 00B62900 slot 0x110  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00B63500 slot 0x130  overrides Behavior
    virtual undefined4 vf13C();  // 00B67940 slot 0x13C  overrides Behavior
    virtual float10 vf140();  // 00AAC6E0 slot 0x140  overrides Behavior
    virtual float10 vf144();  // 00AAC6F0 slot 0x144  overrides Behavior
    virtual undefined4 vf14C();  // 00B64D60 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00B6DE50 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 00B62610 slot 0x158  overrides Behavior
    virtual void vf15C();  // 00B62680 slot 0x15C  overrides Behavior
    virtual undefined4 vf17C();  // 00AAC6A0 slot 0x17C  overrides Behavior
    virtual undefined4 vf180();  // 00AAC6B0 slot 0x180  overrides Behavior
    virtual undefined4 vf184();  // 00B61810 slot 0x184  overrides Behavior
    virtual void vf188();  // 00B6BB00 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00B6B790 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00B6B850 slot 0x1A4  overrides Behavior
    virtual undefined4 vf1B0();  // 00B63440 slot 0x1B0  overrides Behavior
    virtual void vf1C0();  // 00B62D20 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AAC6D0 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 00B61730 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AAC6C0 slot 0x20C  overrides Behavior
    virtual void vf258();  // 00B69290 slot 0x258  overrides Behavior
    virtual void vf260();  // 00B69340 slot 0x260  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 00B69F50 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 00B675F0 slot 0x268  overrides Behavior
    virtual void vf294();  // 00B62D30 slot 0x294  overrides Behavior
    virtual void vf298();  // 00B62D40 slot 0x298  overrides Behavior
    virtual void vf29C();  // 00B62D50 slot 0x29C  overrides Behavior
    virtual void vf2A0();  // 00B698E0 slot 0x2A0  overrides Behavior
    virtual void vf2A4();  // 00B69A70 slot 0x2A4  overrides Behavior
    virtual void vf2A8();  // 00B62D60 slot 0x2A8  overrides Behavior
    virtual void vf2AC();  // 00B62D70 slot 0x2AC  overrides Behavior
    virtual void vf2B0();  // 00B62D80 slot 0x2B0  overrides Behavior
    virtual void vf2B4();  // 00B62D90 slot 0x2B4  overrides Behavior
    virtual void vf2B8();  // 00B62DA0 slot 0x2B8  overrides Behavior
    virtual void vf2BC();  // 00B62DB0 slot 0x2BC  overrides Behavior
    virtual void vf2C0();  // 00B62DC0 slot 0x2C0  overrides Behavior
    virtual void vf2C4();  // 00B62DD0 slot 0x2C4  overrides Behavior
    virtual void vf2C8();  // 00B62DE0 slot 0x2C8  overrides Behavior
    virtual void vf2CC();  // 00B62DF0 slot 0x2CC  overrides Behavior
    virtual void vf2D0();  // 00B62E00 slot 0x2D0  overrides Behavior
    virtual undefined4 vf2D4();  // 00B62E10 slot 0x2D4  overrides Behavior
    virtual void vf2F8();  // 00B634D0 slot 0x2F8  overrides Behavior
    virtual undefined4 vf32C();  // 00B6FDE0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 00B693B0 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 00B69220 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 00B688A0 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 00B66D00 slot 0x34C  overrides BehaviorEmBase
    virtual void vf350();  // 00B66D30 slot 0x350  overrides BehaviorEmBase
    virtual void vf360();  // 00B67570 slot 0x360  overrides BehaviorEmBase
    virtual undefined4 vf368();  // 00B67800 slot 0x368  overrides BehaviorEmBase
    // non-virtual members
    Em0030();  // 00AAC5A0
};
