// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0091 : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9220 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB06F0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0049E6F0 slot 0x40  overrides Behavior
    virtual void vf44();  // 0049DA20 slot 0x44  overrides Behavior
    virtual void vf48();  // 0049E690 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0049F1D0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0049E390 slot 0x50  overrides Behavior
};
