// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em002f : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6A70 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAC2D0 slot 0x4  overrides cObj
    virtual void vf1C();  // 0043AF10 slot 0x1C  overrides cObj
    virtual void vf20();  // 0043AF20 slot 0x20  overrides cObj
    virtual undefined4 startup();  // 0043B810 slot 0x40  overrides Behavior
    virtual void vf44();  // 0043AFF0 slot 0x44  overrides Behavior
    virtual void vf48();  // 0043AAB0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0043BD40 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0043AAD0 slot 0x50  overrides Behavior
    virtual void vf54();  // 0043AB00 slot 0x54  overrides Behavior
    virtual void vf104();  // 0043BCD0 slot 0x104  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 0043AF70 slot 0x264  overrides Behavior
    // non-virtual members
    Em002f();  // 00AAC280
};
