// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBgBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0010DebrisTest : public BehaviorBgBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 005E4E40 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 005E41A0 slot 0x4  overrides cObj
    virtual void vf34();  // 005E6290 slot 0x34  overrides cObj
    virtual undefined4 startup();  // 005E41B0 slot 0x40  overrides Behavior
    virtual void vf44();  // 005E41E0 slot 0x44  overrides Behavior
    virtual void vf48();  // 005E6080 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005E4E90 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005E4EE0 slot 0x50  overrides Behavior
    // non-virtual members
    Em0010DebrisTest();  // 005E4160
    void ctor_005E4DE0();  // 005E4DE0
    static void vf54();  // 00AA1660
};
