// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0045 : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6E00 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6300 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0043EAE0 slot 0x40  overrides Behavior
    virtual void vf44();  // 0043EC60 slot 0x44  overrides Behavior
    virtual void vf48();  // 0043EA40 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0043F320 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0043EA50 slot 0x50  overrides Behavior
    virtual void vf54();  // 0043EA80 slot 0x54  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 0043EA90 slot 0x1D0  overrides Behavior
    // non-virtual members
    Em0045();  // 00AA62C0
};
