// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0042 : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6D70 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6280 slot 0x4  overrides cObj
    virtual void vf30();  // 0043DC50 slot 0x30  overrides cObj
    virtual void vf34();  // 0043DC60 slot 0x34  overrides cObj
    virtual undefined4 startup();  // 0043DD00 slot 0x40  overrides Behavior
    virtual void vf44();  // 0043DCB0 slot 0x44  overrides Behavior
    virtual void vf48();  // 0043DCE0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0043DCF0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0043DDE0 slot 0x50  overrides Behavior
    virtual void vf54();  // 0043DE50 slot 0x54  overrides Behavior
    virtual void vf114();  // 0043DC70 slot 0x114  overrides Behavior
    // non-virtual members
    Em0042();  // 00AA6240
};
