// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0080 : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6EB0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AACEB0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0048F220 slot 0x40  overrides Behavior
    virtual void vf44();  // 00488740 slot 0x44  overrides Behavior
    virtual void vf48();  // 00490EB0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0049B1B0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 004800D0 slot 0x50  overrides Behavior
    virtual void vf54();  // 0047C810 slot 0x54  overrides Behavior
    virtual void vf6C();  // 0047E390 slot 0x6C  overrides Behavior
    virtual void vf70();  // 0047E3A0 slot 0x70  overrides Behavior
    virtual void vfFC();  // 0047EAF0 slot 0xFC  overrides Behavior
    virtual void vf100();  // 0047EB30 slot 0x100  overrides Behavior
    virtual void vf104();  // 0047EB60 slot 0x104  overrides Behavior
    virtual void vf108();  // 0047EB70 slot 0x108  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 0047EB80 slot 0x110  overrides Behavior
    virtual bool vf118(int param_2);  // 0047C700 slot 0x118  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 0047FB70 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00485760 slot 0x14C  overrides Behavior
    virtual void vf150();  // 004857C0 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 0047F360 slot 0x158  overrides Behavior
    virtual undefined4 vf17C();  // 00AACEC0 slot 0x17C  overrides Behavior
    virtual undefined4 vf180();  // 00AACED0 slot 0x180  overrides Behavior
    virtual undefined4 vf184();  // 0047F370 slot 0x184  overrides Behavior
    virtual void vf188();  // 0047F380 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 0048BEB0 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0047E330 slot 0x1A4  overrides Behavior
    virtual void vf1C0();  // 00486CD0 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AACEF0 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 0047E360 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AACEE0 slot 0x20C  overrides Behavior
    virtual void vf258();  // 0047F5B0 slot 0x258  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 0047FF60 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 004801E0 slot 0x268  overrides Behavior
    virtual void vf27C(undefined4 * param_2);  // 00AACF00 slot 0x27C  overrides Behavior
    virtual undefined4 vf280();  // 00484430 slot 0x280  overrides Behavior
    virtual undefined4 vf284();  // 0048C0F0 slot 0x284  overrides Behavior
    virtual undefined4 vf288();  // 0047E790 slot 0x288  overrides Behavior
    virtual void vf300();  // 0047F930 slot 0x300  overrides BehaviorAppBase
    virtual void vf304();  // 0047C760 slot 0x304  overrides BehaviorAppBase
    virtual undefined4 vf32C();  // 0048ECD0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 004867F0 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 00486790 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 00486300 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 0048BF70 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 00484100 slot 0x360  overrides BehaviorEmBase
    virtual undefined4 vf368();  // 004851D0 slot 0x368  overrides BehaviorEmBase
    // non-virtual members
    Em0080();  // 00AACCB0
};
