// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0010RPGBullet : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7D10 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA68F0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00B2DFE0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B2E040 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00B33310 slot 0x4C  overrides Behavior
    // non-virtual members
    Em0010RPGBullet();  // 00AA68D0
};
