// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0100 : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB71B0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAD770 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 004AF860 slot 0x40  overrides Behavior
    virtual void vf44();  // 004A1D50 slot 0x44  overrides Behavior
    virtual void vf48();  // 004A6AC0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 004B4AA0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 004A0100 slot 0x50  overrides Behavior
    virtual void vf54();  // 004A0140 slot 0x54  overrides Behavior
    virtual void vf6C();  // 004A0C30 slot 0x6C  overrides Behavior
    virtual void vf70();  // 004A0C40 slot 0x70  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 004A0C70 slot 0x110  overrides Behavior
    virtual bool vf118(int param_2);  // 0049FEB0 slot 0x118  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 004A1BD0 slot 0x130  overrides Behavior
    virtual undefined4 vf13C();  // 004A59F0 slot 0x13C  overrides Behavior
    virtual float10 vf140();  // 00AAD7A0 slot 0x140  overrides Behavior
    virtual float10 vf144();  // 00AAD7B0 slot 0x144  overrides Behavior
    virtual undefined4 vf14C();  // 004A57D0 slot 0x14C  overrides Behavior
    virtual void vf150();  // 004AB5E0 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 004A5820 slot 0x158  overrides Behavior
    virtual undefined4 vf184();  // 0049FF10 slot 0x184  overrides Behavior
    virtual void vf188();  // 0049FF20 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 004AB250 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 004AB310 slot 0x1A4  overrides Behavior
    virtual void vf1C0();  // 004A0DB0 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AAD790 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 004A0C00 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AAD780 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 004A67F0 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 004A2AE0 slot 0x268  overrides Behavior
    virtual void vf300();  // 004A1BB0 slot 0x300  overrides BehaviorAppBase
    virtual void vf304();  // 0049FF00 slot 0x304  overrides BehaviorAppBase
    virtual undefined4 vf32C();  // 004B3470 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 004B1B00 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 004A42C0 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 004A3690 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 004A2C50 slot 0x34C  overrides BehaviorEmBase
    virtual undefined4 vf368();  // 004A0CB0 slot 0x368  overrides BehaviorEmBase
    // non-virtual members
    Em0100();  // 00AAD5F0
};
