// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0120 : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB73A0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AADCE0 slot 0x4  overrides cObj
    virtual void vf30();  // 004E3880 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 004E7F70 slot 0x40  overrides Behavior
    virtual void vf44();  // 004DB2A0 slot 0x44  overrides Behavior
    virtual void vf48();  // 004E38F0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 004EBED0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 004E3960 slot 0x50  overrides Behavior
    virtual void vf54();  // 004DB420 slot 0x54  overrides Behavior
    virtual void vf6C();  // 004DD990 slot 0x6C  overrides Behavior
    virtual void vf70();  // 004DD9A0 slot 0x70  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 004E15B0 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 004DB240 slot 0x14C  overrides Behavior
    virtual void vf150();  // 004DDD30 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 004DB250 slot 0x158  overrides Behavior
    virtual undefined4 vf184();  // 004DB260 slot 0x184  overrides Behavior
    virtual void vf188();  // 004DB270 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 004E7440 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 004DD6C0 slot 0x1A4  overrides Behavior
    virtual void vf1BC(int * param_2);  // 004E35C0 slot 0x1BC  overrides Behavior
    virtual void vf1C0();  // 004DDC80 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AADD00 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 004DD960 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AADCF0 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 004E7500 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 004E28E0 slot 0x268  overrides Behavior
    virtual undefined4 vf32C();  // 004E9310 slot 0x32C  overrides BehaviorEmBase
    virtual void vf338();  // 004E3830 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 004E3070 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 004E2750 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 004E28B0 slot 0x360  overrides BehaviorEmBase
    // non-virtual members
    Em0120();  // 00AADBB0
};
