// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0190Debris : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8530 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6C00 slot 0x4  overrides cObj
    virtual void vf30();  // 004FBAA0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00515AA0 slot 0x40  overrides Behavior
    virtual void vf44();  // 005009E0 slot 0x44  overrides Behavior
    virtual void vf4C();  // 0050DB60 slot 0x4C  overrides Behavior
    virtual void vf54();  // 00512B40 slot 0x54  overrides Behavior
    virtual void vf114();  // 004FB9D0 slot 0x114  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 004FBA40 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 00500C70 slot 0x1BC  overrides Behavior
    // non-virtual members
    Em0190Debris();  // 00AA6BE0
};
