// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorWeapon.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0110WeaponBase : public BehaviorWeapon {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AA93B0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA9340 slot 0x4  overrides cObj
    // non-virtual members
    Em0110WeaponBase();  // 00AA92F0
};
