// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em014a : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6920 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AABEE0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 004F1A90 slot 0x40  overrides Behavior
    virtual void vf44();  // 004F1D10 slot 0x44  overrides Behavior
    virtual void vf48();  // 004F1390 slot 0x48  overrides Behavior
    virtual void vf4C();  // 004F2080 slot 0x4C  overrides Behavior
    virtual void vf50();  // 004F17F0 slot 0x50  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 004F1510 slot 0x110  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 004F1E40 slot 0x19C  overrides Behavior
    virtual undefined4 vf1A0();  // 004F14B0 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 004F14C0 slot 0x1A4  overrides Behavior
    virtual void vf1E8();  // 00AABF00 slot 0x1E8  overrides Behavior
    virtual void vf1EC();  // 00AABF30 slot 0x1EC  overrides Behavior
    virtual float10 vf20C();  // 00AABEF0 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 004F1540 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 004F15B0 slot 0x268  overrides Behavior
    virtual undefined4 vf32C();  // 004F1F00 slot 0x32C  overrides BehaviorEmBase
    virtual void vf34C();  // 004F14E0 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 004F18F0 slot 0x360  overrides BehaviorEmBase
    // non-virtual members
    Em014a();  // 00AABE60
};
