// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorDebrisBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0110_Debris : public BehaviorDebrisBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8920 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAFD40 slot 0x4  overrides cObj
    virtual void vf30();  // 004B77E0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 004D8DD0 slot 0x40  overrides Behavior
    virtual void vf44();  // 004B7570 slot 0x44  overrides Behavior
    virtual void vf48();  // 004B75B0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 004B75C0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 004B7750 slot 0x50  overrides Behavior
    virtual void vf54();  // 004B7770 slot 0x54  overrides Behavior
    virtual void vf114();  // 004B77A0 slot 0x114  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 004B77C0 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 004B77F0 slot 0x1BC  overrides Behavior
    // non-virtual members
    Em0110_Debris();  // 00AAFD20
};
