// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorPartsModel.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em01a0Parts : public BehaviorPartsModel {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AC1050 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AC0FD0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005331C0 slot 0x40  overrides Behavior
    virtual void vf44();  // 005197B0 slot 0x44  overrides Behavior
    virtual void vf4C();  // 0053EC10 slot 0x4C  overrides Behavior
    virtual bool vf118(int param_2);  // 005196F0 slot 0x118  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 00519770 slot 0x1B8  overrides Behavior
    virtual void vf258();  // 00519790 slot 0x258  overrides Behavior
    virtual void vf300();  // 0051CFF0 slot 0x300  overrides BehaviorAppBase
    virtual void vf304();  // 00519750 slot 0x304  overrides BehaviorAppBase
    virtual void vf32C();  // 0053A710 slot 0x32C  overrides BehaviorPartsModel
};
