// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0200 : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB74E0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAE1A0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00AF6E90 slot 0x40  overrides Behavior
    virtual void vf44();  // 00AEAE60 slot 0x44  overrides Behavior
    virtual void vf48();  // 00AEAFE0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00B01870 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00AFCFB0 slot 0x50  overrides Behavior
    virtual void vf54();  // 00AE8DB0 slot 0x54  overrides Behavior
    virtual void vf6C();  // 00AE8E00 slot 0x6C  overrides Behavior
    virtual void vf70();  // 00AE8E80 slot 0x70  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00AEBA00 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00AE8ED0 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00AE8F30 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 00AE9030 slot 0x158  overrides Behavior
    virtual undefined4 vf17C();  // 00AAE1C0 slot 0x17C  overrides Behavior
    virtual undefined4 vf184();  // 00AE9080 slot 0x184  overrides Behavior
    virtual void vf188();  // 00AE90B0 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00AF6B00 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00AE9670 slot 0x1A4  overrides Behavior
    virtual undefined4 vf1DC();  // 00AAE1D0 slot 0x1DC  overrides Behavior
    virtual float10 vf20C();  // 00AAE1B0 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 00AE8D70 slot 0x264  overrides Behavior
    virtual undefined4 vf32C();  // 00AFC7E0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf358(undefined4 param_2, int param_3);  // 00AFAF20 slot 0x358  overrides BehaviorEmBase
    // non-virtual members
    Em0200();  // 00AADFD0
};
