// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em020a : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7570 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAE620 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0054D190 slot 0x40  overrides Behavior
    virtual void vf44();  // 00549FA0 slot 0x44  overrides Behavior
    virtual void vf48();  // 0054A0A0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005599B0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00558760 slot 0x50  overrides Behavior
    virtual void vf54();  // 00547120 slot 0x54  overrides Behavior
    virtual void vf6C();  // 00547170 slot 0x6C  overrides Behavior
    virtual void vf70();  // 005471F0 slot 0x70  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 0054A1F0 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00547240 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00547250 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 00547350 slot 0x158  overrides Behavior
    virtual undefined4 vf17C();  // 00AAE640 slot 0x17C  overrides Behavior
    virtual undefined4 vf184();  // 00547380 slot 0x184  overrides Behavior
    virtual void vf188();  // 00547390 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 0054C820 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00547CB0 slot 0x1A4  overrides Behavior
    virtual undefined4 vf1DC();  // 00AAE650 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 00547F50 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AAE630 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 005470E0 slot 0x264  overrides Behavior
    virtual undefined4 vf32C();  // 0054F6A0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf34C();  // 00547EF0 slot 0x34C  overrides BehaviorEmBase
    virtual void vf358(undefined4 param_2, int param_3);  // 00551B80 slot 0x358  overrides BehaviorEmBase
};
