// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0310 : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6FC0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAD4E0 slot 0x4  overrides cObj
    virtual void vf30();  // 00593E50 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00594360 slot 0x40  overrides Behavior
    virtual void vf44();  // 00588B20 slot 0x44  overrides Behavior
    virtual void vf48();  // 00594700 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00596B70 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0057BBC0 slot 0x50  overrides Behavior
    virtual void vfFC();  // 00588D30 slot 0xFC  overrides Behavior
    virtual void vf100();  // 005931E0 slot 0x100  overrides Behavior
    virtual void vf104();  // 0057FAD0 slot 0x104  overrides Behavior
    virtual void vf108();  // 0057BC60 slot 0x108  overrides Behavior
    virtual undefined4 vf10C();  // 0057FB10 slot 0x10C  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00583CE0 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 0057D620 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00593DB0 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 0057D650 slot 0x158  overrides Behavior
    virtual undefined4 vf1A0();  // 00584150 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00596930 slot 0x1A4  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 0057DA00 slot 0x1B8  overrides Behavior
    virtual undefined4 vf228();  // 0057BC20 slot 0x228  overrides Behavior
    virtual void vf248();  // 00588C60 slot 0x248  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 005930B0 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 0057BC50 slot 0x268  overrides Behavior
    virtual undefined4 vf32C();  // 00596BB0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 0058FF40 slot 0x334  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 0057DAA0 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 0058AE90 slot 0x34C  overrides BehaviorEmBase
    // non-virtual members
    Em0310();  // 00AAD3E0
};
