// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBgBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0310QteCeiling : public BehaviorBgBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7080 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6430 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00586400 slot 0x40  overrides Behavior
    virtual void vf44();  // 0058AA00 slot 0x44  overrides Behavior
    virtual void vf48();  // 005910D0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0057E6E0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0057E740 slot 0x50  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 0057E770 slot 0x1B8  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 0057E750 slot 0x1D0  overrides Behavior
    // non-virtual members
    Em0310QteCeiling();  // 00AA6410
};
