// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorDebrisBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em0310Debris : public BehaviorDebrisBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8840 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAFC20 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00592BA0 slot 0x40  overrides Behavior
    virtual void vf44();  // 0057F470 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00588530 slot 0x4C  overrides Behavior
    virtual void vf54();  // 00592FB0 slot 0x54  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 0057F4D0 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 0057F480 slot 0x1BC  overrides Behavior
    // non-virtual members
    Em0310Debris();  // 00AAFC00
};
