// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em060c : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6AF0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA61E0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0059FC80 slot 0x40  overrides Behavior
    virtual void vf44();  // 0059FD20 slot 0x44  overrides Behavior
    virtual void vf4C();  // 0059FCD0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0059FCF0 slot 0x50  overrides Behavior
    // non-virtual members
    Em060c();  // 00AA61C0
};
