// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em1000 : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7740 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6700 slot 0x4  overrides cObj
    virtual void vf30();  // 005C6710 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 005C6740 slot 0x40  overrides Behavior
    virtual void vf44();  // 005C69B0 slot 0x44  overrides Behavior
    virtual void vf48();  // 005C6B20 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005C6690 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005C66A0 slot 0x50  overrides Behavior
    virtual void vf54();  // 005C66D0 slot 0x54  overrides Behavior
    virtual void vf114();  // 005C6660 slot 0x114  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 00AA6710 slot 0x1D0  overrides Behavior
    // non-virtual members
    Em1000();  // 00AA66E0
};
