// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em1010 : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB77B0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAEC90 slot 0x4  overrides cObj
    virtual void vf30();  // 005C6BA0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 005C8870 slot 0x40  overrides Behavior
    virtual void vf44();  // 005C7500 slot 0x44  overrides Behavior
    virtual void vf48();  // 005C8710 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005C8E10 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005C6B70 slot 0x50  overrides Behavior
    virtual void vf54();  // 005C6F40 slot 0x54  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 005C6E90 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 005C7490 slot 0x268  overrides Behavior
    virtual void vf2A0();  // 005C6D80 slot 0x2A0  overrides Behavior
    virtual undefined4 vf2D4();  // 005C6C00 slot 0x2D4  overrides Behavior
    virtual undefined4 vf32C();  // 005C8030 slot 0x32C  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 005C6BF0 slot 0x33C  overrides BehaviorEmBase
    // non-virtual members
    Em1010();  // 00AAEC40
};
