// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEm0010Weapon.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em8010Weapon : public cEm0010Weapon {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA790 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB5EE0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0061E740 slot 0x40  overrides Behavior
    virtual undefined4 vf94();  // 00AB5EF0 slot 0x94  overrides Behavior
    virtual undefined4 vf98();  // 0061E8B0 slot 0x98  overrides Behavior
    // non-virtual members
    Em8010Weapon();  // 00AB5EA0
};
