// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "WpBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em8070Gun : public WpBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA3F0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB50E0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 006ACAC0 slot 0x40  overrides Behavior
    virtual void vf44();  // 006A3910 slot 0x44  overrides Behavior
    virtual void vf48();  // 006B74D0 slot 0x48  overrides Behavior
    // non-virtual members
    Em8070Gun();  // 00AB50A0
};
