// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em8040 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA390 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB4BB0 slot 0x4  overrides cObj
    virtual void vf30();  // 00667560 slot 0x30  overrides cObj
    virtual void vf34();  // 0065FD60 slot 0x34  overrides cObj
    virtual void vf3C(undefined4 param_2);  // 0065C7D0 slot 0x3C  overrides cObj
    virtual undefined4 startup();  // 00676C40 slot 0x40  overrides Behavior
    virtual void vf44();  // 0065FDF0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00676D10 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0067BD80 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0066D520 slot 0x50  overrides Behavior
    virtual void vf54();  // 0065C820 slot 0x54  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 0065FD70 slot 0x110  overrides Behavior
    virtual bool vf118(int param_2);  // 0065FD10 slot 0x118  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00660350 slot 0x130  overrides Behavior
    virtual undefined4 vf13C();  // 00665980 slot 0x13C  overrides Behavior
    virtual float10 vf140();  // 00AB4BC0 slot 0x140  overrides Behavior
    virtual float10 vf144();  // 00AB4BD0 slot 0x144  overrides Behavior
    virtual undefined4 vf14C();  // 00662F70 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00669320 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 0065DB00 slot 0x158  overrides Behavior
    virtual void vf188();  // 0066DFC0 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 0066B560 slot 0x19C  overrides Behavior
    virtual undefined4 vf1A0();  // 0065CBD0 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0066E010 slot 0x1A4  overrides Behavior
    virtual undefined4 vf1B0();  // 0065CBE0 slot 0x1B0  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 0065C810 slot 0x1D0  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 00676D20 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 0066D570 slot 0x268  overrides Behavior
    virtual void vf294();  // 0065EC80 slot 0x294  overrides Behavior
    virtual void vf298();  // 0065EC90 slot 0x298  overrides Behavior
    virtual void vf29C();  // 0065ECA0 slot 0x29C  overrides Behavior
    virtual void vf2A0();  // 006657E0 slot 0x2A0  overrides Behavior
    virtual void vf2A4();  // 0065ECB0 slot 0x2A4  overrides Behavior
    virtual void vf2A8();  // 0065ECC0 slot 0x2A8  overrides Behavior
    virtual void vf2AC();  // 0065ECD0 slot 0x2AC  overrides Behavior
    virtual void vf2B0();  // 0065ECE0 slot 0x2B0  overrides Behavior
    virtual undefined4 vf2D4();  // 00665A00 slot 0x2D4  overrides Behavior
    virtual void vf2F8();  // 0065C830 slot 0x2F8  overrides Behavior
    virtual void vf300();  // 0065C7B0 slot 0x300  overrides BehaviorAppBase
    virtual void vf304();  // 0065C7C0 slot 0x304  overrides BehaviorAppBase
    virtual undefined4 vf32C();  // 00679CF0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 00674EB0 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 006667D0 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 00666880 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 0066E5D0 slot 0x34C  overrides BehaviorEmBase
    // non-virtual members
    static void createDestructExplosion();  // 00664340
};
