// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em8120 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA480 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB5690 slot 0x4  overrides cObj
    virtual void vf30();  // 006E0850 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 006E5310 slot 0x40  overrides Behavior
    virtual void vf44();  // 006D6C40 slot 0x44  overrides Behavior
    virtual void vf48();  // 006E08C0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 006E9270 slot 0x4C  overrides Behavior
    virtual void vf50();  // 006E0930 slot 0x50  overrides Behavior
    virtual void vf54();  // 006D6DB0 slot 0x54  overrides Behavior
    virtual void vf6C();  // 006D9060 slot 0x6C  overrides Behavior
    virtual void vf70();  // 006D9070 slot 0x70  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 006DD8B0 slot 0x130  overrides Behavior
    virtual undefined4 vf13C();  // 006E4B40 slot 0x13C  overrides Behavior
    virtual float10 vf140();  // 00AB56A0 slot 0x140  overrides Behavior
    virtual float10 vf144();  // 00AB56B0 slot 0x144  overrides Behavior
    virtual float10 vf148();  // 00AB56C0 slot 0x148  overrides Behavior
    virtual undefined4 vf14C();  // 006DFC80 slot 0x14C  overrides Behavior
    virtual void vf150();  // 006DFCC0 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 006D9370 slot 0x158  overrides Behavior
    virtual undefined4 vf184();  // 006D6C00 slot 0x184  overrides Behavior
    virtual void vf188();  // 006D6C10 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 006E4680 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 006D8CD0 slot 0x1A4  overrides Behavior
    virtual void vf1BC(int * param_2);  // 006DF9A0 slot 0x1BC  overrides Behavior
    virtual void vf1C0();  // 006D9360 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AB56E0 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 006D9030 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AB56D0 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 006E4740 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 006DEC10 slot 0x268  overrides Behavior
    virtual void vf298();  // 006E0990 slot 0x298  overrides Behavior
    virtual void vf2A0();  // 006D7F20 slot 0x2A0  overrides Behavior
    virtual void vf2A4();  // 006E0A00 slot 0x2A4  overrides Behavior
    virtual void vf2A8();  // 006E0AC0 slot 0x2A8  overrides Behavior
    virtual undefined4 vf32C();  // 006E66A0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf338();  // 006DFC30 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 006DF450 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 006DEA80 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 006DEBE0 slot 0x360  overrides BehaviorEmBase
};
