// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "WpBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em8220Weapon : public WpBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA720 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB5E20 slot 0x4  overrides cObj
    virtual void vf30();  // 006FB1A0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 006FB020 slot 0x40  overrides Behavior
    virtual void vf44();  // 006FFC40 slot 0x44  overrides Behavior
    virtual void vf48();  // 007074D0 slot 0x48  overrides Behavior
    virtual void vf54();  // 006EBDA0 slot 0x54  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 006EBDC0 slot 0x1B8  overrides Behavior
    virtual void vf1C8();  // 006EBDB0 slot 0x1C8  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 00AB5E30 slot 0x1D0  overrides Behavior
    virtual void vf25C(undefined4 param_2, int param_3, int param_4);  // 006FB200 slot 0x25C  overrides Behavior
    // non-virtual members
    Em8220Weapon();  // 00AB5DE0
};
