// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Em8220 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA700 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB5D20 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00704FC0 slot 0x40  overrides Behavior
    virtual void vf44();  // 006FB300 slot 0x44  overrides Behavior
    virtual void vf48();  // 006FB480 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00707C70 slot 0x4C  overrides Behavior
    virtual void vf50();  // 006E9810 slot 0x50  overrides Behavior
    virtual void vf54();  // 00705CB0 slot 0x54  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 006EC920 slot 0x110  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 006EFD50 slot 0x130  overrides Behavior
    virtual undefined4 vf13C();  // 006EF9F0 slot 0x13C  overrides Behavior
    virtual float10 vf140();  // 00AB5D30 slot 0x140  overrides Behavior
    virtual float10 vf144();  // 00AB5D40 slot 0x144  overrides Behavior
    virtual undefined4 vf14C();  // 006F2F90 slot 0x14C  overrides Behavior
    virtual void vf150();  // 006F3050 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 006EA770 slot 0x158  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 006FDAF0 slot 0x19C  overrides Behavior
    virtual undefined4 vf1A0();  // 006F02D0 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 006F0080 slot 0x1A4  overrides Behavior
    virtual undefined4 vf228();  // 006E9860 slot 0x228  overrides Behavior
    virtual void vf248();  // 006EC7F0 slot 0x248  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 006FB660 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 006EC830 slot 0x268  overrides Behavior
    virtual void vf294();  // 006EA1F0 slot 0x294  overrides Behavior
    virtual void vf298();  // 006EA200 slot 0x298  overrides Behavior
    virtual void vf29C();  // 006EA210 slot 0x29C  overrides Behavior
    virtual void vf2A0();  // 006EF630 slot 0x2A0  overrides Behavior
    virtual void vf2A4();  // 006EA220 slot 0x2A4  overrides Behavior
    virtual void vf2A8();  // 006EA230 slot 0x2A8  overrides Behavior
    virtual void vf2AC();  // 006EA240 slot 0x2AC  overrides Behavior
    virtual void vf2B0();  // 006EA250 slot 0x2B0  overrides Behavior
    virtual void vf2F8();  // 006E9830 slot 0x2F8  overrides Behavior
    virtual undefined4 vf32C();  // 00706610 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 007038A0 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 006F8BF0 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 006FECC0 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 006FBCF0 slot 0x34C  overrides BehaviorEmBase
    virtual undefined4 vf368();  // 006E9880 slot 0x368  overrides BehaviorEmBase
    // non-virtual members
    Em8220();  // 00AB5B90
};
