// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EmAfterImage : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB68B0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AABDF0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00AC4D90 slot 0x40  overrides Behavior
    virtual void vf44();  // 00AC4E00 slot 0x44  overrides Behavior
    virtual void vf48();  // 00AC4E10 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00ACF790 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00AC4E20 slot 0x50  overrides Behavior
    virtual void vf54();  // 00AC4E30 slot 0x54  overrides Behavior
    // non-virtual members
    EmAfterImage();  // 00AABDC0
};
