// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc060 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9E30 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB2710 slot 0x4  overrides cObj
    virtual void vf2C();  // 00777FC0 slot 0x2C  overrides cObj
    virtual undefined4 startup();  // 00795920 slot 0x40  overrides Behavior
    virtual void vf44();  // 0077C900 slot 0x44  overrides Behavior
    virtual void vf48();  // 007910B0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 007983C0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0077CA00 slot 0x50  overrides Behavior
    virtual void vf54();  // 007914A0 slot 0x54  overrides Behavior
    virtual void vf6C();  // 00777CC0 slot 0x6C  overrides Behavior
    virtual void vf70();  // 00777CD0 slot 0x70  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 007787D0 slot 0x110  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00783440 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00776EE0 slot 0x14C  overrides Behavior
    virtual void vf150();  // 0077C760 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 00776F10 slot 0x158  overrides Behavior
    virtual undefined4 vf184();  // 00776F20 slot 0x184  overrides Behavior
    virtual void vf188();  // 00776F30 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 0078A390 slot 0x19C  overrides Behavior
    virtual undefined4 vf1A0();  // 0077A920 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0077A930 slot 0x1A4  overrides Behavior
    virtual void vf1C0();  // 00779600 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AB2730 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 00777C90 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AB2720 slot 0x20C  overrides Behavior
    virtual void vf248();  // 0077E900 slot 0x248  overrides Behavior
    virtual void vf258();  // 0077F940 slot 0x258  overrides Behavior
    virtual void vf260();  // 0077F9D0 slot 0x260  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 0077E9A0 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 00777F60 slot 0x268  overrides Behavior
    virtual undefined4 vf2D4();  // 00778BA0 slot 0x2D4  overrides Behavior
    virtual void vf2F8();  // 00776F60 slot 0x2F8  overrides Behavior
    virtual undefined4 vf32C();  // 007986A0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 00789770 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 00789660 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 0078D790 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 00777D70 slot 0x34C  overrides BehaviorEmBase
    virtual void vf358(undefined4 param_2, int param_3);  // 00777E20 slot 0x358  overrides BehaviorEmBase
    virtual undefined4 vf368();  // 00776F90 slot 0x368  overrides BehaviorEmBase
    // non-virtual members
    static void R0_ExplodeDie();  // 0078DC00
    static void R0_ExplodeDie_2();  // 00792FD0
    static void R0_ChanceAttack();  // 00793FC0
    Emc060();  // 00AB25F0
};
