// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc080 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9EE0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB2C50 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 007C0ED0 slot 0x40  overrides Behavior
    virtual void vf44();  // 007BA2B0 slot 0x44  overrides Behavior
    virtual void vf48();  // 007C2BE0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 007CA640 slot 0x4C  overrides Behavior
    virtual void vf50();  // 007B2350 slot 0x50  overrides Behavior
    virtual void vf54();  // 007AEE10 slot 0x54  overrides Behavior
    virtual void vf6C();  // 007B09A0 slot 0x6C  overrides Behavior
    virtual void vf70();  // 007B09B0 slot 0x70  overrides Behavior
    virtual void vfFC();  // 007B1100 slot 0xFC  overrides Behavior
    virtual void vf100();  // 007B1140 slot 0x100  overrides Behavior
    virtual void vf104();  // 007B1170 slot 0x104  overrides Behavior
    virtual void vf108();  // 007B1180 slot 0x108  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 007B1190 slot 0x110  overrides Behavior
    virtual bool vf118(int param_2);  // 007AED00 slot 0x118  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 007B1D90 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 007B7A00 slot 0x14C  overrides Behavior
    virtual void vf150();  // 007B7A60 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 007B1730 slot 0x158  overrides Behavior
    virtual undefined4 vf17C();  // 00AB2C60 slot 0x17C  overrides Behavior
    virtual undefined4 vf180();  // 00AB2C70 slot 0x180  overrides Behavior
    virtual undefined4 vf184();  // 007B1740 slot 0x184  overrides Behavior
    virtual void vf188();  // 007B1750 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 007BE700 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 007B0940 slot 0x1A4  overrides Behavior
    virtual void vf1C0();  // 007B88B0 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AB2C90 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 007B0970 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AB2C80 slot 0x20C  overrides Behavior
    virtual void vf258();  // 007B1910 slot 0x258  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 007B21E0 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 007B2460 slot 0x268  overrides Behavior
    virtual void vf27C(undefined4 * param_2);  // 00AB2CA0 slot 0x27C  overrides Behavior
    virtual undefined4 vf280();  // 007B6690 slot 0x280  overrides Behavior
    virtual undefined4 vf284();  // 007BE940 slot 0x284  overrides Behavior
    virtual undefined4 vf288();  // 007B0DA0 slot 0x288  overrides Behavior
    virtual void vf300();  // 007B1B50 slot 0x300  overrides BehaviorAppBase
    virtual void vf304();  // 007AED60 slot 0x304  overrides BehaviorAppBase
    virtual undefined4 vf32C();  // 007C0950 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 007B83D0 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 007B8370 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 007B7EE0 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 007BE7C0 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 007B6360 slot 0x360  overrides BehaviorEmBase
    virtual undefined4 vf368();  // 007B7510 slot 0x368  overrides BehaviorEmBase
};
