// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc070 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9E50 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB28A0 slot 0x4  overrides cObj
    virtual void vf2C();  // 0079A3E0 slot 0x2C  overrides cObj
    virtual void vf30();  // 00798C10 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 007AAF60 slot 0x40  overrides Behavior
    virtual void vf44();  // 0079C2A0 slot 0x44  overrides Behavior
    virtual void vf48();  // 007ABC20 slot 0x48  overrides Behavior
    virtual void vf4C();  // 007AE780 slot 0x4C  overrides Behavior
    virtual void vf50();  // 007AC780 slot 0x50  overrides Behavior
    virtual void vf54();  // 0079CD90 slot 0x54  overrides Behavior
    virtual void vf108();  // 00798BF0 slot 0x108  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 0079AA50 slot 0x110  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 0079CDE0 slot 0x130  overrides Behavior
    virtual undefined4 vf13C();  // 0079FFC0 slot 0x13C  overrides Behavior
    virtual float10 vf140();  // 00AB28B0 slot 0x140  overrides Behavior
    virtual float10 vf144();  // 00AB28C0 slot 0x144  overrides Behavior
    virtual undefined4 vf14C();  // 0079D0C0 slot 0x14C  overrides Behavior
    virtual void vf150();  // 007A4A90 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 007A4BB0 slot 0x158  overrides Behavior
    virtual undefined4 vf17C();  // 00AB28D0 slot 0x17C  overrides Behavior
    virtual undefined4 vf180();  // 00AB28E0 slot 0x180  overrides Behavior
    virtual undefined4 vf184();  // 00798CA0 slot 0x184  overrides Behavior
    virtual void vf188();  // 00798CB0 slot 0x188  overrides Behavior
    virtual undefined4 vf194();  // 007A0610 slot 0x194  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 007A8880 slot 0x19C  overrides Behavior
    virtual undefined4 vf1A0();  // 0079FC50 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0079A2F0 slot 0x1A4  overrides Behavior
    virtual void vf1C0();  // 0079B9F0 slot 0x1C0  overrides Behavior
    virtual float10 vf20C();  // 00AB28F0 slot 0x20C  overrides Behavior
    virtual void vf260();  // 0079B9E0 slot 0x260  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 0079C3C0 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 0079CAA0 slot 0x268  overrides Behavior
    virtual void vf294();  // 0079BEC0 slot 0x294  overrides Behavior
    virtual void vf298();  // 0079BED0 slot 0x298  overrides Behavior
    virtual void vf29C();  // 0079BEF0 slot 0x29C  overrides Behavior
    virtual void vf2A0();  // 0079BF30 slot 0x2A0  overrides Behavior
    virtual void vf2A4();  // 0079BF70 slot 0x2A4  overrides Behavior
    virtual void vf2A8();  // 0079BF90 slot 0x2A8  overrides Behavior
    virtual void vf2AC();  // 0079BFC0 slot 0x2AC  overrides Behavior
    virtual void vf2B0();  // 0079BFE0 slot 0x2B0  overrides Behavior
    virtual void vf2B4();  // 0079BFF0 slot 0x2B4  overrides Behavior
    virtual void vf2B8();  // 0079C000 slot 0x2B8  overrides Behavior
    virtual void vf2BC();  // 0079C010 slot 0x2BC  overrides Behavior
    virtual void vf2C0();  // 0079C020 slot 0x2C0  overrides Behavior
    virtual void vf2C4();  // 0079C030 slot 0x2C4  overrides Behavior
    virtual void vf2C8();  // 0079C040 slot 0x2C8  overrides Behavior
    virtual void vf2CC();  // 0079C050 slot 0x2CC  overrides Behavior
    virtual void vf2D0();  // 0079C060 slot 0x2D0  overrides Behavior
    virtual undefined4 vf2D4();  // 0079C070 slot 0x2D4  overrides Behavior
    virtual undefined4 vf32C();  // 007A97D0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 007A2A80 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 007A28F0 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 007A20C0 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 0079A2C0 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 0079A3D0 slot 0x360  overrides BehaviorEmBase
    virtual undefined4 vf368();  // 007A0630 slot 0x368  overrides BehaviorEmBase
    // non-virtual members
    Emc070();  // 00AB27C0
};
