// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc030Wire : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9DA0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB23C0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00744DB0 slot 0x40  overrides Behavior
    virtual void vf44();  // 007407D0 slot 0x44  overrides Behavior
    virtual void vf4C();  // 0074D630 slot 0x4C  overrides Behavior
    virtual void vf50();  // 007407E0 slot 0x50  overrides Behavior
    virtual undefined4 vf94();  // 007408B0 slot 0x94  overrides Behavior
    virtual undefined4 vf98();  // 007408D0 slot 0x98  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00744E80 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00740800 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00740840 slot 0x150  overrides Behavior
    virtual undefined4 vf1A0();  // 00744F90 slot 0x1A0  overrides Behavior
};
