// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc040 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9E10 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB2550 slot 0x4  overrides cObj
    virtual void vf30();  // 0075E7A0 slot 0x30  overrides cObj
    virtual void vf34();  // 00754D20 slot 0x34  overrides cObj
    virtual void vf3C(undefined4 param_2);  // 007511B0 slot 0x3C  overrides cObj
    virtual undefined4 startup();  // 007714B0 slot 0x40  overrides Behavior
    virtual void vf44();  // 0075E880 slot 0x44  overrides Behavior
    virtual void vf48();  // 007715A0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00776D00 slot 0x4C  overrides Behavior
    virtual void vf50();  // 007715E0 slot 0x50  overrides Behavior
    virtual void vf54();  // 00765AB0 slot 0x54  overrides Behavior
    virtual void vf110(undefined4 param_2);  // 00754D30 slot 0x110  overrides Behavior
    virtual bool vf118(int param_2);  // 00754CD0 slot 0x118  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00755330 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00757F00 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00760620 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 007524F0 slot 0x158  overrides Behavior
    virtual void vf188();  // 00766530 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00762240 slot 0x19C  overrides Behavior
    virtual undefined4 vf1A0();  // 00755220 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00771930 slot 0x1A4  overrides Behavior
    virtual undefined4 vf1B0();  // 00751590 slot 0x1B0  overrides Behavior
    virtual void vf1D0(undefined4 param_2);  // 00754DB0 slot 0x1D0  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 007716E0 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 00765B10 slot 0x268  overrides Behavior
    virtual void vf294();  // 00753E30 slot 0x294  overrides Behavior
    virtual void vf298();  // 00753E40 slot 0x298  overrides Behavior
    virtual void vf29C();  // 00753E50 slot 0x29C  overrides Behavior
    virtual void vf2A0();  // 00753E60 slot 0x2A0  overrides Behavior
    virtual void vf2A4();  // 00753E70 slot 0x2A4  overrides Behavior
    virtual void vf2A8();  // 00753E80 slot 0x2A8  overrides Behavior
    virtual void vf2AC();  // 00753E90 slot 0x2AC  overrides Behavior
    virtual void vf2B0();  // 00753EA0 slot 0x2B0  overrides Behavior
    virtual void vf2B4();  // 00753EB0 slot 0x2B4  overrides Behavior
    virtual void vf2B8();  // 00753EC0 slot 0x2B8  overrides Behavior
    virtual void vf2BC();  // 00753ED0 slot 0x2BC  overrides Behavior
    virtual void vf2C0();  // 00753EE0 slot 0x2C0  overrides Behavior
    virtual void vf2C4();  // 00753EF0 slot 0x2C4  overrides Behavior
    virtual void vf2C8();  // 00753F00 slot 0x2C8  overrides Behavior
    virtual void vf2CC();  // 00753F10 slot 0x2CC  overrides Behavior
    virtual void vf2D0();  // 00753F20 slot 0x2D0  overrides Behavior
    virtual void vf2F8();  // 007511F0 slot 0x2F8  overrides Behavior
    virtual void vf300();  // 00751190 slot 0x300  overrides BehaviorAppBase
    virtual void vf304();  // 007511A0 slot 0x304  overrides BehaviorAppBase
    virtual undefined4 vf32C();  // 007745D0 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 0076F890 slot 0x334  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 0075DAB0 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 00766880 slot 0x34C  overrides BehaviorEmBase
    // non-virtual members
    Emc040();  // 00AB2430
};
