// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc120 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9F20 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB3270 slot 0x4  overrides cObj
    virtual void vf30();  // 007E6510 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 007EAC70 slot 0x40  overrides Behavior
    virtual void vf44();  // 007DDA50 slot 0x44  overrides Behavior
    virtual void vf48();  // 007E6580 slot 0x48  overrides Behavior
    virtual void vf4C();  // 007EEB40 slot 0x4C  overrides Behavior
    virtual void vf50();  // 007E65F0 slot 0x50  overrides Behavior
    virtual void vf54();  // 007DDBC0 slot 0x54  overrides Behavior
    virtual void vf6C();  // 007DFD90 slot 0x6C  overrides Behavior
    virtual void vf70();  // 007DFDA0 slot 0x70  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 007E4170 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 007DD9F0 slot 0x14C  overrides Behavior
    virtual void vf150();  // 007E00D0 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 007DDA00 slot 0x158  overrides Behavior
    virtual undefined4 vf184();  // 007DDA10 slot 0x184  overrides Behavior
    virtual void vf188();  // 007DDA20 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 007EA0B0 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 007DFAC0 slot 0x1A4  overrides Behavior
    virtual void vf1BC(int * param_2);  // 007E6250 slot 0x1BC  overrides Behavior
    virtual void vf1C0();  // 007E0090 slot 0x1C0  overrides Behavior
    virtual undefined4 vf1DC();  // 00AB3290 slot 0x1DC  overrides Behavior
    virtual float * vf208(float * param_2);  // 007DFD60 slot 0x208  overrides Behavior
    virtual float10 vf20C();  // 00AB3280 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 007EA170 slot 0x264  overrides Behavior
    virtual undefined4 vf268();  // 007E5460 slot 0x268  overrides Behavior
    virtual undefined4 vf32C();  // 007EC010 slot 0x32C  overrides BehaviorEmBase
    virtual void vf338();  // 007E64C0 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 007E5D00 slot 0x33C  overrides BehaviorEmBase
    virtual void vf34C();  // 007E52D0 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 007E5430 slot 0x360  overrides BehaviorEmBase
    virtual void vf370(float param_2);  // 007E5630 slot 0x370  overrides EmBaseDLC
    // non-virtual members
    Emc120();  // 00AB3150
};
