// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpAllCdPointCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc190MoveCheckLinearCastCollector : public hkpAllCdPointCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00807560 slot 0x0  overrides hkpCdPointCollector
    virtual void vf04(int param_1);  // 008074C0 slot 0x4  overrides hkpCdPointCollector
    // non-virtual members
    Emc190MoveCheckLinearCastCollector();  // 00807490
};
