// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc200 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9FF0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB3A30 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00815570 slot 0x40  overrides Behavior
    virtual void vf44();  // 0080B2E0 slot 0x44  overrides Behavior
    virtual void vf48();  // 008175E0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0081F4B0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0081C220 slot 0x50  overrides Behavior
    virtual void vf54();  // 008088D0 slot 0x54  overrides Behavior
    virtual void vf6C();  // 00808920 slot 0x6C  overrides Behavior
    virtual void vf70();  // 008089A0 slot 0x70  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 0080B480 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 008089F0 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00808A50 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 00808B30 slot 0x158  overrides Behavior
    virtual undefined4 vf17C();  // 00AB3A50 slot 0x17C  overrides Behavior
    virtual undefined4 vf184();  // 00808B80 slot 0x184  overrides Behavior
    virtual void vf188();  // 00808B90 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00814B10 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00809170 slot 0x1A4  overrides Behavior
    virtual undefined4 vf1DC();  // 00AB3A60 slot 0x1DC  overrides Behavior
    virtual float10 vf20C();  // 00AB3A40 slot 0x20C  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 00808890 slot 0x264  overrides Behavior
    virtual undefined4 vf32C();  // 0081B990 slot 0x32C  overrides BehaviorEmBase
    virtual void vf358(undefined4 param_2, int param_3);  // 0081A360 slot 0x358  overrides BehaviorEmBase
};
