// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EmBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Emc700 : public EmBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA030 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB3DA0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0084F6A0 slot 0x40  overrides Behavior
    virtual void vf44();  // 00843EA0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00850370 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00859B10 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00848ED0 slot 0x50  overrides Behavior
    virtual void vf54();  // 0083FED0 slot 0x54  overrides Behavior
    virtual undefined4 vf94();  // 00AB3DB0 slot 0x94  overrides Behavior
    virtual undefined4 vf10C();  // 00842DB0 slot 0x10C  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00845A70 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00846EF0 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00842EF0 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 008430C0 slot 0x158  overrides Behavior
    virtual void vf15C();  // 008430D0 slot 0x15C  overrides Behavior
    virtual undefined4 vf17C();  // 0083FF20 slot 0x17C  overrides Behavior
    virtual undefined4 vf184();  // 0083FF30 slot 0x184  overrides Behavior
    virtual void vf188();  // 0083FF50 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00848F80 slot 0x19C  overrides Behavior
    virtual undefined4 vf1A0();  // 00844A40 slot 0x1A0  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00857B90 slot 0x1A4  overrides Behavior
    virtual void vf248();  // 00846EA0 slot 0x248  overrides Behavior
    virtual undefined4 setEmSetInfo();  // 0083FEC0 slot 0x264  overrides Behavior
    virtual undefined4 vf32C();  // 00850530 slot 0x32C  overrides BehaviorEmBase
    virtual void vf34C();  // 008405F0 slot 0x34C  overrides BehaviorEmBase
    virtual void vf360();  // 00845DC0 slot 0x360  overrides BehaviorEmBase
};
