// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspStrip2p.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp06 : public cEspStrip2p {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED2D10 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F2E930 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F144A0 slot 0x8  overrides cEspBase
    virtual void vf28();  // 00EEDD30 slot 0x28  overrides cEspStrip2p
    // non-virtual members
    esp06();  // 00ED2CE0
};
