// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "esp13.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp170 : public esp13 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009E01B0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 009D1450 slot 0x4  overrides cEspBase
    // non-virtual members
    esp170();  // 009E0180
    static void vf08();  // 00F23340
};
