// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp111 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009DF510 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 009D9350 slot 0x4  overrides cEspBase
    virtual void vf08();  // 009CFFC0 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 009CFFD0 slot 0x10  overrides cEspBase
    virtual void vf14();  // 009D0030 slot 0x14  overrides cEspBase
    // non-virtual members
    esp111();  // 009D42F0
};
