// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "esp28.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp110 : public esp28 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009E8480 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 009D8A80 slot 0x4  overrides cEspBase
    virtual void vf08();  // 009D8AF0 slot 0x8  overrides cEspBase
    // non-virtual members
    esp110();  // 009E8450
};
