// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp18 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F407C0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F32270 slot 0x4  overrides cEspBase
    virtual void addOtTransList();  // 00F32A90 slot 0x10  overrides cEspBase
    virtual void vf14();  // 00ED85A0 slot 0x14  overrides cEspBase
    virtual bool vf18(int param_2);  // 00EF13F0 slot 0x18  overrides cEspBase
    // non-virtual members
    static undefined4 preTrans_009E1140(undefined4 * param_2);  // 009E1140
    esp18();  // 00F17630
};
