// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp106 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009DF460 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 009CFEB0 slot 0x4  overrides cEspBase
    virtual void addOtTransList();  // 009D8930 slot 0x10  overrides cEspBase
    virtual void vf14();  // 009CFEC0 slot 0x14  overrides cEspBase
    // non-virtual members
    esp106();  // 009D4270
};
