// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "esp11.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp161 : public esp11 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009F6E50 slot 0x0  overrides cEspBase
    virtual void vf08();  // 009D0B90 slot 0x8  overrides cEspBase
    // non-virtual members
    esp161();  // 009F6DB0
};
