// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp120 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009DF610 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 009D06D0 slot 0x4  overrides cEspBase
    virtual void vf08();  // 009D06F0 slot 0x8  overrides cEspBase
    // non-virtual members
    esp120();  // 009D43F0
};
