// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp100 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009DF3C0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 009D65B0 slot 0x4  overrides cEspBase
    virtual void vf08();  // 009CF8F0 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 009CF960 slot 0x10  overrides cEspBase
    // non-virtual members
    esp100();  // 009D41F0
};
