// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspStrip.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp29 : public cEspStrip {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED09A0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F35560 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F19B60 slot 0x8  overrides cEspBase
    virtual void vf14();  // 00EF2FB0 slot 0x14  overrides cEspBase
    // non-virtual members
    esp29();  // 00ED0580
};
