// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp28Strip.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp28 : public cEsp28Strip {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009DF6B0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F352F0 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F23880 slot 0x8  overrides cEspBase
    virtual void vf14();  // 00F04A20 slot 0x14  overrides cEspBase
    // non-virtual members
    esp28();  // 009DF4E0
};
