// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspStrip.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp24 : public cEspStrip {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED0960 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F34B70 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F2A260 slot 0x8  overrides cEspBase
    // non-virtual members
    esp24();  // 00ED0530
};
