// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp25 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F408B0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F34D30 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F18B70 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 00ED8850 slot 0x10  overrides cEspBase
    virtual void vf14();  // 00ED8820 slot 0x14  overrides cEspBase
    // non-virtual members
    esp25();  // 00F18B40
};
