// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp35 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED0A20 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F364E0 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F10F70 slot 0x8  overrides cEspBase
    // non-virtual members
    esp35();  // 00ECD460
};
