// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspStrip2p.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp34 : public cEspStrip2p {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED2DB0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F360D0 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F1A9B0 slot 0x8  overrides cEspBase
    // non-virtual members
    esp34();  // 00ED2D80
};
