// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "ModelShaderJackModule.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp38 : public ModelShaderJackModule {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED0A60 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F39470 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F1B610 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 00EDA080 slot 0x10  overrides cEspBase
    virtual void vf14();  // 00EF5A40 slot 0x14  overrides cEspBase
    // non-virtual members
    esp38();  // 00ED0640
};
