// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp48 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED0BA0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F381C0 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F250E0 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 00F2C3E0 slot 0x10  overrides cEspBase
    // non-virtual members
    esp48();  // 00ECD560
};
