// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp42 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED0AE0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F37580 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F24B80 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 00F2B960 slot 0x10  overrides cEspBase
    // non-virtual members
    esp42();  // 00ECD4C0
};
