// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp52 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED0BE0 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F38780 slot 0x4  overrides cEspBase
    virtual void addOtTransList();  // 00F2C540 slot 0x10  overrides cEspBase
    // non-virtual members
    esp52();  // 00ECD5A0
};
