// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct esp90 : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED0C40 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F38790 slot 0x4  overrides cEspBase
    virtual void vf08();  // 00F1DA30 slot 0x8  overrides cEspBase
    virtual void addOtTransList();  // 00EDACE0 slot 0x10  overrides cEspBase
    // non-virtual members
    esp90();  // 00ECD5C0
};
