// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspControler.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspAtkController : public cEspControler {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009D5ED0 slot 0x0  overrides cEspControler
    // non-virtual members
    EspAtkController();  // 009CEF20
    static void vf04();  // 009D4730
    static void vf08(undefined4 param_1, undefined4 param_2, int param_3);  // 009D4750
    static void thunk_vf0C();  // 009D4780
};
