// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspControler.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspControllerHitStrip : public cEspControler {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00EAAD60 slot 0x0  overrides cEspControler
    // non-virtual members
    EspControllerHitStrip();  // 00EAAAB0
    void ctor_00EAAB00();  // 00EAAB00
};
