// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "espEmt00.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct espEmt01 : public espEmt00 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ED1D90 slot 0x0  overrides cEspBase
    virtual undefined preTrans();  // 00F0A320 slot 0x4  overrides cEspBase
    virtual void vf1C(void * param_1, void * param_2);  // 00EF6870 slot 0x1C  overrides espEmt00
    // non-virtual members
    espEmt01();  // 00ED1C60
};
