// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspEmtBase : public cEspBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F409E0 slot 0x0  overrides cEspBase
};
