// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspList.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspListThread : public cEspList {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F45680 slot 0x0  overrides cEspList
    virtual undefined4 startup(uint param_2, undefined4 param_3);  // 00F43740 slot 0x4  overrides cEspList
    virtual void vf08();  // 00F43890 slot 0x8  overrides cEspList
    virtual void vf0C();  // 00F438D0 slot 0xC  overrides cEspList
    virtual void vf10();  // 00F43A20 slot 0x10  overrides cEspList
    virtual void preTrans();  // 00F42220 slot 0x14  overrides cEspList
    virtual void vf18();  // 00F43A10 slot 0x18  overrides cEspList
    virtual void vf20(int * param_2, int * param_3);  // 00F442E0 slot 0x20  overrides cEspList
    virtual undefined4 vf24(undefined4 param_1, undefined4 param_2, undefined4 param_3);  // 00F44760 slot 0x24
    // non-virtual members
    EspListThread();  // 00F44140
};
