// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cShaderSetting.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspModelShaderSetting : public cShaderSetting {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009E6240 slot 0x0  overrides cShaderSetting
    virtual void vf10();  // 009DCBC0 slot 0x10  overrides cShaderSetting
    virtual void vf24();  // 009D21D0 slot 0x24  overrides cShaderSetting
};
