// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EspPrimitiveWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspPrimitiveWorkMirrorX2 : public EspPrimitiveWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00F59290 slot 0x0  overrides EspPrimitiveWorkBase
    virtual void vf04(undefined4 param_1);  // 00F51EE0 slot 0x4  overrides EspPrimitiveWorkBase
    virtual void vf08();  // 00F4EFD0 slot 0x8  overrides EspPrimitiveWorkBase
    virtual void vf0C(int param_2);  // 00F4F000 slot 0xC  overrides EspPrimitiveWorkBase
    // non-virtual members
    EspPrimitiveWorkMirrorX2();  // 00F4EF50
};
