// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EspPrimitiveWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspPrimitiveWorkMultiBillboardBase : public EspPrimitiveWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00F59690 slot 0x0  overrides EspPrimitiveWorkBase
    virtual void vf08();  // 00F503C0 slot 0x8  overrides EspPrimitiveWorkBase
    virtual void vf0C(int param_2);  // 00F503F0 slot 0xC  overrides EspPrimitiveWorkBase
    // non-virtual members
    EspPrimitiveWorkMultiBillboardBase();  // 00F50330
    void ctor_00F58BF0();  // 00F58BF0
};
