// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EspPrimitiveWorkBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspPrimitiveWorkBillboard : public EspPrimitiveWorkBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00F59180 slot 0x0  overrides EspPrimitiveWorkBase
    virtual void vf04(undefined4 param_1);  // 00F51230 slot 0x4  overrides EspPrimitiveWorkBase
    virtual void vf08();  // 00F4EB10 slot 0x8  overrides EspPrimitiveWorkBase
    virtual void vf0C(int param_2);  // 00F4EB40 slot 0xC  overrides EspPrimitiveWorkBase
    // non-virtual members
    EspPrimitiveWorkBillboard();  // 00F4EA70
};
