// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderSoftPT3D.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderSoftPT3DToneCurve_TexBlend : public cEspShaderSoftPT3D {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8B4F0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F60900 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderSoftPT3DToneCurve_TexBlend();  // 00F8B3F0
};
