// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderMultiMoveParticleSSB : public cEspShaderBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8C320 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F633C0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderMultiMoveParticleSSB();  // 00F8C2B0
};
