// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EspShaderDrawMirror.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderDrawMirrorRot : public EspShaderDrawMirror {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009DCD90 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 009E69B0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderDrawMirrorRot();  // 009D2580
};
