// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EspShaderAlMask_TexBlend.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderAlMaskVC_TexBlend : public EspShaderAlMask_TexBlend {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8AD90 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F5F170 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderAlMaskVC_TexBlend();  // 00F8AD70
};
