// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderToneCurveAlpha.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderToneCurveAlpha_TexBlend : public cEspShaderToneCurveAlpha {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8C200 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F63190 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderToneCurveAlpha_TexBlend();  // 00F82580
};
