// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderMask.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderScreenDirtDetection : public cEspShaderMask {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8EAB0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F6C6B0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderScreenDirtDetection();  // 00F85570
};
