// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderMultiMoveParticleBillbord.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderMultiMoveParticleBillbord_Shimmer : public cEspShaderMultiMoveParticleBillbord {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8C6C0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F63940 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderMultiMoveParticleBillbord_Shimmer();  // 00F8C4A0
};
