// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderShimmer.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderDrawMirror : public cEspShaderShimmer {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009DCD60 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 009E68B0 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderDrawMirror();  // 009D2550
    void ctor_015ECC90();  // 015ECC90
    void ctor_015ECCB0();  // 015ECCB0
};
