// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEspShaderToneCurveAlMaskSp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspShaderToneCurveAlMaskSp_TexBlend : public cEspShaderToneCurveAlMaskSp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00F8BFE0 slot 0x0  overrides Hw::cShader
    virtual undefined4 vf08();  // 00F62760 slot 0x8  overrides cEspShaderBase
    // non-virtual members
    EspShaderToneCurveAlMaskSp_TexBlend();  // 00F8BEC0
};
