// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "EspWorkParentMeshControlBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct EspWorkParentMeshControl : public EspWorkParentMeshControlBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009F6E80 slot 0x0  overrides cEspBase
    virtual void vf20(undefined4 param_2);  // 009F6BA0 slot 0x20  overrides EspWorkParentMeshControlBase
    virtual void vf24();  // 009F5BF0 slot 0x24  overrides EspWorkParentMeshControlBase
    virtual void vf28();  // 009F1C20 slot 0x28  overrides EspWorkParentMeshControlBase
    // non-virtual members
    EspWorkParentMeshControl();  // 009F6AD0
};
