// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Et0200 : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8120 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6A10 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005D7260 slot 0x40  overrides Behavior
    virtual void vf44();  // 005D71B0 slot 0x44  overrides Behavior
    virtual void vf48();  // 005D71C0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005D71D0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005D71F0 slot 0x50  overrides Behavior
    virtual void vf54();  // 005D7220 slot 0x54  overrides Behavior
    // non-virtual members
    Et0200();  // 00AA69F0
};
