// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Et0503 : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8BE0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6D50 slot 0x4  overrides cObj
    virtual void vf50();  // 005D7330 slot 0x50  overrides Behavior
    // non-virtual members
    Et0503();  // 00AA6D30
};
