// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Et9200 : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8F50 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6E30 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005D7E40 slot 0x40  overrides Behavior
    virtual void vf44();  // 005D7880 slot 0x44  overrides Behavior
    virtual void vf4C();  // 005D7900 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005D7860 slot 0x50  overrides Behavior
    // non-virtual members
    Et9200();  // 00AA6DF0
};
