// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ExcelPartsObj : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB76E0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAEB60 slot 0x4  overrides cObj
    virtual void vf30();  // 005B7D20 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 005B78F0 slot 0x40  overrides Behavior
    virtual void vf44();  // 005B7B40 slot 0x44  overrides Behavior
    virtual void vf48();  // 005C4AC0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005B09E0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005B7C90 slot 0x50  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 005B7BC0 slot 0x130  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 005C4B80 slot 0x1A4  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 005B0A60 slot 0x1B8  overrides Behavior
};
