// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBa.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ExcelStage : public BehaviorBa {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7700 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAEC00 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005B0AB0 slot 0x40  overrides Behavior
    // non-virtual members
    ExcelStage();  // 00AAEBE0
    static void thunk_vf1D0(int param_2);  // 00AC3E70
    static void vf24C();  // 00AC74A0
    static void vf4C();  // 00AC7700
    static void vf50();  // 00AC7740
};
