// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkMallocAllocator.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct HavokMallocAllocator : public hkMallocAllocator {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00();  // 00930DC0 slot 0x0  overrides hkMemoryAllocator
    virtual int vf04(int param_2);  // 00930D10 slot 0x4  overrides hkMemoryAllocator
    virtual void vf08(int param_2, int param_3);  // 00930D80 slot 0x8  overrides hkMemoryAllocator
};
