// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkAlignSceneToNodeOptions : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010D8450 slot 0x0  overrides hkBaseObject
    // non-virtual members
    hkAlignSceneToNodeOptions();  // 010D83C0
    void ctor_010D83E0();  // 010D83E0
};
