// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkStreamWriter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkArrayStreamWriter : public hkStreamWriter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010176C0 slot 0x0  overrides hkBaseObject
    virtual undefined * vf08();  // 01017560 slot 0x8  overrides hkReferencedObject
    virtual void vf0C(undefined1 * param_1);  // 01017530 slot 0xC  overrides hkStreamWriter
    virtual int vf10(undefined4 param_2, int param_3);  // 01029520 slot 0x10  overrides hkStreamWriter
    virtual void vf18(undefined1 * param_1);  // 01017540 slot 0x18  overrides hkStreamWriter
    virtual undefined4 vf1C(int param_2, int param_3);  // 010296B0 slot 0x1C  overrides hkStreamWriter
    virtual undefined4 vf20();  // 01017550 slot 0x20  overrides hkStreamWriter
    virtual void vf24();  // 010294D0 slot 0x24
    // non-virtual members
    hkArrayStreamWriter();  // 010174C0
};
