// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkChainedClassNameRegistry.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkBindingClassNameRegistry : public hkChainedClassNameRegistry {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0105F4A0 slot 0x0  overrides hkBaseObject
    virtual int vf10(uint param_2);  // 0105E490 slot 0x10  overrides hkClassNameRegistry
    virtual void vf2C(undefined4 param_2);  // 0105D7C0 slot 0x2C
    virtual void vf30(undefined4 param_1);  // 0105D870 slot 0x30
    virtual void vf34(int * param_1);  // 0105D810 slot 0x34
    // non-virtual members
    hkBindingClassNameRegistry();  // 0105E5F0
    ~hkBindingClassNameRegistry();  // 0105E6A0
};
