// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkSocket.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkBsdSocket : public hkSocket {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0102C430 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 param_2);  // 0102BD80 slot 0xC  overrides hkSocket
    virtual void vf10();  // 0102BDA0 slot 0x10  overrides hkSocket
    virtual int vf14(char * param_2, int param_3);  // 0102BDF0 slot 0x14  overrides hkSocket
    virtual int vf18(char * param_2, int param_3);  // 0102BE40 slot 0x18  overrides hkSocket
    virtual undefined4 vf1C(undefined4 param_2, undefined4 param_3);  // 0102BEA0 slot 0x1C  overrides hkSocket
    virtual undefined4 vf20(undefined4 param_2);  // 0102C290 slot 0x20  overrides hkSocket
    virtual bool vf24(HWND param_2, undefined4 param_3, uint param_4);  // 0102BF60 slot 0x24  overrides hkSocket
    virtual ulonglong vf28(undefined4 param_2);  // 0102BF90 slot 0x28  overrides hkSocket
    virtual undefined4 vf2C();  // 0102C0F0 slot 0x2C  overrides hkSocket
    // non-virtual members
    hkBsdSocket(int param_2);  // 0102C0C0
};
