// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkBuiltinTypeRegistry : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf0C() = 0;  // 00FDB68B slot 0xC
    virtual undefined4 vf10() = 0;  // 00FDB68B slot 0x10
    virtual undefined4 vf14() = 0;  // 00FDB68B slot 0x14
    virtual void vf18(int param_1, undefined4 param_2);  // 010D9680 slot 0x18
    virtual void vf1C() = 0;  // 00FDB68B slot 0x1C
};
