// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkDataRefCounted {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int vf00(byte param_2);  // 010E34D0 slot 0x0
    // non-virtual members
    hkDataRefCounted();  // 010E4480
    void ctor_010EB490();  // 010EB490
    void ctor_010F0480();  // 010F0480
    void ctor_010F0990();  // 010F0990
    void ctor_010F0A90();  // 010F0A90
    void ctor_010F0B90();  // 010F0B90
    void ctor_010F0C90();  // 010F0C90
    void ctor_010F0D90();  // 010F0D90
    void ctor_010F23E0();  // 010F23E0
    void ctor_010F26D0();  // 010F26D0
    void ctor_010F2820();  // 010F2820
    void ctor_010F2940();  // 010F2940
    void ctor_010F2AC0();  // 010F2AC0
    void ctor_010F2C60();  // 010F2C60
    void ctor_010F3570();  // 010F3570
    void ctor_010F3630();  // 010F3630
    void ctor_010F4410();  // 010F4410
};
