// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkDataRefCounted.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkDataClassImpl : public hkDataRefCounted {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int vf00(byte param_2);  // 010E36D0 slot 0x0  overrides hkDataRefCounted
    virtual undefined4 vf04() = 0;  // 00FDB68B slot 0x4
    virtual undefined4 vf08() = 0;  // 00FDB68B slot 0x8
    virtual undefined4 vf0C() = 0;  // 00FDB68B slot 0xC
    virtual undefined4 vf10() = 0;  // 00FDB68B slot 0x10
    virtual void vf14(undefined1 * param_2, int * param_3) = 0;  // 00FDB68B slot 0x14
    virtual undefined4 vf18() = 0;  // 00FDB68B slot 0x18
    virtual void vf1C(int param_2, undefined4 * param_3) = 0;  // 00FDB68B slot 0x1C
    virtual int vf20(int param_2) = 0;  // 00FDB68B slot 0x20
    virtual int vf24() = 0;  // 00FDB68B slot 0x24
    virtual void vf28(int param_2, undefined4 * param_3) = 0;  // 00FDB68B slot 0x28
    virtual int vf2C(int param_2) = 0;  // 00FDB68B slot 0x2C
    virtual void vf30(int * param_2) = 0;  // 00FDB68B slot 0x30
};
