// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "HkDataManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct HkDataManagerImplement : public HkDataManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0092EBF0 slot 0x0  overrides HkDataManager
    virtual void vf04();  // 0092D810 slot 0x4  overrides HkDataManager
    virtual void vf08();  // 0092D0F0 slot 0x8  overrides HkDataManager
    virtual undefined4 vf0C();  // 0092D910 slot 0xC  overrides HkDataManager
    virtual void vf10();  // 0092D110 slot 0x10  overrides HkDataManager
    virtual undefined4 vf14(undefined4 * param_1);  // 0092D1A0 slot 0x14  overrides HkDataManager
    virtual undefined4 vf18(int param_1);  // 0092D1F0 slot 0x18  overrides HkDataManager
};
