// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkOstream.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkErrStream : public hkOstream {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0100B380 slot 0x0  overrides hkBaseObject
    // non-virtual members
    hkErrStream(int param_2, int param_3);  // 0100B1B0
    static undefined * vf08();  // 01019000
};
