// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkError : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf0C() = 0;  // 00FDB68B slot 0xC
    virtual void vf10(undefined4 param_1, char param_2) = 0;  // 00FDB68B slot 0x10
    virtual void vf14(undefined4 param_1, undefined4 param_2) = 0;  // 00FDB68B slot 0x14
    virtual void vf18() = 0;  // 00FDB68B slot 0x18
    virtual void vf1C(undefined4 param_2);  // 0101A040 slot 0x1C
    virtual void vf20();  // 0101A050 slot 0x20
};
