// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkIstream : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01442670 slot 0x0  overrides hkBaseObject
    // non-virtual members
    hkIstream(undefined4 param_2);  // 01441B50
    void ctor_014420B0(undefined4 param_2);  // 014420B0
    hkIstream();  // 01442280
    void ctor_014422E0(undefined4 param_2);  // 014422E0
};
