// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkJobThreadPool : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010117F0 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 param_2) = 0;  // 00FDB68B slot 0xC
    virtual void vf10() = 0;  // 00FDB68B slot 0x10
    virtual bool vf14() = 0;  // 00FDB68B slot 0x14
    virtual undefined4 vf18() = 0;  // 00FDB68B slot 0x18
    virtual void vf1C(int param_2) = 0;  // 00FDB68B slot 0x1C
    virtual void vf20(int * param_2, undefined4 param_3) = 0;  // 00FDB68B slot 0x20
    virtual void vf24() = 0;  // 00FDB68B slot 0x24
};
