// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkStreamReader.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkLineNumberStreamReader : public hkStreamReader {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0143ED20 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined1 * param_2);  // 0143EC10 slot 0xC  overrides hkStreamReader
    virtual int vf10(int param_2, int param_3);  // 0143EBC0 slot 0x10  overrides hkStreamReader
    virtual void vf18(undefined4 param_2);  // 0143EC30 slot 0x18  overrides hkStreamReader
    virtual bool vf1C(int param_2);  // 0143EC50 slot 0x1C  overrides hkStreamReader
    virtual undefined4 vf20();  // 0143EC80 slot 0x20  overrides hkStreamReader
    // non-virtual members
    hkLineNumberStreamReader();  // 0143ECA0
};
