// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkMemoryAllocator.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkMallocAllocator : public hkMemoryAllocator {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00();  // 00930730 slot 0x0  overrides hkMemoryAllocator
    virtual int vf04(int param_2);  // 010133D0 slot 0x4  overrides hkMemoryAllocator
    virtual void vf08(int param_2, int param_3);  // 01013410 slot 0x8  overrides hkMemoryAllocator
    virtual void vf20();  // 01013440 slot 0x20  overrides hkMemoryAllocator
    virtual void vf24();  // 01013470 slot 0x24  overrides hkMemoryAllocator
    virtual void vf28();  // 01013460 slot 0x28  overrides hkMemoryAllocator
};
