// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkMeshBody : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0106DB20 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf0C() = 0;  // 00FDB68B slot 0xC
    virtual void vf10(undefined4 * param_2) = 0;  // 00FDB68B slot 0x10
    virtual void vf14(undefined4 * param_2) = 0;  // 00FDB68B slot 0x14
    virtual undefined4 vf18(int param_2) = 0;  // 00FDB68B slot 0x18
    virtual undefined4 vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual void vf20() = 0;  // 00FDB68B slot 0x20
    virtual void vf24() = 0;  // 00FDB68B slot 0x24
    virtual void vf28() = 0;  // 00FDB68B slot 0x28
    virtual undefined4 vf2C();  // 0106D8D0 slot 0x2C
    virtual undefined4 vf30();  // 0106D8E0 slot 0x30
    virtual undefined4 vf34();  // 0106D8F0 slot 0x34
    virtual undefined4 vf38();  // 0106D900 slot 0x38
    virtual undefined4 vf3C();  // 0106D910 slot 0x3C
    virtual void vf40() = 0;  // 00FDB68B slot 0x40
    virtual void vf44() = 0;  // 00FDB68B slot 0x44
    virtual uint vf48();  // 0106D920 slot 0x48
    virtual void vf4C();  // 0106D930 slot 0x4C
};
