// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkMemorySystem {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00();  // 010110B0 slot 0x0
    virtual int * vf04(int * param_2, uint param_3) = 0;  // 00FDB68B slot 0x4
    virtual undefined4 vf08(uint param_2) = 0;  // 00FDB68B slot 0x8
    virtual void vf0C(int param_2, undefined4 param_3, byte param_4) = 0;  // 00FDB68B slot 0xC
    virtual void vf10(int param_1, byte param_2) = 0;  // 00FDB68B slot 0x10
    virtual undefined4 vf14();  // 01010FB0 slot 0x14
    virtual undefined4 vf18();  // 01010FC0 slot 0x18
    virtual undefined1 vf1C();  // 01010FD0 slot 0x1C
    virtual undefined1 vf20();  // 01010FE0 slot 0x20
    virtual void vf24(undefined4 param_2) = 0;  // 00FDB68B slot 0x24
    virtual undefined4 vf28() = 0;  // 00FDB68B slot 0x28
    virtual void vf2C() = 0;  // 00FDB68B slot 0x2C
    virtual undefined4 vf30() = 0;  // 00FDB68B slot 0x30
    virtual void vf34();  // 01010F90 slot 0x34
    virtual void vf38();  // 01010FA0 slot 0x38
    virtual void vf3C();  // 01010FF0 slot 0x3C
    virtual void vf40();  // 01011030 slot 0x40
    virtual undefined4 vf44();  // 01011040 slot 0x44
    virtual undefined4 vf48();  // 01011050 slot 0x48
    virtual void vf4C();  // 01011060 slot 0x4C
    virtual void vf50();  // 01011070 slot 0x50
    virtual void vf54();  // 01011080 slot 0x54
    virtual undefined4 vf58();  // 01011090 slot 0x58
    virtual undefined4 vf5C();  // 010110A0 slot 0x5C
    // non-virtual members
    ~hkMemorySystem();  // 01010F80
};
