// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkMeshTexture : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01064F20 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C() = 0;  // 00FDB68B slot 0xC
    virtual undefined vf10() = 0;  // 00FDB68B slot 0x10
    virtual uint vf14() = 0;  // 00FDB68B slot 0x14
    virtual void vf18() = 0;  // 00FDB68B slot 0x18
    virtual bool vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual void vf20(undefined1 param_2) = 0;  // 00FDB68B slot 0x20
    virtual int vf24() = 0;  // 00FDB68B slot 0x24
    virtual void vf28(undefined1 param_2) = 0;  // 00FDB68B slot 0x28
    virtual int vf2C() = 0;  // 00FDB68B slot 0x2C
    virtual void vf30(undefined1 param_2) = 0;  // 00FDB68B slot 0x30
    virtual undefined4 vf34() = 0;  // 00FDB68B slot 0x34
    virtual void vf38(undefined4 param_2) = 0;  // 00FDB68B slot 0x38
};
