// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkMemoryAllocator {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00();  // 0092FB00 slot 0x0
    virtual int vf04(int param_2) = 0;  // 00FDB68B slot 0x4
    virtual void vf08(int param_2, int param_3) = 0;  // 00FDB68B slot 0x8
    virtual void vf0C();  // 0100EE60 slot 0xC
    virtual void vf10();  // 0100EE80 slot 0x10
    virtual void vf14();  // 0100EF10 slot 0x14
    virtual void vf18(int param_2, int param_3, undefined4 param_4);  // 0100EE90 slot 0x18
    virtual void vf1C(int param_2, int param_3, undefined4 param_4);  // 0100EEC0 slot 0x1C
    virtual void vf20() = 0;  // 00FDB68B slot 0x20
    virtual void vf24() = 0;  // 00FDB68B slot 0x24
    virtual void vf28();  // 0092FAE0 slot 0x28
    // non-virtual members
    ~hkMemoryAllocator();  // 0100EE50
};
