// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkMeshShape : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0106B410 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf0C() = 0;  // 00FDB68B slot 0xC
    virtual void vf10(int param_2, byte param_3, undefined1 * param_4) = 0;  // 00FDB68B slot 0x10
    virtual void vf14() = 0;  // 00FDB68B slot 0x14
    virtual uint vf18();  // 0106B210 slot 0x18
    virtual void vf1C();  // 0106B220 slot 0x1C
};
