// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkFileSystem.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkNativeFileSystem : public hkFileSystem {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    hkNativeFileSystem();  // 0100F210
};
