// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkObjectCopier : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010F73F0 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 010F6F80 slot 0xC
    virtual undefined4 vf10(int param_1, int param_2);  // 010F5760 slot 0x10
    virtual undefined4 vf14(undefined4 param_1);  // 01053B90 slot 0x14
    // non-virtual members
    hkObjectCopier();  // 010F55B0
};
