// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkResource.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkObjectResource : public hkResource {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011198E0 slot 0x0  overrides hkBaseObject
    virtual char * vf0C();  // 01119600 slot 0xC  overrides hkResource
    virtual undefined vf14();  // 01119610 slot 0x14  overrides hkResource
    virtual undefined4 vf18(int param_2);  // 011197E0 slot 0x18  overrides hkResource
    virtual undefined4 vf1C();  // 01119650 slot 0x1C  overrides hkResource
    virtual void vf20(undefined4 param_2, undefined4 param_3);  // 01119620 slot 0x20
    // non-virtual members
    hkObjectResource(undefined4 * param_2);  // 011196C0
};
