// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkObjectWriter : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010F9850 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C() = 0;  // 00FDB68B slot 0xC
    virtual bool vf10(int * param_1, undefined4 param_2, int param_3) = 0;  // 00FDB68B slot 0x10
};
