// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkStreamWriter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkOffsetOnlyStreamWriter : public hkStreamWriter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01445440 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined1 * param_1);  // 014453F0 slot 0xC  overrides hkStreamWriter
    virtual int vf10(undefined4 param_2, int param_3);  // 01445340 slot 0x10  overrides hkStreamWriter
    virtual void vf18(undefined1 * param_1);  // 01445400 slot 0x18  overrides hkStreamWriter
    virtual undefined4 vf1C(int param_2, int param_3);  // 01445370 slot 0x1C  overrides hkStreamWriter
    virtual undefined4 vf20();  // 014453C0 slot 0x20  overrides hkStreamWriter
    // non-virtual members
    hkOffsetOnlyStreamWriter();  // 014453D0
};
