// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpBroadPhase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkp3AxisSweep : public hkpBroadPhase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0114F5C0 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf0C();  // 011417F0 slot 0xC  overrides hkpBroadPhase
    virtual undefined vf14();  // 01142110 slot 0x14  overrides hkpBroadPhase
    virtual void vf18(undefined4 * param_2, uint * param_3, int * param_4);  // 01144D10 slot 0x18  overrides hkpBroadPhase
    virtual void vf1C(int * param_2, int * param_3, undefined4 param_4);  // 01148CE0 slot 0x1C  overrides hkpBroadPhase
    virtual void vf20(uint * param_2, int * param_3);  // 01145030 slot 0x20  overrides hkpBroadPhase
    virtual void vf24(int * param_2, int param_3);  // 01149C00 slot 0x24  overrides hkpBroadPhase
    virtual int vf28();  // 01142200 slot 0x28  overrides hkpBroadPhase
    virtual undefined vf2C();  // 01142B00 slot 0x2C  overrides hkpBroadPhase
    virtual undefined vf30();  // 01143620 slot 0x30  overrides hkpBroadPhase
    virtual void vf34();  // 011469A0 slot 0x34  overrides hkpBroadPhase
    virtual void vf38();  // 01141940 slot 0x38  overrides hkpBroadPhase
    virtual void vf3C(int * param_2);  // 01142A70 slot 0x3C  overrides hkpBroadPhase
    virtual void vf40(int * param_2, undefined4 param_3);  // 01142540 slot 0x40  overrides hkpBroadPhase
    virtual void vf44(float * param_2, float * param_3);  // 01142560 slot 0x44  overrides hkpBroadPhase
    virtual void vf48(float * param_2, int * param_3);  // 011458D0 slot 0x48  overrides hkpBroadPhase
    virtual void vf4C(int * param_2, int * param_3);  // 01144B80 slot 0x4C  overrides hkpBroadPhase
    virtual void vf50(float * param_2, int * param_3);  // 01145E60 slot 0x50  overrides hkpBroadPhase
    virtual uint vf54(int * param_2, int * param_3);  // 01142090 slot 0x54  overrides hkpBroadPhase
    virtual void vf58(ulonglong * param_1, undefined4 * param_2, undefined4 param_3);  // 01147F40 slot 0x58  overrides hkpBroadPhase
    virtual void vf5C(uint * param_2, float * param_3, undefined4 param_4);  // 011425C0 slot 0x5C  overrides hkpBroadPhase
    virtual void vf60(undefined4 * param_2, undefined4 * param_3);  // 0114EEB0 slot 0x60  overrides hkpBroadPhase
    virtual undefined vf64();  // 01146CC0 slot 0x64  overrides hkpBroadPhase
    virtual int vf68();  // 01142210 slot 0x68  overrides hkpBroadPhase
    virtual void vf6C(int * param_2, undefined4 param_3);  // 01146890 slot 0x6C  overrides hkpBroadPhase
    virtual void vf70(float * param_2, undefined4 param_3);  // 01146350 slot 0x70  overrides hkpBroadPhase
    virtual void vf74(float * param_2, int * param_3);  // 011475A0 slot 0x74  overrides hkpBroadPhase
    virtual undefined vf78();  // 011419B0 slot 0x78  overrides hkpBroadPhase
    // non-virtual members
    hkp3AxisSweep();  // 01144680
    ~hkp3AxisSweep();  // 01148BB0
    static uint vf10(uint param_2);  // 0114EE60
};
