// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkResource.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkPackfileData : public hkResource {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010FA980 slot 0x0  overrides hkBaseObject
    virtual char * vf0C();  // 010555B0 slot 0xC  overrides hkResource
    virtual void vf10();  // 010F9B50 slot 0x10  overrides hkResource
    virtual undefined vf14();  // 010F9BF0 slot 0x14  overrides hkResource
    virtual undefined4 vf18(int param_2);  // 010F9DB0 slot 0x18  overrides hkResource
    virtual undefined4 vf1C();  // 010F9A10 slot 0x1C  overrides hkResource
    // non-virtual members
    hkPackfileData(int param_2);  // 010F9EE0
};
