// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpRayHitCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpAllRayHitCollector : public hkpRayHitCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00();  // 0112C0B0 slot 0x0  overrides hkpRayHitCollector
    virtual undefined vf04();  // 005ED9F0 slot 0x4  overrides hkpRayHitCollector
    // non-virtual members
    hkpAllRayHitCollector();  // 005EC620
    void ctor_0089D610();  // 0089D610
    void ctor_008CFE30();  // 008CFE30
    void ctor_008D0070();  // 008D0070
    void ctor_008D1370();  // 008D1370
    void ctor_009105C0();  // 009105C0
    void ctor_009568F0();  // 009568F0
    void ctor_00DC82B0();  // 00DC82B0
};
