// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpBinaryAction.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpAngularDashpotAction : public hkpBinaryAction {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 012764B0 slot 0x0  overrides hkBaseObject
    virtual void vf0C(int param_2);  // 01280E40 slot 0xC  overrides hkpAction
    virtual int vf1C(int * param_2, int param_3);  // 01281090 slot 0x1C  overrides hkpAction
    // non-virtual members
    ~hkpAngularDashpotAction();  // 01280DF0
};
