// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCdBodyPairCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpAllCdBodyPairCollector : public hkpCdBodyPairCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 005E2C70 slot 0x0  overrides hkpCdBodyPairCollector
    virtual void vf04(int param_2, int param_3);  // 0112C280 slot 0x4  overrides hkpCdBodyPairCollector
    virtual void vf08();  // 005DD9B0 slot 0x8  overrides hkpCdBodyPairCollector
};
