// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpPhantom.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpAabbPhantom : public hkpPhantom {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011AD080 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf14();  // 011AD040 slot 0x14  overrides hkpWorldObject
    virtual undefined4 vf18();  // 011AC130 slot 0x18  overrides hkpPhantom
    virtual void vf1C(undefined4 * param_2);  // 011AC140 slot 0x1C  overrides hkpPhantom
    virtual void vf20(undefined4 param_2);  // 011AC920 slot 0x20  overrides hkpPhantom
    virtual void vf24(undefined1 * param_2, int param_3);  // 011AC190 slot 0x24  overrides hkpPhantom
    virtual void vf28(int param_2);  // 011AC680 slot 0x28  overrides hkpPhantom
    virtual void vf2C();  // 011AC980 slot 0x2C  overrides hkpPhantom
    virtual int vf30();  // 011ACB30 slot 0x30  overrides hkpPhantom
    virtual void vf38();  // 011ACA30 slot 0x38  overrides hkpPhantom
    // non-virtual members
    ~hkpAabbPhantom();  // 011AC9D0
    hkpAabbPhantom();  // 011ACA90
    hkpAabbPhantom(undefined4 param_2);  // 011B2570
};
