// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpBvTreeAgent : public hkpCollisionAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0115B400 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 01160830 slot 0xC  overrides hkpCollisionAgent
    virtual undefined vf10();  // 0115F410 slot 0x10  overrides hkpCollisionAgent
    virtual undefined vf14();  // 01160800 slot 0x14  overrides hkpCollisionAgent
    virtual void vf18(int param_2, int param_3);  // 0115F5A0 slot 0x18  overrides hkpCollisionAgent
    virtual void vf1C(undefined4 param_2);  // 0115ECC0 slot 0x1C  overrides hkpCollisionAgent
    virtual undefined vf20();  // 0115EF00 slot 0x20  overrides hkpCollisionAgent
    virtual void vf24(undefined4 param_2);  // 0115ED10 slot 0x24  overrides hkpCollisionAgent
    virtual undefined vf28();  // 0115ED50 slot 0x28  overrides hkpCollisionAgent
    // non-virtual members
    hkpBvTreeAgent(undefined4 param_2);  // 0115F430
    static void vf2C();  // 011644D0
    static void vf30();  // 011644E0
    static void vf34();  // 011644F0
};
