// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConvexShape.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpBoxShape : public hkpConvexShape {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01138E30 slot 0x0  overrides hkBaseObject
    virtual void getAabb(float * param_2, float param_3, float * param_4);  // 011385E0 slot 0x10  overrides hkpShapeBase
    virtual void castRay(undefined1 * param_2, float * param_3, uint * param_4);  // 011388A0 slot 0x14  overrides hkpShapeBase
    virtual void vf20(uint * param_2, float * param_3);  // 01138840 slot 0x20  overrides hkpShapeBase
    virtual void vf24(ushort * param_2, int param_3, float * param_4);  // 011386A0 slot 0x24  overrides hkpShapeBase
    virtual void vf28(undefined4 * param_1);  // 01138690 slot 0x28  overrides hkpShapeBase
    virtual undefined4 vf2C();  // 01138DF0 slot 0x2C  overrides hkpShapeBase
    virtual void vf30(int param_2);  // 011386F0 slot 0x30  overrides hkpShapeBase
    virtual undefined4 vf40();  // 01138DE0 slot 0x40  overrides hkpShape
    virtual void vf44(undefined4 * param_2);  // 011385C0 slot 0x44  overrides hkpConvexShape
    // non-virtual members
    hkpBoxShape(undefined8 * param_2, undefined4 param_3);  // 01138770
    hkpBoxShape(undefined4 param_2);  // 011387E0
};
