// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpBreakableMaterial.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpBreakableMultiMaterial : public hkpBreakableMaterial {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011D8F00 slot 0x0  overrides hkBaseObject
    virtual undefined * vf08();  // 011D7C60 slot 0x8  overrides hkReferencedObject
    virtual void vf0C();  // 011D7CF0 slot 0xC  overrides hkpBreakableMaterial
    virtual undefined4 vf2C();  // 011D7C70 slot 0x2C  overrides hkpBreakableMaterial
    // non-virtual members
    hkpBreakableMultiMaterial();  // 011D7EA0
    void ctor_011D8110();  // 011D8110
};
