// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConvexTransformShapeBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConvexTranslateShape : public hkpConvexTransformShapeBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00914E70 slot 0x0  overrides hkBaseObject
    virtual void getAabb(float * param_2, float param_3, float * param_4);  // 011390E0 slot 0x10  overrides hkpShapeBase
    virtual void castRay(undefined1 * param_2, float * param_3, uint * param_4);  // 011391D0 slot 0x14  overrides hkpShapeBase
    virtual undefined castRayWithCollector();  // 011392E0 slot 0x18  overrides hkpShapeBase
    virtual void vf20(uint * param_2, float * param_3);  // 01138F90 slot 0x20  overrides hkpShapeBase
    virtual void vf24(ushort * param_2, int param_3, float * param_4);  // 01138FD0 slot 0x24  overrides hkpShapeBase
    virtual void vf28(undefined4 * param_1);  // 01139020 slot 0x28  overrides hkpShapeBase
    virtual undefined4 vf2C();  // 009116C0 slot 0x2C  overrides hkpShapeBase
    virtual void vf30(int param_2);  // 01139080 slot 0x30  overrides hkpShapeBase
    virtual int vf38();  // 01138F80 slot 0x38  overrides hkpShape
    virtual float10 getMaximumProjection(float * param_2);  // 01139180 slot 0x3C  overrides hkpShape
    virtual undefined4 vf40();  // 01138F20 slot 0x40  overrides hkpShape
    virtual void vf44(undefined4 * param_2);  // 01139050 slot 0x44  overrides hkpConvexShape
    // non-virtual members
    static undefined1 vf0C();  // 00911680
    hkpConvexTranslateShape();  // 00925920
    void ctor_00927840();  // 00927840
    static undefined4 vf34();  // 0112EDF0
    void ctor_01139150();  // 01139150
    hkpConvexTranslateShape(int * param_1, int * param_2, undefined4 param_3);  // 01150E30
};
