// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConstraintData : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011A4AB0 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 param_2);  // 008FB590 slot 0xC
    virtual float10 vf10();  // 008FB5A0 slot 0x10
    virtual void vf14(int param_2);  // 008FB5B0 slot 0x14
    virtual undefined4 vf18(undefined4 * param_2);  // 008FB5C0 slot 0x18
    virtual undefined4 vf1C(float param_2);  // 008FB5D0 slot 0x1C
    virtual void vf20(byte param_2);  // 008FB5E0 slot 0x20
    virtual byte vf24();  // 008FB5F0 slot 0x24
    virtual void vf28(undefined1 * param_2) = 0;  // 00FDB68B slot 0x28
    virtual undefined4 vf2C() = 0;  // 00FDB68B slot 0x2C
    virtual void vf30(char param_2, undefined4 * param_3) = 0;  // 00FDB68B slot 0x30
    virtual undefined4 vf34(undefined4 param_1);  // 011A5610 slot 0x34
    virtual void vf38(undefined4 param_1, int param_2, undefined4 param_3);  // 011A55F0 slot 0x38
    virtual void vf3C(undefined4 * param_1, undefined4 * param_2);  // 011A46D0 slot 0x3C
    virtual void vf40(undefined1 * param_1);  // 008FB600 slot 0x40
    virtual void vf44(int param_2, int param_3);  // 008FB610 slot 0x44
    virtual void vf48(undefined4 param_2) = 0;  // 00FDB68B slot 0x48
};
