// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpRayHitCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpClosestRayHitCollector : public hkpRayHitCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00();  // 0114F770 slot 0x0  overrides hkpRayHitCollector
    virtual undefined vf04();  // 00933670 slot 0x4  overrides hkpRayHitCollector
    // non-virtual members
    hkpClosestRayHitCollector();  // 00933140
    hkpClosestRayHitCollector(int * param_1, int * param_2, int * param_3);  // 0121DDC0
    void ctor_0127EBB0();  // 0127EBB0
};
