// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCharacterControllerCinfo.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpCharacterRigidBodyCinfo : public hkpCharacterControllerCinfo {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 008E30A0 slot 0x0  overrides hkBaseObject
    // non-virtual members
    hkpCharacterRigidBodyCinfo();  // 008E2FE0
    hkpCharacterRigidBodyCinfo(undefined4 * param_1);  // 01276210
};
