// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConstraintOwner : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011CF350 slot 0x0  overrides hkBaseObject
    virtual void vf0C();  // 011CEBC0 slot 0xC
    virtual void vf10();  // 011CEBD0 slot 0x10
    virtual void vf14();  // 011CEBE0 slot 0x14
    virtual void vf18();  // 011CEBF0 slot 0x18
};
