// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConvexVerticesConnectivity : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0113CB30 slot 0x0  overrides hkBaseObject
    virtual void vf0C();  // 0114FF10 slot 0xC
    // non-virtual members
    hkpConvexVerticesConnectivity();  // 0113C420
    ~hkpConvexVerticesConnectivity();  // 011410E0
    void ctor_01141100();  // 01141100
    void ctor_0117A310();  // 0117A310
    void ctor_0117AF50();  // 0117AF50
};
