// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConstraintData.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpCogWheelConstraintData : public hkpConstraintData {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011B07D0 slot 0x0  overrides hkBaseObject
    virtual void vf28(undefined1 * param_2);  // 011DC1B0 slot 0x28  overrides hkpConstraintData
    virtual undefined4 vf2C();  // 011DC160 slot 0x2C  overrides hkpConstraintData
    virtual void vf30(char param_2, undefined4 * param_3);  // 011DC190 slot 0x30  overrides hkpConstraintData
    virtual void vf48(undefined4 param_2);  // 011DC170 slot 0x48  overrides hkpConstraintData
    // non-virtual members
    hkpCogWheelConstraintData(undefined4 * param_1);  // 011B0740
};
