// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpCdPointCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0041F710 slot 0x0
    virtual void vf04(int param_1) = 0;  // 00FDB68B slot 0x4
    virtual void vf08();  // 0041C1A0 slot 0x8
    // non-virtual members
    hkpCdPointCollector();  // 004388C0
    void ctor_00499800();  // 00499800
    void ctor_004D9BD0();  // 004D9BD0
    void ctor_004D9DF0();  // 004D9DF0
    void ctor_004EBBE0();  // 004EBBE0
    void ctor_005177D0();  // 005177D0
    hkpCdPointCollector(int param_2);  // 00615460
    void ctor_006D5660();  // 006D5660
    void ctor_006E8F80();  // 006E8F80
    void ctor_007C9470();  // 007C9470
    void ctor_007EE850();  // 007EE850
    void ctor_00807510();  // 00807510
    void ctor_008EA0C0();  // 008EA0C0
    void ctor_008EABC0();  // 008EABC0
    void ctor_008EAC10();  // 008EAC10
    void ctor_008EAF70();  // 008EAF70
    void ctor_008EB310();  // 008EB310
    void ctor_0090E510();  // 0090E510
    void ctor_0090E620();  // 0090E620
    void ctor_00A89390();  // 00A89390
    void ctor_00AC13C0();  // 00AC13C0
    void ctor_00D7C2B0();  // 00D7C2B0
    void ctor_00D7C3C0();  // 00D7C3C0
};
