// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpContactListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00(int * param_2);  // 00911890 slot 0x0
    virtual void vf04();  // 009118A0 slot 0x4
    virtual void vf08();  // 009118B0 slot 0x8
    virtual undefined4 * vf0C(byte param_2);  // 00911900 slot 0xC
    virtual void vf10(int * param_1);  // 009118D0 slot 0x10
    virtual void vf14();  // 009118E0 slot 0x14
    virtual void contactProcessCallback();  // 009118F0 slot 0x18
    // non-virtual members
    hkpContactListener();  // 0127C3F0
};
