// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpMotion.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpCharacterMotion : public hkpMotion {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01191970 slot 0x0  overrides hkBaseObject
    virtual void vf14(float * param_2);  // 011C7EF0 slot 0x14  overrides hkpMotion
    virtual void vf18(float * param_2);  // 011C7F60 slot 0x18  overrides hkpMotion
    virtual void vf1C(float * param_2);  // 011C7FA0 slot 0x1C  overrides hkpMotion
    virtual void vf20(undefined4 * param_2);  // 011C8000 slot 0x20  overrides hkpMotion
    virtual void vf24(undefined4 * param_2);  // 011C8040 slot 0x24  overrides hkpMotion
    virtual void vf28();  // 011C8070 slot 0x28  overrides hkpMotion
    virtual undefined vf48();  // 011C8210 slot 0x48  overrides hkpMotion
    virtual undefined vf4C();  // 011C82A0 slot 0x4C  overrides hkpMotion
    virtual void vf54(float * param_2, float * param_3);  // 011C8160 slot 0x54  overrides hkpMotion
    virtual void vf58(float * param_2);  // 011C80A0 slot 0x58  overrides hkpMotion
    virtual void vf5C(float param_2, float * param_3, undefined4 param_4);  // 011C80D0 slot 0x5C  overrides hkpMotion
    virtual void vf60(float param_2, float * param_3);  // 011C81D0 slot 0x60  overrides hkpMotion
    virtual void vf64(float param_2, float * param_3);  // 011C8120 slot 0x64  overrides hkpMotion
    // non-virtual members
    hkpCharacterMotion();  // 011A0C20
};
