// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpPredGskfAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConvexListAgent : public hkpPredGskfAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01166B60 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 01165B40 slot 0xC  overrides hkpCollisionAgent
    virtual undefined vf10();  // 01165A40 slot 0x10  overrides hkpCollisionAgent
    virtual undefined vf14();  // 01165C70 slot 0x14  overrides hkpCollisionAgent
    virtual void vf18(int param_2, int param_3);  // 01165E40 slot 0x18  overrides hkpCollisionAgent
    virtual void vf1C(undefined4 param_2);  // 01165720 slot 0x1C  overrides hkpCollisionAgent
    virtual undefined vf20();  // 01165830 slot 0x20  overrides hkpCollisionAgent
    virtual void vf24(undefined4 param_2);  // 011655F0 slot 0x24  overrides hkpCollisionAgent
    virtual undefined vf28();  // 01165620 slot 0x28  overrides hkpCollisionAgent
    virtual void vf2C();  // 01165680 slot 0x2C  overrides hkpCollisionAgent
    virtual void vf30();  // 011656A0 slot 0x30  overrides hkpCollisionAgent
    virtual void vf34();  // 011656C0 slot 0x34  overrides hkpCollisionAgent
    // non-virtual members
    hkpConvexListAgent();  // 01165790
};
