// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpSimulation.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpContinuousSimulation : public hkpSimulation {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011BD4B0 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf18();  // 011BB160 slot 0x18  overrides hkpSimulation
    virtual undefined vf30();  // 011B7850 slot 0x30  overrides hkpSimulation
    virtual void vf34();  // 011B6CD0 slot 0x34  overrides hkpSimulation
    virtual void vf38(int param_2);  // 011B6E50 slot 0x38  overrides hkpSimulation
    virtual void vf3C();  // 011B6CF0 slot 0x3C  overrides hkpSimulation
    virtual undefined vf40();  // 011B9FB0 slot 0x40  overrides hkpSimulation
    virtual void vf44(undefined8 * param_2);  // 011BA170 slot 0x44  overrides hkpSimulation
    virtual void vf48(float param_2);  // 011B6D00 slot 0x48  overrides hkpSimulation
    virtual void vf4C(int * param_1, int param_2, int * param_3);  // 011B89D0 slot 0x4C
    virtual void vf50(int * param_2, int * param_3);  // 011B8D70 slot 0x50
    virtual undefined vf54();  // 011BB240 slot 0x54
    // non-virtual members
    hkpContinuousSimulation();  // 011B8230
    ~hkpContinuousSimulation();  // 011B82D0
};
