// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConstraintMotor : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011A9C80 slot 0x0  overrides hkBaseObject
    virtual void vf0C() = 0;  // 00FDB68B slot 0xC
    // non-virtual members
    hkpConstraintMotor(int param_2);  // 011A9A70
    void ctor_011A9C10(int param_2);  // 011A9C10
    void ctor_011A9DA0(int param_2);  // 011A9DA0
    void ctor_011DCC20(int param_2);  // 011DCC20
    void ctor_011DD370(int param_2);  // 011DD370
    void ctor_011DFE00(int param_2);  // 011DFE00
};
