// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCdPointCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpClosestCdPointCollector : public hkpCdPointCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01166DD0 slot 0x0  overrides hkpCdPointCollector
    virtual void vf04(int param_1);  // 011837A0 slot 0x4  overrides hkpCdPointCollector
    virtual void vf08();  // 011668B0 slot 0x8  overrides hkpCdPointCollector
    // non-virtual members
    hkpClosestCdPointCollector();  // 01165890
    void ctor_01183BF0();  // 01183BF0
    void ctor_0127F670();  // 0127F670
};
