// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionFilter.h"
#include "hkpConstraintListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConstrainedSystemFilter : public hkpCollisionFilter, public hkpConstraintListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf00();  // 01276110
    static void vf0C();  // 01276120
    static void vf04();  // 01276130
    static void vf00_01276140();  // 01276140
    static void vf00_01276150();  // 01276150
    static undefined vf04_01280430();  // 01280430
    static undefined vf04_01280510();  // 01280510
    static undefined vf00_01280560();  // 01280560
    static undefined vf00_012805C0();  // 012805C0
    static undefined vf04_01280610();  // 01280610
    static void vf04_01280650(int param_1);  // 01280650
    static void vf08();  // 01280690
};
