// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpContactMgr : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011650E0 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C() = 0;  // 00FDB68B slot 0xC
    virtual void vf10() = 0;  // 00FDB68B slot 0x10
    virtual void vf14() = 0;  // 00FDB68B slot 0x14
    virtual void vf18() = 0;  // 00FDB68B slot 0x18
    virtual undefined vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual void vf20() = 0;  // 00FDB68B slot 0x20
    virtual void vf24();  // 01164E30 slot 0x24
    // non-virtual members
    hkpContactMgr(undefined4 param_2);  // 01164E10
};
