// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "hkpEntityListener.h"
#include "hkpWorldPostSimulationListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpCharacterRigidBody : public hkReferencedObject, public hkpEntityListener, public hkpWorldPostSimulationListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf0C(undefined4 param_2, int * param_3);  // 0126F730 slot 0xC
    virtual undefined4 vf10(int param_1, int * param_2);  // 0126FA60 slot 0x10
    virtual void vf14(int * param_2, char param_3, int param_4);  // 0126F540 slot 0x14
    // non-virtual members
    static void vf00();  // 01270840
    static void vf00_01270850();  // 01270850
};
