// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "hkpCollidableCollidableFilter.h"
#include "hkpShapeCollectionFilter.h"
#include "hkpRayShapeCollectionFilter.h"
#include "hkpRayCollidableFilter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpCollisionFilter : public hkReferencedObject, public hkpCollidableCollidableFilter, public hkpShapeCollectionFilter, public hkpRayShapeCollectionFilter, public hkpRayCollidableFilter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf0C();  // 008FD6B0 slot 0xC
    // non-virtual members
    hkpCollisionFilter();  // 01132860
    static void vf00();  // 011328D0
    static void vf0C_011328E0();  // 011328E0
    static void vf04();  // 011328F0
    static void vf00_01132900();  // 01132900
};
