// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpCdBodyPairCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 005DC0F0 slot 0x0
    virtual void vf04(int param_2, int param_3) = 0;  // 00FDB68B slot 0x4
    virtual void vf08();  // 005D9020 slot 0x8
    // non-virtual members
    hkpCdBodyPairCollector();  // 005E1820
    void ctor_00906720();  // 00906720
};
