// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConstraintInstance.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConstraintChainInstance : public hkpConstraintInstance {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011A9A10 slot 0x0  overrides hkBaseObject
    virtual void vf10(int param_2);  // 011A96D0 slot 0x10  overrides hkpConstraintInstance
    virtual undefined4 vf18();  // 011A99D0 slot 0x18  overrides hkpConstraintInstance
    // non-virtual members
    ~hkpConstraintChainInstance();  // 011A9830
};
