// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpSphereRepShape.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpConvexShape : public hkpSphereRepShape {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00914B70 slot 0x0  overrides hkBaseObject
    virtual undefined1 vf0C();  // 00911680 slot 0xC  overrides hkpShapeBase
    virtual undefined castRayWithCollector();  // 0112EEB0 slot 0x18  overrides hkpShapeBase
    virtual void vf28(undefined4 * param_1);  // 0112EE30 slot 0x28  overrides hkpShapeBase
    virtual undefined4 vf34();  // 0112EDF0 slot 0x34  overrides hkpShapeBase
    virtual float10 getMaximumProjection(float * param_2);  // 0112EFB0 slot 0x3C  overrides hkpShape
    virtual void vf44(undefined4 * param_2) = 0;  // 00FDB68B slot 0x44
    // non-virtual members
    hkpConvexShape(undefined4 param_2);  // 0112EE90
};
