// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionFilter.h"
#include "hkpEntityListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpDisableEntityCollisionFilter : public hkpCollisionFilter, public hkpEntityListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf00();  // 01275DF0
    static void vf0C();  // 01275E00
    static void vf04();  // 01275E10
    static void vf00_01275E20();  // 01275E20
    static void vf00_01275E30();  // 01275E30
    static void vf04_0127FCB0(undefined1 * param_1);  // 0127FCB0
    static void vf00_0127FCC0(undefined1 * param_1);  // 0127FCC0
    static void vf00_0127FCD0(undefined1 * param_1);  // 0127FCD0
    static void vf04_0127FCE0(undefined1 * param_1);  // 0127FCE0
    static void vf14();  // 0127FCF0
    static undefined vf04_0127FD00();  // 0127FD00
    static void vf08(int param_2);  // 0127FDB0
};
