// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpWorldMaintenanceMgr.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpDefaultWorldMaintenanceMgr : public hkpWorldMaintenanceMgr {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011D13D0 slot 0x0  overrides hkBaseObject
    virtual void vf0C(int param_2);  // 011D11B0 slot 0xC  overrides hkpWorldMaintenanceMgr
    virtual void vf10(undefined4 param_2, float * param_3);  // 011D1200 slot 0x10  overrides hkpWorldMaintenanceMgr
    virtual void vf14(undefined4 param_2, float * param_3);  // 011D12D0 slot 0x14  overrides hkpWorldMaintenanceMgr
    // non-virtual members
    hkpDefaultWorldMaintenanceMgr();  // 011D11D0
};
