// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpContactMgr.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpDynamicsContactMgr : public hkpContactMgr {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011CD0B0 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf28();  // 011CC910 slot 0x28
    virtual undefined4 vf2C();  // 011CC920 slot 0x2C
    virtual void vf30();  // 011CC930 slot 0x30
    virtual undefined4 vf34() = 0;  // 00FDB68B slot 0x34
    virtual void vf38();  // 011CC940 slot 0x38
    virtual void vf3C();  // 011CC950 slot 0x3C
    virtual undefined4 vf40();  // 011CC960 slot 0x40
    virtual void vf44(undefined1 * param_1);  // 011CC970 slot 0x44
    virtual void vf48();  // 011CC980 slot 0x48
    // non-virtual members
    hkpDynamicsContactMgr(undefined4 param_2);  // 011CC8F0
};
