// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConvexListFilter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpDefaultConvexListFilter : public hkpConvexListFilter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01140F80 slot 0x0  overrides hkBaseObject
    virtual uint vf0C(undefined4 param_1, int * param_2, int * param_3);  // 01158980 slot 0xC  overrides hkpConvexListFilter
    // non-virtual members
    ~hkpDefaultConvexListFilter();  // 01140EA0
    hkpDefaultConvexListFilter();  // 01140ED0
    void ctor_01198290();  // 01198290
};
