// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "hkpBroadPhaseListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpEntityEntityBroadPhaseListener : public hkReferencedObject, public hkpBroadPhaseListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf04(int * param_2);  // 011D1E70
    static void vf08(int * param_1);  // 011D1ED0
    static void vf00();  // 011D1F20
};
