// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpWorldObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpEntity : public hkpWorldObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011922C0 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf14();  // 01192280 slot 0x14  overrides hkpWorldObject
    virtual void vf18();  // 011902D0 slot 0x18
    // non-virtual members
    ~hkpEntity();  // 011909D0
};
