// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "hkpWorldPostSimulationListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpEndOfStepCallbackUtil : public hkReferencedObject, public hkpWorldPostSimulationListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf04();  // 011D0220
    static void vf00();  // 011D0DB0
};
