// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpEntityListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 008F7CE0 slot 0x0
    virtual void vf04();  // 008E1590 slot 0x4
    virtual void vf08();  // 008F7CD0 slot 0x8
    virtual void vf0C(int param_2);  // 008E15A0 slot 0xC
    virtual void vf10();  // 008E15D0 slot 0x10
    virtual void vf14(undefined4 param_1);  // 008E15E0 slot 0x14
    // non-virtual members
    hkpEntityListener();  // 0091F310
    void ctor_0091F420();  // 0091F420
    hkpEntityListener(int param_2);  // 0126F810
    hkpEntityListener(undefined4 * param_1);  // 01275D20
    void ctor_01279460();  // 01279460
    void ctor_01279B50(int param_2);  // 01279B50
    void ctor_0127FDF0();  // 0127FDF0
};
