// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpRayHitCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpFixedBufferRayHitCollector : public hkpRayHitCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00();  // 01474C30 slot 0x0  overrides hkpRayHitCollector
    virtual undefined vf04();  // 01474C80 slot 0x4  overrides hkpRayHitCollector
    // non-virtual members
    hkpFixedBufferRayHitCollector();  // 01474BF0
    void ctor_01475010();  // 01475010
};
