// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpKeyframedRigidMotion.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpFixedRigidMotion : public hkpKeyframedRigidMotion {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01191680 slot 0x0  overrides hkBaseObject
    virtual void vf40();  // 011C70F0 slot 0x40  overrides hkpMotion
    virtual void vf44();  // 011C7100 slot 0x44  overrides hkpMotion
    virtual void vf6C();  // 011C70E0 slot 0x6C  overrides hkpKeyframedRigidMotion
    virtual void vf74(int param_2);  // 011C7140 slot 0x74
    // non-virtual members
    hkpFixedRigidMotion();  // 011C7110
};
