// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCdBodyPairCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpFirstCdBodyPairCollector : public hkpCdBodyPairCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00906630 slot 0x0  overrides hkpCdBodyPairCollector
    virtual void vf04(int param_2, int param_3);  // 01138E70 slot 0x4  overrides hkpCdBodyPairCollector
    // non-virtual members
    hkpFirstCdBodyPairCollector();  // 00907F20
    void ctor_0090DC80();  // 0090DC80
    void ctor_00965120();  // 00965120
};
