// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpGskBaseAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpGskfAgent : public hkpGskBaseAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01183750 slot 0x0  overrides hkBaseObject
    virtual void vf18(int param_2, int param_3);  // 01183530 slot 0x18  overrides hkpCollisionAgent
    virtual void vf1C(undefined4 param_2);  // 011832A0 slot 0x1C  overrides hkpCollisionAgent
    virtual void vf2C();  // 011832D0 slot 0x2C  overrides hkpCollisionAgent
    virtual void vf30();  // 01183310 slot 0x30  overrides hkpCollisionAgent
    virtual void vf34();  // 01183350 slot 0x34  overrides hkpCollisionAgent
    // non-virtual members
    hkpGskfAgent();  // 01183390
};
