// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionFilter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpGroupFilter : public hkpCollisionFilter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf10();  // 008FD6C0 slot 0x10
    // non-virtual members
    hkpGroupFilter();  // 011323C0
    static undefined4 vf04(undefined4 param_1, int param_2, int param_3);  // 011324C0
    static undefined4 vf04_01132570(undefined4 param_1, int param_2, int param_3);  // 01132570
    static void vf04_01132760();  // 01132760
    static void vf00();  // 01132770
    static void vf00_01132780();  // 01132780
    static void vf0C();  // 01132790
};
