// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpIterativeLinearCastAgent : public hkpCollisionAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0116A2F0 slot 0x0  overrides hkBaseObject
    virtual undefined vf14();  // 01183860 slot 0x14  overrides hkpCollisionAgent
    // non-virtual members
    hkpIterativeLinearCastAgent();  // 0116A2A0
};
