// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpShapeCollection.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpListShape : public hkpShapeCollection {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static undefined4 vf14(int param_2);  // 0113B7D0
    static undefined4 vf10(int param_2);  // 0113B7F0
    hkpListShape(int param_2);  // 0113BCA0
    hkpListShape();  // 0113BEF0
    static void vf00();  // 0113C2C0
    static int vf04();  // 0113C300
    static uint vf0C(uint param_2);  // 0113C310
    static uint vf08();  // 0113C350
    static void vf48();  // 0114F850
    static void vf44();  // 0114F860
};
