// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpBreakableMultiMaterial.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpListShapeBreakableMaterial : public hkpBreakableMultiMaterial {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011DE140 slot 0x0  overrides hkBaseObject
    virtual undefined * vf08();  // 011DDE50 slot 0x8  overrides hkReferencedObject
    virtual void vf10();  // 011DE020 slot 0x10  overrides hkpBreakableMaterial
    virtual void vf14();  // 011DDE60 slot 0x14  overrides hkpBreakableMaterial
    virtual undefined4 vf18();  // 011DDE90 slot 0x18  overrides hkpBreakableMaterial
    virtual undefined4 vf1C();  // 011DDEB0 slot 0x1C  overrides hkpBreakableMaterial
    virtual void vf28();  // 011DDEE0 slot 0x28  overrides hkpBreakableMaterial
    virtual void vf30();  // 011DDE70 slot 0x30  overrides hkpBreakableMaterial
    virtual void vf34();  // 011DDF50 slot 0x34  overrides hkpBreakableMaterial
    // non-virtual members
    hkpListShapeBreakableMaterial();  // 011DDFE0
    ~hkpListShapeBreakableMaterial();  // 011DE000
    void ctor_011DE050();  // 011DE050
};
