// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkObjectWriter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkPlatformObjectWriter : public hkObjectWriter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01113990 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 011135A0 slot 0xC  overrides hkObjectWriter
    virtual bool vf10(int * param_1, undefined4 param_2, int param_3);  // 011134D0 slot 0x10  overrides hkObjectWriter
    // non-virtual members
    hkPlatformObjectWriter();  // 011137C0
};
