// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConstraintData.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpLimitedHingeConstraintData : public hkpConstraintData {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011A7E50 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 param_2);  // 011A7550 slot 0xC  overrides hkpConstraintData
    virtual float10 vf10();  // 011A7570 slot 0x10  overrides hkpConstraintData
    virtual void vf14(int param_2);  // 011A7750 slot 0x14  overrides hkpConstraintData
    virtual undefined4 vf18(undefined4 * param_2);  // 011A7790 slot 0x18  overrides hkpConstraintData
    virtual undefined4 vf1C(float param_2);  // 011A78B0 slot 0x1C  overrides hkpConstraintData
    virtual void vf20(byte param_2);  // 011A7580 slot 0x20  overrides hkpConstraintData
    virtual byte vf24();  // 011A75A0 slot 0x24  overrides hkpConstraintData
    virtual void vf28(undefined1 * param_2);  // 011A76C0 slot 0x28  overrides hkpConstraintData
    virtual undefined4 vf2C();  // 011A7620 slot 0x2C  overrides hkpConstraintData
    virtual void vf30(char param_2, undefined4 * param_3);  // 011A7600 slot 0x30  overrides hkpConstraintData
    virtual void vf48(undefined4 param_2);  // 011A75E0 slot 0x48  overrides hkpConstraintData
    // non-virtual members
    hkpLimitedHingeConstraintData();  // 011A77B0
    hkpLimitedHingeConstraintData(undefined4 * param_1);  // 011B0160
};
