// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMoppNodeMgr : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01247650 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 * param_2) = 0;  // 00FDB68B slot 0xC
    virtual int vf10() = 0;  // 00FDB68B slot 0x10
};
