// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpVehicleManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMultithreadedVehicleManager : public hkpVehicleManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01289120 slot 0x0  overrides hkBaseObject
    virtual undefined vf18();  // 01292E50 slot 0x18
    // non-virtual members
    hkpMultithreadedVehicleManager(undefined4 * param_1);  // 012890A0
};
