// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMultiSphereAgent : public hkpCollisionAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011787F0 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 01177C70 slot 0xC  overrides hkpCollisionAgent
    virtual undefined vf10();  // 01177840 slot 0x10  overrides hkpCollisionAgent
    virtual undefined vf14();  // 01177A50 slot 0x14  overrides hkpCollisionAgent
    virtual void vf18(int param_2, int param_3);  // 01177720 slot 0x18  overrides hkpCollisionAgent
    virtual void vf1C(undefined4 param_2);  // 011776E0 slot 0x1C  overrides hkpCollisionAgent
    // non-virtual members
    hkpMultiSphereAgent();  // 01177EA0
};
