// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpMoppSplitter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMoppDefaultSplitter : public hkpMoppSplitter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01247C00 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 * param_2);  // 012466A0 slot 0xC  overrides hkpMoppNodeMgr
    virtual int vf10();  // 012466D0 slot 0x10  overrides hkpMoppNodeMgr
    virtual undefined vf14();  // 01246BE0 slot 0x14  overrides hkpMoppSplitter
    // non-virtual members
    hkpMoppDefaultSplitter();  // 01246100
};
