// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpMoppMediator.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMoppShapeMediator : public hkpMoppMediator {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0120E290 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 param_2, undefined4 param_3);  // 0120DE30 slot 0xC  overrides hkpMoppMediator
    virtual undefined4 vf10();  // 0120DEE0 slot 0x10  overrides hkpMoppMediator
    virtual void vf14(undefined4 * param_2);  // 0120DE60 slot 0x14  overrides hkpMoppMediator
    virtual undefined vf18();  // 0120DF20 slot 0x18  overrides hkpMoppMediator
    virtual undefined vf1C();  // 0120E090 slot 0x1C  overrides hkpMoppMediator
    virtual void vf20(undefined8 * param_1);  // 0120DEB0 slot 0x20  overrides hkpMoppMediator
    virtual undefined4 vf24(undefined4 param_1, undefined4 * param_2);  // 0120DE40 slot 0x24  overrides hkpMoppMediator
    // non-virtual members
    hkpMoppShapeMediator(int * param_2);  // 0120DEF0
};
