// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpUnaryAction.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMouseSpringAction : public hkpUnaryAction {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01274DA0 slot 0x0  overrides hkBaseObject
    virtual void vf0C(int param_2);  // 0127D410 slot 0xC  overrides hkpAction
    virtual void vf18();  // 0127D3A0 slot 0x18  overrides hkpAction
    virtual int vf1C(int * param_2, int param_3);  // 0127DA30 slot 0x1C  overrides hkpAction
    // non-virtual members
    hkpMouseSpringAction(undefined4 * param_1, undefined4 param_2);  // 01274B00
    hkpMouseSpringAction();  // 01274CE0
    void ctor_0127D6E0();  // 0127D6E0
};
