// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpKeyframedRigidMotion.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMaxSizeMotion : public hkpKeyframedRigidMotion {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01191500 slot 0x0  overrides hkBaseObject
    // non-virtual members
    hkpMaxSizeMotion(undefined4 param_2);  // 01190730
    hkpMaxSizeMotion(int param_2);  // 01190870
    hkpMaxSizeMotion();  // 01190FA0
    void ctor_011914C0(int param_2);  // 011914C0
    hkpMaxSizeMotion(undefined4 * param_1, int param_2);  // 011B1430
    void ctor_011B1470();  // 011B1470
    ~hkpMaxSizeMotion();  // 011C3C60
};
