// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpBallGun.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMountedBallGun : public hkpBallGun {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0127E130 slot 0x0  overrides hkBaseObject
    virtual void vf10(int param_2, float * param_3);  // 0127DE00 slot 0x10  overrides hkpFirstPersonGun
    // non-virtual members
    static void vf0C();  // 0127CE80
    hkpMountedBallGun(int param_2);  // 0127DD90
    hkpMountedBallGun();  // 0127DDC0
    static void vf14();  // 0127E0E0
    static uint vf1C();  // 0127F650
    static void vf18();  // 0127F660
    static void vf20(int param_2);  // 012806E0
};
