// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpMoppMediator : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0120E220 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined4 param_2, undefined4 param_3) = 0;  // 00FDB68B slot 0xC
    virtual undefined4 vf10() = 0;  // 00FDB68B slot 0x10
    virtual void vf14(undefined4 * param_2) = 0;  // 00FDB68B slot 0x14
    virtual undefined vf18() = 0;  // 00FDB68B slot 0x18
    virtual undefined vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual void vf20(undefined8 * param_1) = 0;  // 00FDB68B slot 0x20
    virtual undefined4 vf24(undefined4 param_1, undefined4 * param_2) = 0;  // 00FDB68B slot 0x24
};
