// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpNullAgent : public hkpCollisionAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01181C30 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 01181BB0 slot 0xC  overrides hkpCollisionAgent
    virtual undefined vf10();  // 01181BC0 slot 0x10  overrides hkpCollisionAgent
    virtual undefined vf14();  // 01181BD0 slot 0x14  overrides hkpCollisionAgent
    virtual void vf18(int param_2, int param_3);  // 01181BE0 slot 0x18  overrides hkpCollisionAgent
    virtual void vf1C(undefined4 param_2);  // 01181BF0 slot 0x1C  overrides hkpCollisionAgent
    // non-virtual members
    hkpNullAgent();  // 01181B80
};
