// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpWind.h"
#include "hkpWorldPostSimulationListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpPrevailingWind : public hkpWind, public hkpWorldPostSimulationListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf04(int param_2);  // 01268C80
    static void vf00();  // 01269440
};
