// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpFirstPersonGun.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpProjectileGun : public hkpFirstPersonGun {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0127CED0 slot 0x0  overrides hkBaseObject
    virtual void vf10(int param_2, float * param_3);  // 0127C370 slot 0x10  overrides hkpFirstPersonGun
    virtual void vf14();  // 0127C3A0 slot 0x14  overrides hkpFirstPersonGun
    virtual void vf20(int param_2);  // 0127C760 slot 0x20  overrides hkpFirstPersonGun
    virtual void vf24();  // 0127CE90 slot 0x24
    virtual void vf28(undefined4 param_1);  // 0127C730 slot 0x28
    // non-virtual members
    hkpProjectileGun();  // 0127CA00
    hkpProjectileGun(undefined4 param_2);  // 0127CA50
    ~hkpProjectileGun();  // 0127CA80
};
