// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpDynamicsContactMgr.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpReportContactMgr : public hkpDynamicsContactMgr {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011CD410 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 011CCF00 slot 0xC  overrides hkpContactMgr
    virtual void vf10();  // 011CD3B0 slot 0x10  overrides hkpContactMgr
    virtual void vf14();  // 011CCC70 slot 0x14  overrides hkpContactMgr
    virtual void vf18();  // 011CCCF0 slot 0x18  overrides hkpContactMgr
    virtual undefined vf1C();  // 011CCB00 slot 0x1C  overrides hkpContactMgr
    virtual void vf20();  // 011CCBF0 slot 0x20  overrides hkpContactMgr
    virtual void vf24();  // 011CD3C0 slot 0x24  overrides hkpContactMgr
    virtual undefined4 vf34();  // 011CD3D0 slot 0x34  overrides hkpDynamicsContactMgr
    virtual void vf48();  // 011CCDE0 slot 0x48  overrides hkpDynamicsContactMgr
    // non-virtual members
    hkpReportContactMgr();  // 011CCAB0
};
