// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpRemoveTerminalsMoppModifier.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpRemoveTerminalsMoppModifier2 : public hkpRemoveTerminalsMoppModifier {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf04(byte * param_2, int param_3);  // 01157D60
    static void vf00();  // 01158160
};
