// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpUnaryAction.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpReorientAction : public hkpUnaryAction {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01274760 slot 0x0  overrides hkBaseObject
    virtual void vf0C(int param_2);  // 0127C030 slot 0xC  overrides hkpAction
    virtual int vf1C(int * param_2, int param_3);  // 0127BFB0 slot 0x1C  overrides hkpAction
    // non-virtual members
    ~hkpReorientAction();  // 0127BF60
};
