// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpRayHitCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00() = 0;  // 00FDB68B slot 0x0
    virtual undefined vf04();  // 005E9580 slot 0x4
    // non-virtual members
    hkpRayHitCollector();  // 005EC760
    void ctor_0090E3F0();  // 0090E3F0
};
