// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "hkpPhantomOverlapListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpRejectChassisListener : public hkReferencedObject, public hkpPhantomOverlapListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    static void vf08();  // 01286720
    static void vf04();  // 01289160
    static void vf00(int param_2);  // 01289180
};
