// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConstraintChainData.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpStiffSpringChainData : public hkpConstraintChainData {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011D9720 slot 0x0  overrides hkBaseObject
    virtual void vf28(undefined1 * param_2);  // 011D96D0 slot 0x28  overrides hkpConstraintData
    virtual undefined4 vf2C();  // 011D8F70 slot 0x2C  overrides hkpConstraintData
    virtual void vf30(char param_2, undefined4 * param_3);  // 011D8FD0 slot 0x30  overrides hkpConstraintData
    virtual void vf3C(undefined4 * param_1, undefined4 * param_2);  // 011D9160 slot 0x3C  overrides hkpConstraintData
    virtual void vf48(undefined4 param_2);  // 011D8F80 slot 0x48  overrides hkpConstraintData
    virtual undefined4 vf4C();  // 011D9710 slot 0x4C  overrides hkpConstraintChainData
    // non-virtual members
    hkpStiffSpringChainData();  // 011D90D0
};
