// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSerializedDisplayMarkerList : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01274480 slot 0x0  overrides hkBaseObject
    // non-virtual members
    hkpSerializedDisplayMarkerList(undefined4 * param_1);  // 01274240
};
