// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpDynamicsContactMgr.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSimpleConstraintContactMgr : public hkpDynamicsContactMgr {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011CE8B0 slot 0x0  overrides hkBaseObject
    virtual undefined * vf08();  // 011CE830 slot 0x8  overrides hkReferencedObject
    virtual undefined vf0C();  // 011CDB20 slot 0xC  overrides hkpContactMgr
    virtual void vf10();  // 011CD540 slot 0x10  overrides hkpContactMgr
    virtual void vf14();  // 011CD8A0 slot 0x14  overrides hkpContactMgr
    virtual void vf18();  // 011CDE00 slot 0x18  overrides hkpContactMgr
    virtual undefined vf1C();  // 011CD680 slot 0x1C  overrides hkpContactMgr
    virtual void vf20();  // 011CD600 slot 0x20  overrides hkpContactMgr
    virtual void vf24();  // 011CE810 slot 0x24  overrides hkpContactMgr
    virtual undefined4 vf28();  // 011CD990 slot 0x28  overrides hkpDynamicsContactMgr
    virtual undefined4 vf2C();  // 011CD970 slot 0x2C  overrides hkpDynamicsContactMgr
    virtual void vf30();  // 011CDDF0 slot 0x30  overrides hkpDynamicsContactMgr
    virtual undefined4 vf34();  // 011CE820 slot 0x34  overrides hkpDynamicsContactMgr
    virtual void vf38();  // 011CD580 slot 0x38  overrides hkpDynamicsContactMgr
    virtual void vf3C();  // 011CD590 slot 0x3C  overrides hkpDynamicsContactMgr
    virtual undefined4 vf40();  // 011CD520 slot 0x40  overrides hkpDynamicsContactMgr
    virtual void vf44(undefined1 * param_1);  // 011CD9F0 slot 0x44  overrides hkpDynamicsContactMgr
    virtual void vf48();  // 011CDAD0 slot 0x48  overrides hkpDynamicsContactMgr
    virtual int vf4C();  // 011CD530 slot 0x4C
    // non-virtual members
    hkpSimpleConstraintContactMgr();  // 011CDF80
    ~hkpSimpleConstraintContactMgr();  // 011CE060
};
