// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCdPointCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSimpleClosestContactCollector : public hkpCdPointCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01166E90 slot 0x0  overrides hkpCdPointCollector
    virtual void vf04(int param_1);  // 01183FA0 slot 0x4  overrides hkpCdPointCollector
    virtual void vf08();  // 01166AB0 slot 0x8  overrides hkpCdPointCollector
    // non-virtual members
    hkpSimpleClosestContactCollector();  // 01165B60
    void ctor_01179000();  // 01179000
};
