// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpShape.h"
#include "hkpShapeContainer.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpShapeCollection : public hkpShape, public hkpShapeContainer {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf44(int param_2);  // 0114F860 slot 0x44
    virtual void vf48(uint param_2, undefined2 param_3);  // 0114F850 slot 0x48
    // non-virtual members
    static void vf00();  // 0114FE30
};
