// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpShapeContainer.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSingleShapeContainer : public hkpShapeContainer {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00914A20 slot 0x0  overrides hkpShapeContainer
    virtual int vf04();  // 00911470 slot 0x4  overrides hkpShapeContainer
    virtual undefined4 vf08();  // 00911480 slot 0x8  overrides hkpShapeContainer
    virtual undefined4 vf0C();  // 00911490 slot 0xC  overrides hkpShapeContainer
    virtual undefined4 vf14();  // 01138F00 slot 0x14  overrides hkpShapeContainer
    // non-virtual members
    hkpSingleShapeContainer();  // 0112F090
    void ctor_01139450();  // 01139450
    void ctor_0113DFF0();  // 0113DFF0
    ~hkpSingleShapeContainer();  // 0113F0B0
    void ctor_0113F0D0();  // 0113F0D0
    hkpSingleShapeContainer(undefined4 * param_1, int param_2);  // 0113F1D0
    void ctor_0113F2A0();  // 0113F2A0
    void ctor_01157560();  // 01157560
    void ctor_01157B50();  // 01157B50
    void ctor_01159CA0();  // 01159CA0
    void ctor_01159CF0();  // 01159CF0
    void ctor_01237E70();  // 01237E70
};
