// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpLimitedForceConstraintMotor.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSpringDamperConstraintMotor : public hkpLimitedForceConstraintMotor {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011B0DD0 slot 0x0  overrides hkBaseObject
    virtual void vf0C();  // 011DD2E0 slot 0xC  overrides hkpConstraintMotor
    // non-virtual members
    ~hkpSpringDamperConstraintMotor();  // 011B0D50
    hkpSpringDamperConstraintMotor();  // 011B0D70
    void ctor_011DD290();  // 011DD290
    void ctor_011DD370();  // 011DD370
};
