// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCdBodyPairCollector.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSymmetricAgentFlipBodyCollector : public hkpCdBodyPairCollector {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0115B1A0 slot 0x0  overrides hkpCdBodyPairCollector
    virtual void vf04(int param_2, int param_3);  // 011819E0 slot 0x4  overrides hkpCdBodyPairCollector
    // non-virtual members
    hkpSymmetricAgentFlipBodyCollector();  // 0115ABC0
    void ctor_0115AF10();  // 0115AF10
    void ctor_0115B5C0();  // 0115B5C0
    void ctor_0115C070();  // 0115C070
    void ctor_0115D150();  // 0115D150
    void ctor_01166BA0();  // 01166BA0
    void ctor_01166F10();  // 01166F10
    void ctor_0116B270();  // 0116B270
    void ctor_0116D500();  // 0116D500
    void ctor_0116F130();  // 0116F130
    void ctor_011705E0();  // 011705E0
    void ctor_01171550();  // 01171550
    void ctor_01176000();  // 01176000
    void ctor_01178240();  // 01178240
    void ctor_011798A0();  // 011798A0
};
