// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpMeshShape.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpStorageMeshShape : public hkpMeshShape {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    hkpStorageMeshShape();  // 01156080
    ~hkpStorageMeshShape();  // 011560C0
    hkpStorageMeshShape(int param_2);  // 01156710
    void ctor_01156790(int param_2);  // 01156790
    static void vf00();  // 01156D20
};
