// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpIterativeLinearCastAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSphereTriangleAgent : public hkpIterativeLinearCastAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01170170 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 0116FC20 slot 0xC  overrides hkpCollisionAgent
    virtual undefined vf10();  // 0116F7F0 slot 0x10  overrides hkpCollisionAgent
    virtual void vf18(int param_2, int param_3);  // 011702E0 slot 0x18  overrides hkpCollisionAgent
    virtual void vf1C(undefined4 param_2);  // 0116F630 slot 0x1C  overrides hkpCollisionAgent
    // non-virtual members
    hkpSphereTriangleAgent();  // 0116F550
    void ctor_0116F5D0();  // 0116F5D0
    void ctor_0116F670();  // 0116F670
    void ctor_01170010();  // 01170010
};
