// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpCollisionAgent.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpShapeCollectionAgent : public hkpCollisionAgent {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01177580 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 01176CF0 slot 0xC  overrides hkpCollisionAgent
    virtual undefined vf10();  // 01176870 slot 0x10  overrides hkpCollisionAgent
    virtual undefined vf14();  // 01176AB0 slot 0x14  overrides hkpCollisionAgent
    virtual void vf18(int param_2, int param_3);  // 01176780 slot 0x18  overrides hkpCollisionAgent
    virtual void vf1C(undefined4 param_2);  // 011766C0 slot 0x1C  overrides hkpCollisionAgent
    virtual undefined vf20();  // 01176F30 slot 0x20  overrides hkpCollisionAgent
    virtual void vf24(undefined4 param_2);  // 01176700 slot 0x24  overrides hkpCollisionAgent
    virtual undefined vf28();  // 01176730 slot 0x28  overrides hkpCollisionAgent
    // non-virtual members
    hkpShapeCollectionAgent();  // 01177120
};
