// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpShapePhantom.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpSimpleShapePhantom : public hkpShapePhantom {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011A26C0 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf18();  // 011A1650 slot 0x18  overrides hkpPhantom
    virtual void vf20(undefined4 param_2);  // 011A1AD0 slot 0x20  overrides hkpPhantom
    virtual void vf24(undefined1 * param_2, int param_3);  // 011A1660 slot 0x24  overrides hkpPhantom
    virtual void vf28(int param_2);  // 011A17C0 slot 0x28  overrides hkpPhantom
    virtual void vf2C();  // 011A1B30 slot 0x2C  overrides hkpPhantom
    virtual int vf30();  // 011A1C30 slot 0x30  overrides hkpPhantom
    virtual void vf38();  // 011A1DC0 slot 0x38  overrides hkpPhantom
    virtual undefined vf3C();  // 011A1890 slot 0x3C  overrides hkpShapePhantom
    virtual undefined vf40();  // 011A1A90 slot 0x40  overrides hkpShapePhantom
    virtual void vf44(undefined4 param_2, int param_3);  // 011A16B0 slot 0x44  overrides hkpShapePhantom
    virtual void vf48(int param_2, int param_3);  // 011A1730 slot 0x48  overrides hkpShapePhantom
    // non-virtual members
    ~hkpSimpleShapePhantom();  // 011A1B80
    hkpSimpleShapePhantom();  // 011AF430
};
