// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpUnaryAction.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpVehicleInstance : public hkpUnaryAction {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01286C40 slot 0x0  overrides hkBaseObject
    virtual void vf0C(int param_2);  // 0128D4D0 slot 0xC  overrides hkpAction
    virtual void vf14();  // 0128A570 slot 0x14  overrides hkpAction
    virtual int vf1C(int * param_2, int param_3);  // 0128CDC0 slot 0x1C  overrides hkpAction
    virtual void vf20();  // 0128BC70 slot 0x20
    virtual void vf24(undefined4 param_2);  // 0128AA00 slot 0x24
    virtual void vf28();  // 0128AA30 slot 0x28
    virtual undefined vf2C();  // 0128B510 slot 0x2C
    virtual float10 vf30();  // 0128A6F0 slot 0x30
    virtual float10 vf34();  // 0128C020 slot 0x34
    virtual float10 vf38();  // 0128C0A0 slot 0x38
    virtual void vf3C(undefined4 param_1, undefined2 * param_2);  // 0128A710 slot 0x3C
    // non-virtual members
    hkpVehicleInstance(undefined4 * param_1, undefined4 param_2);  // 01286A10
    hkpVehicleInstance();  // 01286BE0
    void ctor_0128C120();  // 0128C120
    ~hkpVehicleInstance();  // 0128C210
};
