// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpVehicleTransmission.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpVehicleDefaultTransmission : public hkpVehicleTransmission {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01288AE0 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 012921A0 slot 0xC  overrides hkpVehicleTransmission
    virtual float10 vf10(int param_2, int param_3);  // 01292220 slot 0x10
    virtual float10 vf14(int param_2, undefined4 param_3);  // 01292250 slot 0x14
    virtual void vf18(undefined1 * param_1, int param_2, int param_3);  // 01292430 slot 0x18
    virtual undefined vf1C();  // 012923B0 slot 0x1C
    virtual float10 vf20(undefined4 param_2, int param_3);  // 01292150 slot 0x20
    // non-virtual members
    hkpVehicleDefaultTransmission(undefined4 * param_1);  // 01288960
};
