// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpVehicleCastBatchingManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpVehicleLinearCastBatchingManager : public hkpVehicleCastBatchingManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01288470 slot 0x0  overrides hkBaseObject
    virtual int vf20(int param_1, int param_2);  // 01291430 slot 0x20  overrides hkpVehicleCastBatchingManager
    virtual undefined vf24();  // 012914F0 slot 0x24  overrides hkpVehicleCastBatchingManager
    virtual undefined vf28();  // 012916B0 slot 0x28  overrides hkpVehicleCastBatchingManager
    // non-virtual members
    ~hkpVehicleLinearCastBatchingManager();  // 012883F0
    hkpVehicleLinearCastBatchingManager();  // 01288410
};
