// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpVehicleEngine.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpVehicleDefaultEngine : public hkpVehicleEngine {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01288E50 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 01292630 slot 0xC  overrides hkpVehicleEngine
    // non-virtual members
    hkpVehicleDefaultEngine(undefined4 * param_1);  // 01288D40
};
