// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpVehicleManager : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01288210 slot 0x0  overrides hkBaseObject
    virtual void vf0C(int param_2);  // 01290060 slot 0xC
    virtual void vf10(int param_2);  // 01290010 slot 0x10
    virtual void vf14(undefined4 param_2);  // 012905C0 slot 0x14
    // non-virtual members
    ~hkpVehicleManager();  // 01288390
    hkpVehicleManager();  // 012883B0
};
