// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpVehicleAerodynamics.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpVehicleDefaultAerodynamics : public hkpVehicleAerodynamics {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01288FD0 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 01292930 slot 0xC  overrides hkpVehicleAerodynamics
    virtual float10 vf10(float param_2);  // 012928E0 slot 0x10
    virtual float10 vf14(float param_2);  // 01292850 slot 0x14
    // non-virtual members
    hkpVehicleDefaultAerodynamics(undefined4 * param_1);  // 01288EC0
};
