// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpVehicleBrake.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpVehicleDefaultBrake : public hkpVehicleBrake {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01287510 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 0128E720 slot 0xC  overrides hkpVehicleBrake
    // non-virtual members
    hkpVehicleDefaultBrake(undefined4 * param_1);  // 01287280
};
