// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpWorldObject : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01192240 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf0C(undefined4 param_2);  // 011C8340 slot 0xC
    virtual undefined4 vf10(int * param_2);  // 011C8350 slot 0x10
    virtual undefined4 vf14() = 0;  // 00FDB68B slot 0x14
    // non-virtual members
    ~hkpWorldObject();  // 01192170
    hkpWorldObject(int param_2);  // 011C85D0
    hkpWorldObject();  // 011C8650
};
