// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpWorldCinfo : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009307C0 slot 0x0  overrides hkBaseObject
    // non-virtual members
    hkpWorldCinfo();  // 00930E60
    hkpWorldCinfo(int param_2);  // 0119C370
    void ctor_011C0200();  // 011C0200
    void ctor_011C0460(int param_2);  // 011C0460
};
