// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpConstraintData.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpWheelConstraintData : public hkpConstraintData {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 011AF140 slot 0x0  overrides hkBaseObject
    virtual void vf28(undefined1 * param_2);  // 011D4020 slot 0x28  overrides hkpConstraintData
    virtual undefined4 vf2C();  // 011D3DE0 slot 0x2C  overrides hkpConstraintData
    virtual void vf30(char param_2, undefined4 * param_3);  // 011D3DB0 slot 0x30  overrides hkpConstraintData
    virtual void vf48(undefined4 param_2);  // 011D3D90 slot 0x48  overrides hkpConstraintData
    // non-virtual members
    hkpWheelConstraintData(undefined4 * param_1);  // 011AF0B0
    hkpWheelConstraintData();  // 011D3EC0
};
