// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpUnaryAction.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkpWindAction : public hkpUnaryAction {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01268AD0 slot 0x0  overrides hkBaseObject
    virtual void vf0C(int param_2);  // 01268A50 slot 0xC  overrides hkpAction
    virtual int vf1C(int * param_2, int param_3);  // 012689D0 slot 0x1C  overrides hkpAction
    // non-virtual members
    ~hkpWindAction();  // 01268970
    static undefined * vf08();  // 01268A90
    static void vf18();  // 014992B0
    static void vf10(int * param_2);  // 014993B0
};
