// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkResourceBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkResourceHandle : public hkResourceBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01112420 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf0C();  // 01111EB0 slot 0xC  overrides hkResourceBase
    virtual void vf14() = 0;  // 00FDB68B slot 0x14
    virtual undefined4 vf18() = 0;  // 00FDB68B slot 0x18
    virtual void vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual void vf20() = 0;  // 00FDB68B slot 0x20
    virtual void vf24(undefined4 param_2, undefined4 param_3) = 0;  // 00FDB68B slot 0x24
    virtual void vf28(undefined4 param_2) = 0;  // 00FDB68B slot 0x28
    virtual void vf2C(int * param_2) = 0;  // 00FDB68B slot 0x2C
    virtual undefined4 vf30() = 0;  // 00FDB68B slot 0x30
    virtual void vf34(undefined4 * param_2);  // 01110CD0 slot 0x34
};
