// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkResourceBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkResourceContainer : public hkResourceBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01112490 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf0C();  // 01111F10 slot 0xC  overrides hkResourceBase
    virtual undefined vf14() = 0;  // 00FDB68B slot 0x14
    virtual void vf18(int param_2) = 0;  // 00FDB68B slot 0x18
    virtual undefined4 vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual int * vf20(int param_2, int param_3, int param_4) = 0;  // 00FDB68B slot 0x20
    virtual undefined4 vf24() = 0;  // 00FDB68B slot 0x24
    virtual int vf28(undefined4 param_2) = 0;  // 00FDB68B slot 0x28
    virtual void vf2C(int param_2) = 0;  // 00FDB68B slot 0x2C
    virtual undefined4 vf30() = 0;  // 00FDB68B slot 0x30
    virtual int vf34(int param_2, int param_3) = 0;  // 00FDB68B slot 0x34
    virtual undefined4 vf38(int * param_2) = 0;  // 00FDB68B slot 0x38
    virtual void vf3C(undefined4 param_1);  // 01110E80 slot 0x3C
};
