// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "HkRemoveContainer.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct HkRemovePhysicsSystem : public HkRemoveContainer {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 008ECF20 slot 0x0  overrides HkRemoveContainer
    virtual bool vf04(int * param_2);  // 0092C980 slot 0x4  overrides HkRemoveContainer
    virtual void vf08();  // 0092D310 slot 0x8  overrides HkRemoveContainer
    virtual undefined4 vf1C();  // 008ECF10 slot 0x1C  overrides HkRemoveContainer
    virtual undefined4 vf20();  // 008ECF00 slot 0x20  overrides HkRemoveContainer
    // non-virtual members
    HkRemovePhysicsSystem();  // 008F1F80
};
