// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkStreamReader.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkSeekableStreamReader : public hkStreamReader {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0102BCF0 slot 0x0  overrides hkBaseObject
    virtual void vf18(undefined4 param_2);  // 0102BC90 slot 0x18  overrides hkStreamReader
    virtual bool vf1C(int param_2);  // 0102BC60 slot 0x1C  overrides hkStreamReader
    virtual undefined4 vf20();  // 0102BC80 slot 0x20  overrides hkStreamReader
    virtual undefined4 vf24(undefined4 param_2);  // 0102BCA0 slot 0x24  overrides hkStreamReader
};
