// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkSerializeDeprecated.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkSerializeDeprecated2 : public hkSerializeDeprecated {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    hkSerializeDeprecated2();  // 0104C8C0
    void ctor_0104C910();  // 0104C910
};
