// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkMemorySystem.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkSimpleMemorySystem : public hkMemorySystem {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00();  // 01024350 slot 0x0  overrides hkMemorySystem
    virtual int * vf04(int * param_2, uint param_3);  // 01024150 slot 0x4  overrides hkMemorySystem
    virtual undefined4 vf08(uint param_2);  // 010241B0 slot 0x8  overrides hkMemorySystem
    virtual void vf0C(int param_2, undefined4 param_3, byte param_4);  // 01024220 slot 0xC  overrides hkMemorySystem
    virtual void vf10(int param_1, byte param_2);  // 01024290 slot 0x10  overrides hkMemorySystem
    virtual void vf24(undefined4 param_2);  // 01024040 slot 0x24  overrides hkMemorySystem
    virtual undefined4 vf28();  // 01024120 slot 0x28  overrides hkMemorySystem
    virtual void vf2C();  // 01024130 slot 0x2C  overrides hkMemorySystem
    virtual undefined4 vf30();  // 01024320 slot 0x30  overrides hkMemorySystem
    // non-virtual members
    hkSimpleMemorySystem();  // 010242D0
};
