// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkStreamReader : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0101A7B0 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined1 * param_2) = 0;  // 00FDB68B slot 0xC
    virtual int vf10(int param_2, int param_3) = 0;  // 00FDB68B slot 0x10
    virtual int vf14(int param_2);  // 0102C470 slot 0x14
    virtual void vf18(undefined4 param_2);  // 0102C540 slot 0x18
    virtual bool vf1C(int param_2);  // 0102C500 slot 0x1C
    virtual undefined4 vf20();  // 0102C510 slot 0x20
    virtual undefined4 vf24(undefined4 param_2);  // 0102C550 slot 0x24
    virtual void vf28();  // 0102C520 slot 0x28
    virtual int vf2C();  // 0102C530 slot 0x2C
};
