// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkSeekableStreamReader.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkStdioStreamReader : public hkSeekableStreamReader {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 0102BD30 slot 0x0  overrides hkBaseObject
    virtual void vf0C(undefined1 * param_2);  // 0102BB20 slot 0xC  overrides hkStreamReader
    virtual int vf10(int param_2, int param_3);  // 0102BC10 slot 0x10  overrides hkStreamReader
    virtual void vf18(undefined4 param_2);  // 0102BB30 slot 0x18  overrides hkStreamReader
    virtual undefined4 vf24(undefined4 param_2);  // 0102BB40 slot 0x24  overrides hkStreamReader
    virtual void vf28();  // 0102BB50 slot 0x28  overrides hkStreamReader
    virtual int vf2C();  // 0102BB80 slot 0x2C  overrides hkStreamReader
    // non-virtual members
    hkStdioStreamReader(char * param_2);  // 0102BB90
};
