// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "HkSystemGroupManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct HkSystemGroupManagerImplement : public HkSystemGroupManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 008FDE70 slot 0x0  overrides HkSystemGroupManager
    virtual int vf04(uint param_2);  // 008FD7E0 slot 0x4  overrides HkSystemGroupManager
    virtual void vf08(int param_2);  // 008FD840 slot 0x8  overrides HkSystemGroupManager
    virtual int vf0C();  // 008FDE10 slot 0xC  overrides HkSystemGroupManager
    virtual float10 vf10();  // 008FDE20 slot 0x10  overrides HkSystemGroupManager
    // non-virtual members
    HkSystemGroupManagerImplement();  // 008FE850
};
