// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkVersionPatchManager : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    // non-virtual members
    hkVersionPatchManager();  // 010DD120
};
