// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkReferencedObject.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkVtableClassRegistry : public hkReferencedObject {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf0C();  // 0143EAD0 slot 0xC
    virtual void vf10(undefined4 param_1);  // 0104D480 slot 0x10
    virtual undefined4 vf14(undefined4 * param_1);  // 0104D4A0 slot 0x14
    virtual void vf18(int * param_2);  // 0104D610 slot 0x18
};
