// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkMeshShape.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkxBlobMeshShape : public hkMeshShape {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010D3D20 slot 0x0  overrides hkBaseObject
    virtual undefined * vf08();  // 010D3C10 slot 0x8  overrides hkReferencedObject
    virtual undefined4 vf0C();  // 010D3BD0 slot 0xC  overrides hkMeshShape
    virtual void vf10(int param_2, byte param_3, undefined1 * param_4);  // 010D3BE0 slot 0x10  overrides hkMeshShape
    virtual void vf14();  // 010D3BF0 slot 0x14  overrides hkMeshShape
    virtual uint vf18();  // 010D3C50 slot 0x18  overrides hkMeshShape
    virtual void vf1C();  // 010D3C00 slot 0x1C  overrides hkMeshShape
};
