// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkObjectWriter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkXmlObjectWriter : public hkObjectWriter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010F9920 slot 0x0  overrides hkBaseObject
    virtual undefined vf0C();  // 010F95F0 slot 0xC  overrides hkObjectWriter
    virtual bool vf10(int * param_1, undefined4 param_2, int param_3);  // 010F87F0 slot 0x10  overrides hkObjectWriter
    virtual undefined vf14();  // 010F9450 slot 0x14
    // non-virtual members
    hkXmlObjectWriter();  // 010F8D60
};
