// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkPackfileWriter.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkXmlPackfileWriter : public hkPackfileWriter {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 01055180 slot 0x0  overrides hkBaseObject
    virtual bool vf1C(int * param_1, undefined4 param_2);  // 01054D10 slot 0x1C  overrides hkPackfileWriter
    // non-virtual members
    hkXmlPackfileWriter();  // 01054AC0
    static undefined vf10();  // 010E56E0
    static void vf14(undefined4 param_2, undefined4 param_3);  // 010E5710
    static void vf18(undefined4 param_1, undefined4 param_2);  // 010E5770
    static void vf20();  // 010E5AA0
    static void vf24(undefined4 param_1, undefined4 param_2);  // 010E5AB0
    static void vf28(undefined4 param_1, undefined4 param_2);  // 010E5AE0
    static undefined vf0C();  // 010E6240
};
