// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkTagfileReader.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct hkXmlTagfileReader : public hkTagfileReader {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 010DBC80 slot 0x0  overrides hkBaseObject
    virtual undefined4 vf0C(undefined4 param_1, undefined4 param_2, undefined4 param_3);  // 01101390 slot 0xC  overrides hkTagfileReader
    // non-virtual members
    hkXmlTagfileReader(undefined4 param_2);  // 010DB020
};
