// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cItemViscelaBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct It0500 : public cItemViscelaBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AC1240 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AC0DE0 slot 0x4  overrides cObj
    virtual void vf30C();  // 005E8280 slot 0x30C  overrides cItemViscelaBase
    virtual void vf310();  // 005E81E0 slot 0x310  overrides cItemViscelaBase
    virtual void vf314();  // 005E8070 slot 0x314  overrides cItemViscelaBase
};
