// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct KamaitatiObj : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9CD0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1BB0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00867680 slot 0x40  overrides Behavior
    virtual void vf44();  // 0085EE70 slot 0x44  overrides Behavior
    virtual void vf48();  // 0085EEC0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00887300 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00894770 slot 0x50  overrides Behavior
    virtual void vf54();  // 0085EEE0 slot 0x54  overrides Behavior
    virtual undefined4 vf94();  // 00AB1BC0 slot 0x94  overrides Behavior
    virtual void setSeqAtk();  // 00887570 slot 0x128  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00870310 slot 0x130  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00870640 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0085EF10 slot 0x1A4  overrides Behavior
    // non-virtual members
    KamaitatiObj();  // 00AB1B60
};
