// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cCustomObjCtrlManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct LostDeviceFrame : public cCustomObjCtrlManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00989690 slot 0x0  overrides cCustomObjCtrlManager
    virtual void vf04();  // 00998D70 slot 0x4  overrides cCustomObjCtrlManager
    virtual void vf08();  // 00998DB0 slot 0x8  overrides cCustomObjCtrlManager
    virtual void create();  // 00999070 slot 0x14  overrides cCustomObjCtrlManager
    // non-virtual members
    LostDeviceFrame();  // 00989650
    void ctor_009990B0();  // 009990B0
};
