// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct MiddleOverJumpStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B81A90 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B91080 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00B81A10 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00BAC920 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BDF6E0 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00BCB0F0 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00BACA50 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00BACB00 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B81A50 slot 0x24  overrides StateMachineNode
};
