// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ModelShaderJackModule : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 00ECD740 slot 0x0  overrides cEspBase
    virtual void vf0C();  // 00EF7BB0 slot 0xC  overrides cEspBase
    virtual bool vf18(int param_2);  // 00EF7B60 slot 0x18  overrides cEspBase
    // non-virtual members
    static void updateModule(int param_2);  // 009EE450
    static void updateModule_2(int * param_2, int param_3);  // 009EF340
    static void updateModule_3(int * param_2, int param_3);  // 009F01E0
    ModelShaderJackModule();  // 00ECD610
    void ctor_00ED0480();  // 00ED0480
    void ctor_00ED04C0();  // 00ED04C0
    void ctor_00ED0640();  // 00ED0640
    void ctor_00ED06E0();  // 00ED06E0
    static void updateModule_4();  // 00EF7BD0
    static void updateModule_5();  // 00EF81E0
    static void updateModule_6(int * param_2, int param_3);  // 00F15820
    static void updateModule_7(int * param_2, int param_3);  // 00F163F0
    static void updateModule_8(int param_2);  // 00F3E960
};
