// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "cEsp.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ModelShaderWtrJackModule : public cEsp {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf00(byte param_2);  // 009F6A40 slot 0x0  overrides cEspBase
    virtual void vf0C();  // 00EF81C0 slot 0xC  overrides cEspBase
    virtual bool vf18(int param_2);  // 00EF8170 slot 0x18  overrides cEspBase
    // non-virtual members
    ModelShaderWtrJackModule();  // 009F6920
};
