// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "RayArmorDebris.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct MonDebris : public RayArmorDebris {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB8760 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAFB00 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0051EA60 slot 0x40  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 0051B6F0 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 0051EAB0 slot 0x1BC  overrides Behavior
    virtual void vf300();  // 0051B5D0 slot 0x300  overrides RayArmorDebris
    // non-virtual members
    MonDebris();  // 00AAFAE0
};
