// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct MonQteObj : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB77E0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAED20 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 0051E780 slot 0x40  overrides Behavior
    virtual void vf44();  // 0052EBA0 slot 0x44  overrides Behavior
    virtual void vf48();  // 0053B050 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0051B550 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0051B560 slot 0x50  overrides Behavior
    virtual void vf54();  // 0051B580 slot 0x54  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 0051B590 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0051B5A0 slot 0x1A4  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 0051E9C0 slot 0x1B8  overrides Behavior
    // non-virtual members
    MonQteObj();  // 00AAECC0
};
