// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct MonThrowObj : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9720 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1140 slot 0x4  overrides cObj
    virtual float10 vf24();  // 00AB1150 slot 0x24  overrides cObj
    virtual void vf30();  // 0051B1D0 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00537890 slot 0x40  overrides Behavior
    virtual void vf44();  // 0052DFB0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00537CF0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00541170 slot 0x4C  overrides Behavior
    virtual void vf50();  // 0051E200 slot 0x50  overrides Behavior
    virtual void vf54();  // 0051B140 slot 0x54  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 0051E0F0 slot 0x130  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 0051B260 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0052EB00 slot 0x1A4  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 0051B170 slot 0x1B8  overrides Behavior
};
