// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorEmBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct MonYoyoObj : public BehaviorEmBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB9740 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB1260 slot 0x4  overrides cObj
    virtual float10 vf24();  // 00AB1270 slot 0x24  overrides cObj
    virtual void vf30();  // 0051BD70 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00538D00 slot 0x40  overrides Behavior
    virtual void vf44();  // 0052F6A0 slot 0x44  overrides Behavior
    virtual void vf48();  // 0052F770 slot 0x48  overrides Behavior
    virtual void vf4C();  // 0053F5F0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005214C0 slot 0x50  overrides Behavior
    virtual void vf54();  // 0051BD40 slot 0x54  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 005213B0 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 00521800 slot 0x14C  overrides Behavior
    virtual void vf150();  // 0051BEC0 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 0051BF20 slot 0x158  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 0051BDA0 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 0053CA90 slot 0x1A4  overrides Behavior
    virtual void vf1C0();  // 0051BF50 slot 0x1C0  overrides Behavior
    virtual void vf260();  // 0051BF40 slot 0x260  overrides Behavior
    virtual undefined4 vf32C();  // 00534A80 slot 0x32C  overrides BehaviorEmBase
    virtual void vf334(int param_2);  // 005219F0 slot 0x334  overrides BehaviorEmBase
    virtual void vf338();  // 00521990 slot 0x338  overrides BehaviorEmBase
    virtual void vf33C(undefined4 param_1, int param_2);  // 00521830 slot 0x33C  overrides BehaviorEmBase
};
