// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkpPhantomOverlapListener.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct NinjaRunEventPhantomListener : public hkpPhantomOverlapListener {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00(int param_1);  // 00957D30 slot 0x0  overrides hkpPhantomOverlapListener
    virtual void vf04();  // 00957D20 slot 0x4  overrides hkpPhantomOverlapListener
    virtual undefined vf08();  // 00957DC0 slot 0x8  overrides hkpPhantomOverlapListener
};
