// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct OvercomeEnemyStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B82170 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B91190 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00B820E0 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00BB0220 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BE02E0 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00BCC1F0 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00BB0340 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00BB03A0 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B82120 slot 0x24  overrides StateMachineNode
    // non-virtual members
    OvercomeEnemyStatePl0010();  // 00B82140
};
