// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct OvercomeMissileStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B82230 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B911B0 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00B82190 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00BB0460 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BE03C0 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00BCC260 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00B821D0 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00BB0730 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B821E0 slot 0x24  overrides StateMachineNode
    // non-virtual members
    OvercomeMissileStatePl0010();  // 00B82200
};
