// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct P350 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D70380 slot 0x0  overrides cPhaseAbstract
    virtual void vf08();  // 00D487F0 slot 0x8  overrides cPhaseAbstract
    virtual void vf0C();  // 00D48A60 slot 0xC  overrides cPhaseAbstract
    virtual void vf10();  // 00D53440 slot 0x10  overrides cPhaseAbstract
    virtual void vf14(undefined4 param_2, byte * param_3);  // 00D53190 slot 0x14  overrides cPhaseAbstract
    virtual void vf18();  // 00D5AAA0 slot 0x18  overrides cPhaseAbstract
    virtual void vf1C(undefined4 param_1, byte * param_2);  // 00D487C0 slot 0x1C  overrides cPhaseAbstract
};
