// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Pf13 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00D70720 slot 0x0  overrides cPhaseAbstract
    virtual void vf08();  // 00D5FEE0 slot 0x8  overrides cPhaseAbstract
    virtual void vf0C();  // 00D476D0 slot 0xC  overrides cPhaseAbstract
    virtual void vf10();  // 00D476E0 slot 0x10  overrides cPhaseAbstract
    virtual void vf14(undefined4 param_2, byte * param_3);  // 00D50E90 slot 0x14  overrides cPhaseAbstract
    virtual void vf18();  // 00D70CA0 slot 0x18  overrides cPhaseAbstract
    virtual void vf1C(undefined4 param_1, byte * param_2);  // 00D476C0 slot 0x1C  overrides cPhaseAbstract
};
