// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Pl0012 : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB64E0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6060 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00C12120 slot 0x40  overrides Behavior
    virtual void vf44();  // 00C11A80 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00C11EF0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00C11AA0 slot 0x50  overrides Behavior
    // non-virtual members
    Pl0012();  // 00AA6040
};
