// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Pl0000 : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AC35D0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AC0A70 slot 0x4  overrides cObj
    virtual void vf1C();  // 00B866E0 slot 0x1C  overrides cObj
    virtual void vf20();  // 00B866C0 slot 0x20  overrides cObj
    virtual undefined4 startup();  // 00C02660 slot 0x40  overrides Behavior
    virtual void vf44();  // 00BBCEE0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00BF2740 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00C064C0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00BF2CC0 slot 0x50  overrides Behavior
    virtual void vf54();  // 00BBDEC0 slot 0x54  overrides Behavior
    virtual void vf5C();  // 00B7A080 slot 0x5C  overrides Behavior
    virtual void vf7C(undefined4 param_2, undefined4 param_3);  // 00B7A1F0 slot 0x7C  overrides Behavior
    virtual void vfFC();  // 00B94C10 slot 0xFC  overrides Behavior
    virtual void vf100();  // 00B94D20 slot 0x100  overrides Behavior
    virtual void vf104();  // 00C063C0 slot 0x104  overrides Behavior
    virtual void vf108();  // 00B7D840 slot 0x108  overrides Behavior
    virtual undefined4 vf10C();  // 00B7D710 slot 0x10C  overrides Behavior
    virtual void setSeqAtk();  // 00BBE290 slot 0x128  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 00BE6E90 slot 0x130  overrides Behavior
    virtual undefined4 vf134();  // 00BE9580 slot 0x134  overrides Behavior
    virtual undefined4 vf14C();  // 00B8C900 slot 0x14C  overrides Behavior
    virtual void vf150();  // 00BF5690 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 00B7E6F0 slot 0x158  overrides Behavior
    virtual void vf160();  // 00B7E6C0 slot 0x160  overrides Behavior
    virtual undefined4 vf17C();  // 00AC0C50 slot 0x17C  overrides Behavior
    virtual undefined4 vf184();  // 00B8CBD0 slot 0x184  overrides Behavior
    virtual void vf188();  // 00B8CC70 slot 0x188  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 00B94DA0 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 00BDA310 slot 0x1A4  overrides Behavior
    virtual void vf1AC();  // 00B94D60 slot 0x1AC  overrides Behavior
    virtual void vf1E8();  // 00B7D9E0 slot 0x1E8  overrides Behavior
    virtual void vf1EC();  // 00B7DA00 slot 0x1EC  overrides Behavior
    virtual undefined4 vf1FC();  // 00AC0AA0 slot 0x1FC  overrides Behavior
    virtual void vf214(undefined4 param_2, undefined4 param_3, int param_4);  // 00B87120 slot 0x214  overrides Behavior
    virtual void vf218();  // 00B87260 slot 0x218  overrides Behavior
    virtual void vf224();  // 00AC0D20 slot 0x224  overrides Behavior
    virtual undefined4 vf228();  // 00B87070 slot 0x228  overrides Behavior
    virtual undefined4 vf22C();  // 00B870C0 slot 0x22C  overrides Behavior
    virtual undefined4 vf230();  // 00B7C750 slot 0x230  overrides Behavior
    virtual undefined4 vf234();  // 00B7C780 slot 0x234  overrides Behavior
    virtual void vf248();  // 00B88960 slot 0x248  overrides Behavior
    virtual undefined4 vf270();  // 00AC0D60 slot 0x270  overrides Behavior
    virtual void vf27C(undefined4 * param_2);  // 00AC0C60 slot 0x27C  overrides Behavior
    virtual undefined4 vf280();  // 00B8DAA0 slot 0x280  overrides Behavior
    virtual undefined4 vf284();  // 00BEA700 slot 0x284  overrides Behavior
    virtual undefined4 vf288();  // 00B7EC70 slot 0x288  overrides Behavior
    virtual void vf2F8();  // 00BF26F0 slot 0x2F8  overrides Behavior
    virtual void vf30C(int param_2, int param_3);  // 00B94640 slot 0x30C  overrides BehaviorAppBase
    virtual void vf314();  // 00AC0C90 slot 0x314  overrides BehaviorAppBase
    virtual void vf318();  // 00AC0CC0 slot 0x318  overrides BehaviorAppBase
    virtual void vf31C();  // 00B7ADE0 slot 0x31C  overrides BehaviorAppBase
    virtual undefined4 vf320(float param_2);  // 00B86EA0 slot 0x320  overrides BehaviorAppBase
    virtual undefined4 vf324();  // 00B7AD80 slot 0x324  overrides BehaviorAppBase
    virtual void vf328(float param_2);  // 00B7A9E0 slot 0x328  overrides BehaviorAppBase
    virtual bool vf32C();  // 00B95330 slot 0x32C
    virtual bool vf330();  // 00B7E1F0 slot 0x330
    virtual bool vf334();  // 00B7E200 slot 0x334
    virtual undefined4 vf338();  // 00AC0A80 slot 0x338
    virtual bool vf33C();  // 00B7AD90 slot 0x33C
    virtual bool vf340();  // 00B7C730 slot 0x340
    virtual bool vf344();  // 00BC3370 slot 0x344
    virtual bool vf348();  // 00B7CDB0 slot 0x348
    virtual uint vf34C();  // 00B7E5C0 slot 0x34C
    virtual undefined4 vf350();  // 00AC0AB0 slot 0x350
    virtual bool vf354();  // 00AC0AD0 slot 0x354
    virtual undefined4 vf358();  // 00AC0AE0 slot 0x358
    virtual undefined4 vf35C();  // 00AC0B00 slot 0x35C
    virtual undefined4 vf360();  // 00AC0B30 slot 0x360
    virtual undefined4 vf364();  // 00AC0B80 slot 0x364
    virtual undefined4 vf368();  // 00B7C830 slot 0x368
    virtual undefined4 vf36C();  // 00AC0B90 slot 0x36C
    virtual undefined4 vf370();  // 00AC0BB0 slot 0x370
    virtual undefined4 vf374();  // 00AC0BE0 slot 0x374
    virtual undefined4 vf378();  // 00AC0C10 slot 0x378
    virtual bool vf37C();  // 00AC0C40 slot 0x37C
    virtual bool vf380();  // 00B89630 slot 0x380
    virtual void vf384();  // 00B896B0 slot 0x384
    virtual void vf388();  // 00B87BD0 slot 0x388
    virtual void vf38C();  // 00B7CE20 slot 0x38C
    virtual void vf390();  // 00BC8DE0 slot 0x390
    virtual void vf394();  // 00B7D560 slot 0x394
    virtual bool vf398();  // 00B7D5B0 slot 0x398
    virtual void vf39C();  // 00B88710 slot 0x39C
    virtual float10 vf3A0();  // 00B8DBB0 slot 0x3A0
    virtual float10 vf3A4();  // 00B8DC40 slot 0x3A4
    virtual float10 vf3A8();  // 00B8DCC0 slot 0x3A8
    virtual float10 vf3AC();  // 00B8DD50 slot 0x3AC
    virtual float10 vf3B0();  // 00BC4C20 slot 0x3B0
    virtual float10 vf3B4();  // 00B7F4E0 slot 0x3B4
    virtual float10 vf3B8();  // 00B8DDD0 slot 0x3B8
    virtual undefined1 vf3BC();  // 00B8DE40 slot 0x3BC
    virtual void vf3C0();  // 00B93790 slot 0x3C0
    virtual void vf3C4();  // 00C104B0 slot 0x3C4
    virtual void vf3C8();  // 00C05000 slot 0x3C8
    virtual undefined4 vf3CC();  // 00C04430 slot 0x3CC
    virtual undefined4 vf3D0();  // 00BC4200 slot 0x3D0
    virtual undefined4 vf3D4();  // 00BC44D0 slot 0x3D4
    virtual void vf3D8();  // 00B948D0 slot 0x3D8
    virtual void vf3DC(undefined4 param_2, undefined4 param_3);  // 00BC33F0 slot 0x3DC
    virtual void vf3E0(undefined4 param_2, undefined4 param_3);  // 00BC3470 slot 0x3E0
    virtual void vf3E4();  // 00AC0D00 slot 0x3E4
    virtual undefined4 vf3E8();  // 00AC0D70 slot 0x3E8
    virtual bool vf3EC();  // 00B8A4C0 slot 0x3EC
    virtual void vf3F0();  // 00AC0D80 slot 0x3F0
    virtual void vf3F4();  // 00B7D760 slot 0x3F4
    // non-virtual members
    Pl0000();  // 00AC0310
    static void qteZangekiSafeCheckForward();  // 00B89A20
    static undefined4 vf134_00BDA8A0();  // 00BDA8A0
    static void em0080Qte2SafeCheck(undefined4 * param_2);  // 00BF9730
};
