// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Pl0013 : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6450 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAB550 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00B78E70 slot 0x40  overrides Behavior
    virtual void vf44();  // 00B78E20 slot 0x44  overrides Behavior
    virtual void vf4C();  // 00B78E40 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00B78E60 slot 0x50  overrides Behavior
};
