// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorBulletBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Pl1500Knife : public BehaviorBulletBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00ABA250 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AB4340 slot 0x4  overrides cObj
    virtual void vf300();  // 008CF450 slot 0x300  overrides BehaviorBulletBase
    virtual void vf304();  // 008A9C90 slot 0x304  overrides BehaviorBulletBase
    // non-virtual members
    Pl1500Knife();  // 00AB4320
    static void vf44();  // 00ACFB40
};
