// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "PlBaseDLC.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Pl1500 : public PlBaseDLC {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AC3CA0 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AC3B40 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 008C6130 slot 0x40  overrides Behavior
    virtual void vf44();  // 008AAD60 slot 0x44  overrides Behavior
    virtual void vf48();  // 008C6200 slot 0x48  overrides Behavior
    virtual void vf4C();  // 008D0770 slot 0x4C  overrides Behavior
    virtual void vf50();  // 008C6220 slot 0x50  overrides Behavior
    virtual void vf54();  // 008A5290 slot 0x54  overrides Behavior
    virtual void vf7C(undefined4 param_2, undefined4 param_3);  // 008A0D80 slot 0x7C  overrides Behavior
    virtual undefined4 vf94();  // 00AC3B50 slot 0x94  overrides Behavior
    virtual void vfFC();  // 008AAE00 slot 0xFC  overrides Behavior
    virtual void vf100();  // 008B92A0 slot 0x100  overrides Behavior
    virtual undefined4 vf10C();  // 008A5380 slot 0x10C  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 008A72B0 slot 0x130  overrides Behavior
    virtual undefined4 vf14C();  // 008A3A50 slot 0x14C  overrides Behavior
    virtual void vf150();  // 008B0D60 slot 0x150  overrides Behavior
    virtual undefined4 vf158();  // 008A3A70 slot 0x158  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 008AF150 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 008ACF20 slot 0x1A4  overrides Behavior
    virtual void vf214(undefined4 param_2, undefined4 param_3, int param_4);  // 008A5430 slot 0x214  overrides Behavior
    virtual void vf218();  // 008A54A0 slot 0x218  overrides Behavior
    virtual void vf248();  // 008A5300 slot 0x248  overrides Behavior
    virtual void vf2F8();  // 008A5360 slot 0x2F8  overrides Behavior
    virtual bool vf32C();  // 008B2350 slot 0x32C  overrides Pl0000
    virtual uint vf34C();  // 008A3A90 slot 0x34C  overrides Pl0000
    virtual bool vf354();  // 00AC3B80 slot 0x354  overrides Pl0000
    virtual undefined4 vf358();  // 00AC3B60 slot 0x358  overrides Pl0000
    virtual undefined4 vf35C();  // 00AC3B90 slot 0x35C  overrides Pl0000
    virtual undefined4 vf360();  // 00AC3B70 slot 0x360  overrides Pl0000
    virtual undefined4 vf364();  // 00AC3C10 slot 0x364  overrides Pl0000
    virtual undefined4 vf368();  // 00AC3BA0 slot 0x368  overrides Pl0000
    virtual undefined4 vf36C();  // 00AC3BB0 slot 0x36C  overrides Pl0000
    virtual undefined4 vf374();  // 00AC3BE0 slot 0x374  overrides Pl0000
    virtual undefined4 vf378();  // 00AC3BF0 slot 0x378  overrides Pl0000
    virtual bool vf37C();  // 00AC3C00 slot 0x37C  overrides Pl0000
    virtual bool vf380();  // 008A53A0 slot 0x380  overrides Pl0000
    virtual void vf388();  // 008B9CD0 slot 0x388  overrides Pl0000
    virtual void vf38C();  // 008B9210 slot 0x38C  overrides Pl0000
    virtual void vf390();  // 008D3460 slot 0x390  overrides Pl0000
    virtual void vf3C0();  // 008A0D00 slot 0x3C0  overrides Pl0000
    virtual undefined4 vf3CC();  // 008C7E40 slot 0x3CC  overrides Pl0000
    virtual undefined4 vf3E8();  // 008A9140 slot 0x3E8  overrides Pl0000
    virtual void vf3FC();  // 008D36B0 slot 0x3FC  overrides PlBaseDLC
    virtual bool vf404();  // 00AC3C20 slot 0x404  overrides PlBaseDLC
    virtual bool vf408();  // 00AC3C30 slot 0x408  overrides PlBaseDLC
    virtual void vf40C();  // 008B22E0 slot 0x40C  overrides PlBaseDLC
    virtual void vf410();  // 008A0CE0 slot 0x410  overrides PlBaseDLC
    virtual void vf414();  // 008CF1D0 slot 0x414  overrides PlBaseDLC
    virtual undefined4 vf418(int param_2, int * param_3);  // 008BB8D0 slot 0x418  overrides PlBaseDLC
    virtual void vf420();  // 008A20D0 slot 0x420  overrides PlBaseDLC
    virtual undefined4 vf424();  // 008A9170 slot 0x424  overrides PlBaseDLC
    // non-virtual members
    static undefined4 vf358_008A2930();  // 008A2930
    static bool vf35C_008A2950();  // 008A2950
    static undefined4 vf360_008A2970();  // 008A2970
    static undefined4 vf378_008A29B0();  // 008A29B0
    static undefined4 vf37C_008A29E0();  // 008A29E0
    static bool vf404_008A2A10();  // 008A2A10
    Pl1500();  // 00AC3A40
};
