// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct PlayerNullCamera : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB6600 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA60F0 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 00B80A00 slot 0x40  overrides Behavior
    virtual void vf4C();  // 00BA86D0 slot 0x4C  overrides Behavior
    // non-virtual members
    PlayerNullCamera();  // 00AA60D0
};
