// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorAppBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct PowGaObj : public BehaviorAppBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7660 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AAE950 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005B7320 slot 0x40  overrides Behavior
    virtual void vf44();  // 005B0900 slot 0x44  overrides Behavior
    virtual void vf48();  // 005B0940 slot 0x48  overrides Behavior
    virtual void vf4C();  // 005C6450 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005B7470 slot 0x50  overrides Behavior
    virtual int getAttackInfo(ushort * param_2);  // 005BD8A0 slot 0x130  overrides Behavior
    virtual void vf19C(int param_2, undefined4 param_3);  // 005BDE50 slot 0x19C  overrides Behavior
    virtual void vf1A4(undefined4 param_2, uint param_3);  // 005B75F0 slot 0x1A4  overrides Behavior
    // non-virtual members
    PowGaObj();  // 00AAE900
};
