// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "ProgressFlagBase_Dlc.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ProgressFlagDlc2 : public ProgressFlagBase_Dlc {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00C88EE0 slot 0x0  overrides ProgressFlagBase_Dlc
    // non-virtual members
    static undefined1 SAVE();  // 00C82640
    static undefined LOAD();  // 00C826D0
};
