// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "ProgressFlagBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ProgressFlag : public ProgressFlagBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00C88E80 slot 0x0  overrides ProgressFlagBase
    // non-virtual members
    static uint SAVE();  // 00C81F30
    static uint LOAD();  // 00C81FB0
};
