// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct R705 {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00();  // 00A79D50 slot 0x0  overrides cRoomAbstract
    virtual void vf04();  // 00A71680 slot 0x4  overrides cRoomAbstract
    virtual undefined4 * vf14(byte param_2);  // 00A7B930 slot 0x14  overrides cRoomAbstract
};
