// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "BehaviorDebrisBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct RayArmorDebris : public BehaviorDebrisBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AEF860 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AEF850 slot 0x4  overrides cObj
    virtual void vf30();  // 00AEAD10 slot 0x30  overrides cObj
    virtual undefined4 startup();  // 00AEAC00 slot 0x40  overrides Behavior
    virtual void vf44();  // 00AEACB0 slot 0x44  overrides Behavior
    virtual void vf48();  // 00AEACC0 slot 0x48  overrides Behavior
    virtual void vf4C();  // 00AEACE0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 00AEACF0 slot 0x50  overrides Behavior
    virtual void vf54();  // 00AEAD00 slot 0x54  overrides Behavior
    virtual void setCutCrerateInfo(undefined4 * param_1, undefined4 param_2, int param_3);  // 00AEAD40 slot 0x1B8  overrides Behavior
    virtual void vf1BC(int * param_2);  // 00AEF4C0 slot 0x1BC  overrides Behavior
    virtual void vf300();  // 00AEF570 slot 0x300
    // non-virtual members
    RayArmorDebris();  // 00AEF830
};
