// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "RayCastWork.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct RayCastPenetrationWork : public RayCastWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00906780 slot 0x0  overrides RayCastWork
    virtual undefined4 vf04(byte param_2);  // 009067C0 slot 0x4  overrides RayCastWork
    virtual void vf08();  // 00907070 slot 0x8  overrides RayCastWork
    virtual undefined4 vf0C();  // 009067B0 slot 0xC  overrides RayCastWork
    virtual void vf10();  // 0090AFB0 slot 0x10  overrides RayCastWork
    virtual void vf14();  // 00905CB0 slot 0x14  overrides RayCastWork
    virtual void vf18();  // 0090AFF0 slot 0x18  overrides RayCastWork
    virtual void vf1C();  // 00905CA0 slot 0x1C  overrides RayCastWork
    virtual void vf20(undefined4 param_2);  // 0090B030 slot 0x20  overrides RayCastWork
};
