// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct RayCastWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 009055D0 slot 0x0
    virtual undefined4 vf04(byte param_2);  // 009068B0 slot 0x4
    virtual void vf08() = 0;  // 00FDB68B slot 0x8
    virtual undefined4 vf0C() = 0;  // 00FDB68B slot 0xC
    virtual void vf10() = 0;  // 00FDB68B slot 0x10
    virtual void vf14() = 0;  // 00FDB68B slot 0x14
    virtual void vf18() = 0;  // 00FDB68B slot 0x18
    virtual void vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual void vf20(undefined4 param_2) = 0;  // 00FDB68B slot 0x20
    virtual void vf24(uint param_2);  // 009055E0 slot 0x24
    virtual void vf28(uint param_2);  // 009055F0 slot 0x28
    virtual void vf2C(uint param_2);  // 00905600 slot 0x2C
    virtual void vf30(uint param_2);  // 00905610 slot 0x30
    virtual void vf34(uint param_2);  // 00905620 slot 0x34
    virtual void vf38(uint param_2);  // 00905630 slot 0x38
    // non-virtual members
    RayCastWork();  // 00906660
    static undefined get();  // 00906810
    static undefined set();  // 00908310
};
