// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "RayCastWork.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct RayCastSingleHitWork : public RayCastWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 009066A0 slot 0x0  overrides RayCastWork
    virtual undefined4 vf04(byte param_2);  // 009066D0 slot 0x4  overrides RayCastWork
    virtual void vf08();  // 009068D0 slot 0x8  overrides RayCastWork
    virtual undefined4 vf0C();  // 009066C0 slot 0xC  overrides RayCastWork
    virtual void vf10();  // 0090A740 slot 0x10  overrides RayCastWork
    virtual void vf14();  // 009058D0 slot 0x14  overrides RayCastWork
    virtual void vf18();  // 0090A780 slot 0x18  overrides RayCastWork
    virtual void vf1C();  // 009058A0 slot 0x1C  overrides RayCastWork
    virtual void vf20(undefined4 param_2);  // 0090A7C0 slot 0x20  overrides RayCastWork
    // non-virtual members
    RayCastSingleHitWork();  // 00907860
    void ctor_0090B130();  // 0090B130
    void ctor_0090B2E0();  // 0090B2E0
    void ctor_0090B490();  // 0090B490
    RayCastSingleHitWork(undefined4 param_1, int param_2);  // 00910800
};
