// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct RealArrayImplementation {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int vf00(byte param_2);  // 010F3740 slot 0x0  overrides hkDataRefCounted
    virtual undefined4 vf20();  // 010F2790 slot 0x20  overrides hkDataArrayImpl
    virtual void vf3C(int param_2);  // 010F2760 slot 0x3C  overrides hkDataArrayImpl
    virtual void vf40(int param_2, undefined4 param_3);  // 010F2770 slot 0x40  overrides hkDataArrayImpl
    virtual void vf70(int param_2, int param_3);  // 010F27C0 slot 0x70  overrides hkDataArrayImpl
    // non-virtual members
    RealArrayImplementation();  // 010F2720
};
