// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "RigidBodyManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct RigidBodyManagerImplement : public RigidBodyManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 009264E0 slot 0x0  overrides RigidBodyManager
    virtual undefined createBox();  // 00921990 slot 0x4  overrides RigidBodyManager
    virtual undefined createSphere();  // 00921BB0 slot 0x8  overrides RigidBodyManager
    virtual undefined createCaspule();  // 00921D80 slot 0xC  overrides RigidBodyManager
    virtual undefined createCylinder();  // 00921FC0 slot 0x10  overrides RigidBodyManager
    virtual undefined createHexahedron();  // 00927330 slot 0x14  overrides RigidBodyManager
    virtual undefined createPlane();  // 009216C0 slot 0x18  overrides RigidBodyManager
    virtual undefined vf1C();  // 00926500 slot 0x1C  overrides RigidBodyManager
    virtual undefined vf20();  // 00921580 slot 0x20  overrides RigidBodyManager
    virtual undefined vf24();  // 009214A0 slot 0x24  overrides RigidBodyManager
    virtual void vf28(int * param_2);  // 00919620 slot 0x28  overrides RigidBodyManager
    virtual void vf2C(undefined4 * param_2);  // 00913FC0 slot 0x2C  overrides RigidBodyManager
    virtual uint vf30(int param_2);  // 00920A30 slot 0x30  overrides RigidBodyManager
    virtual void vf34();  // 00919570 slot 0x34  overrides RigidBodyManager
};
