// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct RigidBodyManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00910A00 slot 0x0
    virtual undefined createBox() = 0;  // 00FDB68B slot 0x4
    virtual undefined createSphere() = 0;  // 00FDB68B slot 0x8
    virtual undefined createCaspule() = 0;  // 00FDB68B slot 0xC
    virtual undefined createCylinder() = 0;  // 00FDB68B slot 0x10
    virtual undefined createHexahedron() = 0;  // 00FDB68B slot 0x14
    virtual undefined createPlane() = 0;  // 00FDB68B slot 0x18
    virtual undefined vf1C() = 0;  // 00FDB68B slot 0x1C
    virtual undefined vf20() = 0;  // 00FDB68B slot 0x20
    virtual undefined vf24() = 0;  // 00FDB68B slot 0x24
    virtual void vf28(int * param_2) = 0;  // 00FDB68B slot 0x28
    virtual void vf2C(undefined4 * param_2) = 0;  // 00FDB68B slot 0x2C
    virtual uint vf30(int param_2) = 0;  // 00FDB68B slot 0x30
    virtual void vf34() = 0;  // 00FDB68B slot 0x34
    // non-virtual members
    static undefined createPlane_009216C0();  // 009216C0
    static undefined createBox_00921990();  // 00921990
    static undefined createSphere_00921BB0();  // 00921BB0
    static undefined createCaspule_00921D80();  // 00921D80
    static undefined createCylinder_00921FC0();  // 00921FC0
    static undefined createHexahedron_00927330();  // 00927330
};
