// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "ScenarioRegionManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ScenarioRegionManagerImplement : public ScenarioRegionManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 00A76100 slot 0x0  overrides ScenarioRegionManager
    virtual void vf04();  // 00A71BC0 slot 0x4  overrides ScenarioRegionManager
    virtual void vf08();  // 00A6DFC0 slot 0x8  overrides ScenarioRegionManager
    virtual void vf0C();  // 00A6DFD0 slot 0xC  overrides ScenarioRegionManager
    virtual undefined setGroupResource();  // 00A6F870 slot 0x10  overrides ScenarioRegionManager
    virtual void vf14(int param_2);  // 00A6FC00 slot 0x14  overrides ScenarioRegionManager
    virtual void vf18(int param_2);  // 00A6FC50 slot 0x18  overrides ScenarioRegionManager
    virtual void vf1C(int param_2);  // 00A6FD10 slot 0x1C  overrides ScenarioRegionManager
    virtual undefined vf20();  // 00A6E0E0 slot 0x20  overrides ScenarioRegionManager
    virtual undefined vf24();  // 00A6E110 slot 0x24  overrides ScenarioRegionManager
    virtual undefined vf28();  // 00A6FE70 slot 0x28  overrides ScenarioRegionManager
    virtual undefined vf2C();  // 00A6FEB0 slot 0x2C  overrides ScenarioRegionManager
    virtual undefined vf30();  // 00A6FDE0 slot 0x30  overrides ScenarioRegionManager
    virtual void vf34(undefined4 param_2);  // 00A76090 slot 0x34  overrides ScenarioRegionManager
    virtual void vf38();  // 00A760B0 slot 0x38  overrides ScenarioRegionManager
    virtual undefined vf3C();  // 00A6E070 slot 0x3C  overrides ScenarioRegionManager
    virtual ushort * vf40(uint param_2, int param_3);  // 00A6E180 slot 0x40  overrides ScenarioRegionManager
    virtual void vf44(uint param_2, int param_3);  // 00A6E1F0 slot 0x44  overrides ScenarioRegionManager
    virtual void vf48(uint param_2, int param_3);  // 00A6E250 slot 0x48  overrides ScenarioRegionManager
    virtual uint vf4C(uint param_2, int param_3);  // 00A6FF40 slot 0x4C  overrides ScenarioRegionManager
    virtual undefined4 vf50(uint param_2, int param_3);  // 00A6E2B0 slot 0x50  overrides ScenarioRegionManager
    virtual undefined vf54();  // 00A6E310 slot 0x54  overrides ScenarioRegionManager
    virtual undefined vf58();  // 00A6E390 slot 0x58  overrides ScenarioRegionManager
    virtual undefined vf5C();  // 00A6E400 slot 0x5C  overrides ScenarioRegionManager
    virtual undefined vf60();  // 00A6FFB0 slot 0x60  overrides ScenarioRegionManager
    virtual undefined4 vf64();  // 00A6E520 slot 0x64  overrides ScenarioRegionManager
    virtual void vf68();  // 00A6E530 slot 0x68  overrides ScenarioRegionManager
    virtual void vf6C();  // 00A70030 slot 0x6C  overrides ScenarioRegionManager
    virtual void vf70(undefined4 param_2);  // 00A6E4F0 slot 0x70  overrides ScenarioRegionManager
    virtual void vf74(undefined4 param_2);  // 00A6E480 slot 0x74  overrides ScenarioRegionManager
    virtual int * vf78(uint param_2, int param_3);  // 00A6E560 slot 0x78  overrides ScenarioRegionManager
    virtual int * vf7C(byte * param_2, int param_3);  // 00A6E5C0 slot 0x7C  overrides ScenarioRegionManager
    virtual byte * vf80(int param_2, int param_3);  // 00A70140 slot 0x80  overrides ScenarioRegionManager
    virtual void vf84(undefined4 param_2);  // 00A6E540 slot 0x84  overrides ScenarioRegionManager
    virtual int * vf88(int param_2, int param_3);  // 00A6F800 slot 0x88  overrides ScenarioRegionManager
    // non-virtual members
    ScenarioRegionManagerImplement();  // 00A76020
};
