// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "ShapeBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ShapeMesh : public ShapeBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00A6B990 slot 0x0  overrides ShapeBase
    virtual undefined4 * vf04(undefined4 * param_1);  // 00A6CB80 slot 0x4  overrides ShapeBase
    virtual undefined4 * vf08(byte param_2);  // 00A6C120 slot 0x8  overrides ShapeBase
    virtual void vf0C();  // 00A6C420 slot 0xC  overrides ShapeBase
    virtual void vf14();  // 00A6B8D0 slot 0x14  overrides ShapeBase
    virtual void vf18(undefined4 param_2);  // 00A6D060 slot 0x18  overrides ShapeBase
    virtual byte vf1C(undefined4 param_2);  // 00A6CA20 slot 0x1C  overrides ShapeBase
    // non-virtual members
    ShapeMesh();  // 00A6B960
};
