// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ShapeBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00A6AD10 slot 0x0
    virtual undefined4 * vf04(undefined4 * param_1);  // 00A6CA40 slot 0x4
    virtual undefined4 * vf08(byte param_2);  // 00A6B100 slot 0x8
    virtual void vf0C();  // 00A6C300 slot 0xC
    virtual void vf10();  // 00A6ACF0 slot 0x10
    virtual void vf14() = 0;  // 00FDB68B slot 0x14
    virtual void vf18(undefined4 param_2) = 0;  // 00FDB68B slot 0x18
    virtual byte vf1C(undefined4 param_2) = 0;  // 00FDB68B slot 0x1C
    // non-virtual members
    ShapeBase();  // 00A6AD30
    void ctor_00A6ADA0();  // 00A6ADA0
    void ctor_00A6AE10();  // 00A6AE10
    void ctor_00A6AE30();  // 00A6AE30
    ShapeBase(undefined4 param_2);  // 00A6B000
    void ctor_00A6B9A0();  // 00A6B9A0
};
