// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "SignalManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct SignalManagerImplement : public SignalManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int * vf00(int * param_2);  // 00D8A710 slot 0x0  overrides SignalManager
    virtual int * vf04(int param_2);  // 00D8A5C0 slot 0x4  overrides SignalManager
    virtual undefined4 * vf08(byte param_2);  // 00D8A6F0 slot 0x8  overrides SignalManager
};
