// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct SignalManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int * vf00(int * param_2) = 0;  // 00FDB68B slot 0x0
    virtual int * vf04(int param_2) = 0;  // 00FDB68B slot 0x4
    virtual undefined4 * vf08(byte param_2);  // 00D897D0 slot 0x8
    // non-virtual members
    SignalManager();  // 00D8A650
};
