// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "SituationManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct SituationManagerImplement : public SituationManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00();  // 00C60BC0 slot 0x0  overrides SituationManager
    virtual undefined vf04();  // 00C3D4C0 slot 0x4  overrides SituationManager
    virtual undefined vf08();  // 00C3D400 slot 0x8  overrides SituationManager
    virtual undefined4 * vf0C(byte param_2);  // 00C60B90 slot 0xC  overrides SituationManager
};
