// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct SituationManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00() = 0;  // 00FDB68B slot 0x0
    virtual undefined vf04() = 0;  // 00FDB68B slot 0x4
    virtual undefined vf08() = 0;  // 00FDB68B slot 0x8
    virtual undefined4 * vf0C(byte param_2);  // 00C1A600 slot 0xC
    // non-virtual members
    SituationManager();  // 00C60B10
};
