// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "ContentsBase.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct SlashTestContents : public ContentsBase {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 008DB560 slot 0x0  overrides ContentsBase
    virtual undefined4 * vf04(byte param_2);  // 008DB5B0 slot 0x4  overrides ContentsBase
    virtual undefined4 vf08();  // 008DB9F0 slot 0x8  overrides ContentsBase
    virtual void vf0C();  // 008DBAA0 slot 0xC  overrides ContentsBase
    virtual void vf10();  // 008DBA20 slot 0x10  overrides ContentsBase
    // non-virtual members
    SlashTestContents();  // 008DB520
    void ctor_008DC110();  // 008DC110
};
