// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Slot.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct SlashStartSlotPl0010 : public Slot {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00();  // 00B84B70 slot 0x0  overrides Slot
    virtual void vf10();  // 00B79DF0 slot 0x10  overrides Slot
    virtual void vf14();  // 00B79E00 slot 0x14  overrides Slot
    virtual void vf18();  // 00B84AC0 slot 0x18  overrides Slot
};
