// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct SlipFallStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B82720 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B91290 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00B82680 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00B826A0 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BB19A0 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00BB1B00 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00B826B0 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00B826C0 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B826E0 slot 0x24  overrides StateMachineNode
};
