// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Slot {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00();  // 004055E0 slot 0x0
    virtual void vf04();  // 00D89870 slot 0x4
    virtual void vf08();  // 00D89880 slot 0x8
    virtual void vf0C();  // 00D89890 slot 0xC
    virtual void vf10() = 0;  // 00FDB68B slot 0x10
    virtual void vf14() = 0;  // 00FDB68B slot 0x14
    virtual void vf18() = 0;  // 00FDB68B slot 0x18
    // non-virtual members
    Slot();  // 00A8FC50
    void ctor_00B79D60();  // 00B79D60
};
