// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "sMapInfoRayCastWork.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct sMapInfoRayCastBidirectionalWork : public sMapInfoRayCastWork {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 vf04(byte param_2);  // 00969600 slot 0x4  overrides sMapInfoRayCastWork
    virtual undefined4 vf14();  // 00966C60 slot 0x14  overrides sMapInfoRayCastWork
};
