// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineFactory.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct StateMachineFactoryPl1500 : public StateMachineFactory {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(undefined4 param_1);  // 008AA330 slot 0x0  overrides StateMachineFactory
    virtual undefined4 * vf04(byte param_2);  // 008A8C60 slot 0x4  overrides StateMachineFactory
};
