// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 0085C5F0 slot 0x0
    virtual undefined4 * vf04(byte param_2);  // 0085C630 slot 0x4
    virtual bool vf08(undefined4 param_1);  // 00D82210 slot 0x8
    virtual void SafeCheck(undefined4 * param_2);  // 00D82220 slot 0xC
    virtual void qteSafeCheck(undefined4 * param_2);  // 00D82260 slot 0x10
    virtual void vf14(undefined4 * param_2);  // 00D822A0 slot 0x14
    virtual undefined4 vf18(undefined4 param_2);  // 00D822E0 slot 0x18
    virtual undefined4 vf1C(undefined4 param_2);  // 00D82320 slot 0x1C
    virtual undefined4 vf20(undefined4 * param_1);  // 00D82360 slot 0x20
    virtual bool vf24(undefined4 param_1);  // 00D823A0 slot 0x24
    // non-virtual members
    StateMachineNode();  // 0085F010
    void ctor_00860270();  // 00860270
    void ctor_008A4010();  // 008A4010
    void ctor_008A4A50();  // 008A4A50
    void ctor_00B81330();  // 00B81330
    void ctor_00B82010();  // 00B82010
    void ctor_00B837E0();  // 00B837E0
    StateMachineNode(undefined4 param_2);  // 00D82530
};
