// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "hkDataArrayImpl.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct StructArrayImplementation : public hkDataArrayImpl {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual int vf00(byte param_2);  // 010F44C0 slot 0x0  overrides hkDataRefCounted
    virtual void vf04();  // 010F39D0 slot 0x4  overrides hkDataArrayImpl
    virtual void vf08();  // 010F3C50 slot 0x8  overrides hkDataArrayImpl
    virtual void vf0C(int param_2);  // 010F3C90 slot 0xC  overrides hkDataArrayImpl
    virtual void vf10(int param_2);  // 010F3CC0 slot 0x10  overrides hkDataArrayImpl
    virtual int vf14();  // 010F39F0 slot 0x14  overrides hkDataArrayImpl
    virtual undefined4 vf18();  // 010F3F50 slot 0x18  overrides hkDataArrayImpl
    virtual undefined4 vf1C();  // 010F39E0 slot 0x1C  overrides hkDataArrayImpl
    virtual undefined4 vf20();  // 010F38E0 slot 0x20  overrides hkDataArrayImpl
    virtual undefined4 vf28(undefined4 param_2);  // 010F3F60 slot 0x28  overrides hkDataArrayImpl
    virtual void Object(int param_2);  // 010F3BA0 slot 0x5C  overrides hkDataArrayImpl
    virtual void vf60(int param_2, undefined4 param_3);  // 010F3BE0 slot 0x60  overrides hkDataArrayImpl
    // non-virtual members
    StructArrayImplementation();  // 010F37C0
};
