// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "../../ghidra_types.h"
#include "../fwd.h"

struct TargetManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00() = 0;  // 00FDB68B slot 0x0
    virtual void vf04() = 0;  // 00FDB68B slot 0x4
    virtual undefined4 * vf08(byte param_2);  // 00C12530 slot 0x8
    virtual void vf0C() = 0;  // 00FDB68B slot 0xC
    virtual void vf10() = 0;  // 00FDB68B slot 0x10
    virtual void vf14() = 0;  // 00FDB68B slot 0x14
    virtual undefined4 vf18() = 0;  // 00FDB68B slot 0x18
    virtual void vf1C(int param_2) = 0;  // 00FDB68B slot 0x1C
    virtual undefined4 vf20() = 0;  // 00FDB68B slot 0x20
    virtual void vf24(int param_2) = 0;  // 00FDB68B slot 0x24
    virtual undefined4 vf28() = 0;  // 00FDB68B slot 0x28
    virtual void vf2C(int param_2) = 0;  // 00FDB68B slot 0x2C
    virtual undefined4 vf30() = 0;  // 00FDB68B slot 0x30
    virtual undefined vf34() = 0;  // 00FDB68B slot 0x34
    virtual undefined4 vf38(int param_1) = 0;  // 00FDB68B slot 0x38
    virtual undefined4 vf3C() = 0;  // 00FDB68B slot 0x3C
    virtual void vf40(int param_2) = 0;  // 00FDB68B slot 0x40
    virtual undefined4 vf44(undefined4 * param_1) = 0;  // 00FDB68B slot 0x44
    virtual undefined4 vf48() = 0;  // 00FDB68B slot 0x48
    virtual void vf4C() = 0;  // 00FDB68B slot 0x4C
    virtual undefined4 vf50(undefined4 * param_1, undefined4 * param_2, int param_3) = 0;  // 00FDB68B slot 0x50
    virtual undefined4 vf54(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3) = 0;  // 00FDB68B slot 0x54
    virtual int vf58(int param_1, float param_2, float param_3, float param_4) = 0;  // 00FDB68B slot 0x58
};
