// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "TargetManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct TargetManagerImplement : public TargetManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual void vf00();  // 00C15760 slot 0x0  overrides TargetManager
    virtual void vf04();  // 00C15770 slot 0x4  overrides TargetManager
    virtual undefined4 * vf08(byte param_2);  // 00C157A0 slot 0x8  overrides TargetManager
    virtual void vf0C();  // 00C26580 slot 0xC  overrides TargetManager
    virtual void vf10();  // 00C26680 slot 0x10  overrides TargetManager
    virtual void vf14();  // 00C26760 slot 0x14  overrides TargetManager
    virtual undefined4 vf18();  // 00C26AF0 slot 0x18  overrides TargetManager
    virtual void vf1C(int param_2);  // 00C26B60 slot 0x1C  overrides TargetManager
    virtual undefined4 vf20();  // 00C26BC0 slot 0x20  overrides TargetManager
    virtual void vf24(int param_2);  // 00C26C40 slot 0x24  overrides TargetManager
    virtual undefined4 vf28();  // 00C26CB0 slot 0x28  overrides TargetManager
    virtual void vf2C(int param_2);  // 00C26D30 slot 0x2C  overrides TargetManager
    virtual undefined4 vf30();  // 00C26DA0 slot 0x30  overrides TargetManager
    virtual undefined vf34();  // 00C26DB0 slot 0x34  overrides TargetManager
    virtual undefined4 vf38(int param_1);  // 00C26F40 slot 0x38  overrides TargetManager
    virtual undefined4 vf3C();  // 00C26FC0 slot 0x3C  overrides TargetManager
    virtual void vf40(int param_2);  // 00C157C0 slot 0x40  overrides TargetManager
    virtual undefined4 vf44(undefined4 * param_1);  // 00C27040 slot 0x44  overrides TargetManager
    virtual undefined4 vf48();  // 00C157F0 slot 0x48  overrides TargetManager
    virtual void vf4C();  // 00C15800 slot 0x4C  overrides TargetManager
    virtual undefined4 vf50(undefined4 * param_1, undefined4 * param_2, int param_3);  // 00C595E0 slot 0x50  overrides TargetManager
    virtual undefined4 vf54(undefined4 * param_1, undefined4 * param_2, undefined4 * param_3);  // 00C59850 slot 0x54  overrides TargetManager
    virtual int vf58(int param_1, float param_2, float param_3, float param_4);  // 00C27130 slot 0x58  overrides TargetManager
    // non-virtual members
    TargetManagerImplement();  // 00C15740
    void ctor_00C26530();  // 00C26530
};
