// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct WalkStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B82A10 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B91330 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00B829A0 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00BB2550 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BCCC40 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00BB2600 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00B829C0 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00BB2690 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B829D0 slot 0x24  overrides StateMachineNode
};
