// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "WindManager.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct WindManagerImplement : public WindManager {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 * vf00(byte param_2);  // 008E07A0 slot 0x0  overrides WindManager
    virtual undefined vf04();  // 008E02F0 slot 0x4  overrides WindManager
    virtual int * vf08(int param_2);  // 008DFFD0 slot 0x8  overrides WindManager
    virtual void vf0C(float param_1, undefined4 * param_2);  // 008E0210 slot 0xC  overrides WindManager
    virtual void vf10(undefined4 param_2);  // 008DFE40 slot 0x10  overrides WindManager
    virtual void vf14(int param_2);  // 008E03C0 slot 0x14  overrides WindManager
    virtual void vf18();  // 008DFE90 slot 0x18  overrides WindManager
};
