// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Behavior.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct Wp030a : public Behavior {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined4 destruct(byte param_2);  // 00AB7900 slot 0x0  overrides cParts
    virtual undefined * vf04();  // 00AA6770 slot 0x4  overrides cObj
    virtual undefined4 startup();  // 005FF640 slot 0x40  overrides Behavior
    virtual void vf44();  // 005FF650 slot 0x44  overrides Behavior
    virtual void vf4C();  // 005FF6A0 slot 0x4C  overrides Behavior
    virtual void vf50();  // 005FF630 slot 0x50  overrides Behavior
    virtual undefined4 vf1B0();  // 005FF660 slot 0x1B0  overrides Behavior
    // non-virtual members
    Wp030a();  // 00AA6750
};
