// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "Slot.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ZangekiModeExitSlot : public Slot {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined vf00();  // 0093E290 slot 0x0  overrides Slot
    virtual void vf10();  // 0093D9E0 slot 0x10  overrides Slot
    virtual void vf14();  // 0093D9F0 slot 0x14  overrides Slot
    virtual void vf18();  // 0093E280 slot 0x18  overrides Slot
    // non-virtual members
    ZangekiModeExitSlot();  // 00943500
};
