// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ZangekiHoldStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B83100 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B916A0 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00BE2410 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00B83090 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BE2560 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00B830A0 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00B830B0 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00BB5E40 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B830C0 slot 0x24  overrides StateMachineNode
};
