// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ZangekiMoveStatePl1400 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 008600E0 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00868D60 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00872F80 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00860060 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00897F70 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00860070 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00860080 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00873590 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00860090 slot 0x24  overrides StateMachineNode
    // non-virtual members
    ZangekiMoveStatePl1400();  // 008600B0
};
