// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ZangekiHugeCutLeftToRightStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B832B0 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B91700 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00BB6420 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00B83240 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BE3740 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00B83250 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00B83260 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00BB6530 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B83270 slot 0x24  overrides StateMachineNode
};
