// generated by tools/gen_headers.py from RTTI + Ghidra prototypes
#pragma once
#include "StateMachineNode.h"
#include "../../ghidra_types.h"
#include "../fwd.h"

struct ZangekiOnPartsStatePl0010 : public StateMachineNode {
    // virtual functions, in vftable order (slot = byte offset / 4)
    virtual undefined * vf00();  // 00B837D0 slot 0x0  overrides StateMachineNode
    virtual undefined4 * vf04(byte param_2);  // 00B918B0 slot 0x4  overrides StateMachineNode
    virtual bool vf08(undefined4 param_1);  // 00BB75F0 slot 0x8  overrides StateMachineNode
    virtual void SafeCheck(undefined4 * param_2);  // 00BCFF40 slot 0xC  overrides StateMachineNode
    virtual void qteSafeCheck(undefined4 * param_2);  // 00BFFF20 slot 0x10  overrides StateMachineNode
    virtual void vf14(undefined4 * param_2);  // 00B83760 slot 0x14  overrides StateMachineNode
    virtual undefined4 vf18(undefined4 param_2);  // 00B83770 slot 0x18  overrides StateMachineNode
    virtual undefined4 vf20(undefined4 * param_1);  // 00BD0590 slot 0x20  overrides StateMachineNode
    virtual bool vf24(undefined4 param_1);  // 00B83780 slot 0x24  overrides StateMachineNode
    // non-virtual members
    ZangekiOnPartsStatePl0010();  // 00B837A0
};
